xh/hoist-react

cmp/contextmenu/ContextMenu.js

Saw the context menu throwing when testing an unrelated change.
We were using oneOf but:
"PropTypes.oneOf is a simple enum of literal values. It means that if you’re going to pass a value to this component, it better be one of these exact values."
Came across this:
https://github.com/facebook/react/issues/1919
https://jaketrent.com/post/react-oneof-vs-oneoftype/

PropType check for menu item should be 'oneOfType'

---

cmp/form/NumberField.js

The only way we were ending up with this problem was to either tab and then out of the field without entering any input or to delete preexisting input which would pass an empty string to parseFloat and give us 'NaN'.
This NaN value was invisible in the UI and was almost certainly not what was intended by the user.
This surfaced out of the type switching problem (where you see the left over value in a new control). I'm working on that in another branch but it seemed like this numberField behavior would still be wrong once that is fixed.

Do not set non-number values on hoist numberFields

---

admin/tabs/monitor/MonitorResultsModel.js
promise/Promise.js
svc/TrackService.js

Removed exception property from the service.
Added doc, and added support for msg & messages.
In removing the exception property from the service, I was obliged to remove it from the promise's use of track.  The assumption being that we will just not log promise exceptions at all.  That may be the wrong assumption.

track service updates

---

svc/ErrorTrackingService.js

This null was getting converted to a string by fetch, and then saved as such. I have a fix in place to handle this in hoist core, but better to not create the problem in the first place I think.

Send empty string in place of null as message for Client Error

---

exception/ExceptionHandler.js

This change was made in Hoist Sencha last week to solve a client app problem. We should be consistant here.

For exceptions, default logOnServer to showAsError value

---

cmp/rest/RestControlModel.js

This ensures that we do not null them out upon opening an edit form.

Only null out typeFields if form isDirty, Fixes #310

---

cmp/dataview/DataView.js

Dataview should take the whole record as it's value, rather than the id, to ensure the cell refreshes on data change

Dataview should refresh on data change

---

cmp/form/dropdown/BaseComboField.js

+ Only attempt to commit onBlur and onKeyPress if !requireSelection. Allows us to remove label matching logic. Fixes #353.
+ Debounce commits. Display internalValue during wait to mask for user. Fixes #354.

Combofield fixes, Fixes #353, Fixes #354

---

admin/App.js
admin/AppModel.js
cmp/appbar/AppBar.js
cmp/appbar/AppBar.scss
cmp/appbar/AppBarSeparator.js
cmp/appbar/index.js
cmp/tab/TabSwitcher.js

#307 
I left the built-in refresh button out since there isn't yet a consistent way to refresh an app, seems like that is a different story and the standard button can be added to AppBar once that mechanism is decided on.
I also updated the Admin app to put the TabSwitcher in the AppBar.
See https://github.com/exhi/toolbox/pull/18 for toolbox usage of the new component

AppBar Component

---

desktop/cmp/tab/container/TabContainerModel.js
desktop/cmp/tab/pane/TabModel.js
desktop/cmp/tab/switcher/TabSwitcher.js

#451 
Just a slight re-organization of the code for setting the `activeTabId` to allow the router state to drive updating the `activeTabId` value when using routing. This is to fix a sync issue where a route change could be rejected by middleware of a canDeactivate handler, and the TabContainer would still change the active tab.

Ensure TabContainer activeTabId is in sync with the router state (Fixes #451)

---

desktop/cmp/grid/Grid.js

#464 
I enabled multi-select on the standard grid example in Toolbox for testing and to demonstrate the bug this is fixing.

Clear the selection when showing context menu for unselected record (Fixes #464)

---

template/index.html

On mobile devices, the viewport automatically zooms upon focusing an input. This change prevents that by preventing scaling.
Tested on device in the context of a client-app. Does not seem to have any side-effects for desktop apps (i.e. user can still zoom using the browser zoom).
This _does_ break W3C accessibility guidelines (https://www.w3.org/TR/mobile-accessibility-mapping/#zoom-magnification), but I would argue they don't really apply, given that we are going for a 'native' app feel rather than an responsive app.

Prevent automatic zooming upon input focus on mobile devices

---

admin/tabs/activity/clienterrors/ClientErrorPanel.js
admin/tabs/activity/tracking/ActivityGrid.js
admin/tabs/activity/tracking/VisitsChart.js
desktop/cmp/form/HoistField.js

Seems like it's possible dayFields should be commitOnBlur by default instead. But for now this fixes https://github.com/exhi/hoist-react/issues/513

DayFields in Hoist Admin tabs commitOnChange

---

admin/App.js
admin/AppComponent.js
admin/tabs/activity/tracking/ActivityGrid.js
core/HoistApp.js
desktop/cmp/appbar/AppBar.js
desktop/cmp/button/RefreshButton.js

#390 
Went with `requestRefresh` method on the App since that was the pattern we are following with the Tabs (and was already what the Admin app was using). Decided against using an event for now since we don't really seem to be using events much, and the App will probably need to drive the refresh from the top-down most of the time.

Global App refresh method + default AppBar RefreshButton handler

---

columns/Column.js

These props can be specified as strings (in our agOptions) as documented by ag-grid. However, if passing a string here along with an align prop, our method was throwing when we tried to push our xh alignment class onto that string.

Cast headerClass and cellClass to array before pushing to it

---

desktop/cmp/dataview/DataView.js
desktop/cmp/dataview/DataViewModel.js

Minor enhancement to pass the DataView store in the item component props (along with the item record). The need for this arose in a client app where my data view items have buttons to perform crud operations so they need access to the store.

Pass the store through to the data view item component

---

core/XH.js
desktop/cmp/rest/data/RestStore.js
package.json
svc/FetchService.js
yarn.lock

This change is part of improvements made to the framework to support a proxy service (https://github.com/exhi/hoist-core/issues/49)
Many api calls will be made with posting a json body, which our current fetch wrapper does not support.

Support posting JSON body with content-type application/json.

---

cmp/form/HoistField.js
core/HoistApp.js
core/HoistComponent.js
core/HoistModel.js
core/HoistService.js
core/mixins/EventSupport.js
core/mixins/LayoutSupport.js
core/mixins/ReactiveSupport.js
desktop/cmp/contextmenu/ContextMenuSupport.js
field/FieldSupport.js
utils/js/ClassUtils.js

This formalizes (and fixes) our evolving ad-hoc method for marking classes in mixins with an identifying flag. 
Also, actually using this now to introspect the presence of FieldSupport.

Support for markClass

---

columns/Column.js

The ag-grid docs are misleading - the column tooltip function actually has a single `params` object, with the documented `value, valueFormatted, data, node , colDef, rowIndex and api` as properties (similar to renderer function). We need to deconstruct `data` from this object in order to pass it to tooltip fn.

Fix: Column tooltip fn gets record data as second argument.

---

desktop/cmp/form/dropdown/BaseDropdownField.js
desktop/cmp/form/dropdown/ComboField.js
desktop/cmp/form/dropdown/QueryComboField.js
desktop/cmp/form/dropdown/SelectField.js

+ Ensures component implementations are re-rendered when props.options change and are "re-normalized" back into this internal collection.
+ Fixes #591

Make DropDownField internalOptions observable

---

core/XH.js
data/LocalStore.js

+ Add XH.genId() to return locally-generated unique ID.
+ LocalStore uses XH.genId() if raw records do not contain an ID property.
+ LocalStore replaces null record IDs with generated IDs (not just undefined).
+ LocalStore warns if records contain non-unique IDs.
+ Minor re-org of some XH method blocks and comments.
+ Fixes #590

Add XH.genId(), update LocalStore ID generation + validation

---

desktop/cmp/form/TextField.js

This is a bit of a strange one, but see the link in the comment for the rationale behind 'nope'.
Example of the value of this here can be see in toolbox -- just the presence of a 'First Name/ Last Name' label in the vicinity of the input causes chrome to aggressively do an autofill, even with autoComplete= 'off'  !

Add support for autoComplete prop in TextField Fixes #581

---

desktop/cmp/grid/GridModel.js

#644
Didn't dig too deep, but probably broke with the column definition refactoring, just needed to look for the `rowGroup` property in the correct place.
Added example of changing the groupBy field to toolbox in https://github.com/exhi/toolbox/commit/a3fa4485babde8af642db083e398f414c6c43005

Fix issues with changing groupBy after initial call

---

columns/Column.js

+ I decided not to add a Toolbox example for now, until we get some better sample data so we can have grids with wider / more filled out column sets where you could actually see the scrolling. But I did test the true/left/right variants.

Promote "pinned" to top-level Column config

---

desktop/cmp/contextmenu/StoreContextMenu.js
desktop/cmp/grid/GridModel.js
desktop/cmp/grid/ag-grid/styles.scss

+ Note fix to actually set the observable groupBy within `GridModel.setGroupBy()` - even if we don't want this overall change we should be sure to apply that!
+ Context menu token provided to add both actions at once - I didn't see a use-case for only adding one...
+ Added to default context menu, although items will hide if grid is not tree/grouped.
+ Warning in comment on expandAll that this is recursive. Further work could absolutely be smarter about expanding only a single level, or optionally expanding only the selected node.
+ Center align grid context menu icons - looked much better with > icon.
+ Fixes #640

Add GridModel.expandAll() and collapseAll() w/context menu tokens

---

desktop/cmp/grid/Grid.js

+ We should look at debouncing `GridModel.noteAgColumnStateChanged()`. In normal usage this change does not appear to generate extra calls to the model, but e.g. double-clicking a column header border to auto-size appears to fire two dragEnd and one autoSize events, resulting in three calls.
+ Fixes #670

Ensure column size changes due to autoSize are flushed to GridModel

---

desktop/cmp/grid/GridModel.js

+ Need to search / iterate over leaf-level columns when evaluating new groupBy
+ Current code will throw for grouped column grids with NPE on agOptions for parent group configs. This fixes that (clearly bad) situation, but also ensures we look in the leaves for groupable cols.
+ Change pushed to Toolbox develop branch to add switch on grouped col sample grid to turn on row grouping as a test case.

Support row grouping when column-level grouping also active

---

core/ExceptionHandler.js
exception/Exception.js
svc/FetchService.js

This resolves issue: https://github.com/exhi/hoist-react/issues/698
There is a corresponding toolbox branch (fetchservice_cancel) which does not need to be merged in, but can be used to test this implementation by cancelling News refreshes.

Implementation of fetchservice cancellable by requestKey

---

data/RecordAction.js
desktop/cmp/contextmenu/StoreContextMenu.js
desktop/cmp/grid/Grid.js

Encountered a couple issues while using the new features in a client-app. The main change here is adding support for dynamic sub menus returned from the `displayFn` callback. Previously we were just taking them and assuming that they are RecordActions (which they would have been if they were statically defined in the RecordAction config).

RecordAction sub-menu fix

---

cmp/grid/Grid.js
cmp/grid/GridModel.js
cmp/grid/columns/Column.js
data/Field.js
data/Record.js

+ Our implementation of getDataPath() -> Record.xhTreePath results in treeColumn cells having the record ID as their underlying value via the node's groupData property. This is prioritized by default over the field value for filtering, sorting, and copying.
+ Fixes #679

Fixes to value handling for treeColumn

---

field/FieldSupport.js
utils/js/Decorators.js
utils/js/index.js

I went back and forth on whether to throw, or just console.error, but ultimately decided to throw.
If you were to just spell the decorator wrong, (e.g. 'feild') it throws at runtime in the browser, so I thought it made sense to do the same here.

Parameterized decorator check

---

core/XH.js

+ Provides a clearer exception when Grails server is down or unreachable vs. generic service failure.
+ Fixes #758

Special exception handling for EnvironmentService init

---

svc/ConfigService.js
svc/EnvironmentService.js
svc/IdentityService.js
svc/PrefService.js
utils/js/LangUtils.js

Note that this could represent a breaking change for any apps that are depending on the current behavior of PrefService and CloneService to clone the return from get().  These apps would simply need to do the clone themselves.  It should be a very visible and easy to fix failure.
I think this establishes a safer and more efficient pattern for shared data.
Still to do, making localStorageService freeze() as well.  This is a bit trickier.
Also, if people approve of this approach, I can go ahead and add some discussion of this in the documentation.

Deep Freeze Shared enumerable data from various services

---

desktop/cmp/rest/impl/RestControl.js

Avoid mutating lookup results when adding 'null' in RestControl Select inputs. 

---

core/XH.js
desktop/cmp/form/inputs/Select.js
desktop/cmp/form/inputs/Select.scss
static/index.html

+ Allows us to avoid using the styles() API within the Select input component itself to control menu portal z-index (reserving that react-select prop as something an app could leverage if needed to style other aspects of its components).
+ Rename existing 'root' div to 'xh-root' to use our namespace in that context as well.

Create top-level DOM node for Select menu portal

---

desktop/cmp/form/inputs/Checkbox.js
desktop/cmp/form/inputs/SwitchInput.js

Needs branch in hoist-core merged first as well.  Hoist Core branch improves serialization of prefs and configs

Remove workaround in boolean controls to handle string values

---

svc/EnvironmentService.js

+ Clearly we could do this in a number of places - XH.js being a likely alternative. EnvironmentService seemed like a reasonable place, too, and that's what we have here. Could also format in various ways, make optional, etc. but didn't want to over-complicate.

 Append (non-prod) environment to app title

---

cmp/grid/columns/Column.js
cmp/grid/impl/GridSorter.js

Column.comparator is used by ag-grid's column filters to sort the available options in a set filter - we should fall back to default comparator if we don't have a sorter in the GridModel.

Column comparator falls back to default comparator.

---

cmp/grid/GridStateModel.js

Fixes #804 
If the value coming from the state is undefined, do not update the GridModel.
The value in the state will be undefined when:
* The grid state was saved before we supported the specific state property
* No state has yet been saved for the grid
* The specific state property of the grid has not been changed by the user

Don't set grid state for undefined values

---

styles/XH.scss

We have relied on blueprint css to default all DOM elements to `box-sizing: border-box`. See [here](https://github.com/palantir/blueprint/blob/4e93d2f5d8965aa2864759b663c70640b589ecd0/packages/core/src/_reset.scss#L9).
Since we're no longer applying blueprint styling to the mobile app, we need to set this property ourselves.

border-box styling for mobile

---

cmp/form/HoistInput.js

so same array or same object comparisons do not trigger false change events.

Replace === with lodash isEqual 

---

desktop/cmp/store/StoreFilterField.js

Fixes #821 
Make sure that includeFields is used if there is no store associated with the component.
Note that in Toolbox, the News grid had a bug where the store filter field would overwrite the source filter, because a store was being provided. Removing that (https://github.com/exhi/toolbox/commit/4140f328f96b565f51b88a1e15a6629d6941845b) reproduces the bug this pr fixes.

Store filter field no store fix

---

CHANGELOG.md
mobile/cmp/toolbar/Toolbar.js
mobile/cmp/toolbar/Toolbar.scss
mobile/cmp/toolbar/ToolbarSeparator.js
mobile/cmp/toolbar/index.js

Onsen's toolbars are absolutely positioned, which raises a number of issues (you can only have 1 top and / or bottom toolbar per page, they can overlap other components etc).
This change brings symmetry between the desktop and mobile toolbar implementations. Prompted by an immediate need in a client app.
Please also see Toolbox example:
https://github.com/exhi/toolbox/pull/116

Mobile toolbars

---

desktop/cmp/form/inputs/TextInput.js

Added to TextInput - BPs NumberInput does not support a rightElement. Resolves #807.

Add 'enableClear' prop to show a built-in 'clear value' affordance to TextInput.

---

desktop/cmp/form/inputs/Select.js

Hi,
implementing this fix requires using a ref on the react select props, which will be overwritten if a user assigns their own ref via rsOptions.  
Just pointing that out for consideration.  One solution might be to only create this ref and wrap the reactSelect in a box if 'popoverMode' = true.  Happy to discuss.
-Colin

Select input:  stopPropagation of key event only when menuIsOpen = true

---

desktop/cmp/rest/RestGrid.js
desktop/cmp/rest/RestGridModel.js
desktop/cmp/rest/impl/RestFormModel.js

For #869 
- RestGrid takes an editable prop with default = true
- RestGrid.editable controls default menu buttons
- allow onRowDoubleClicked prop
- rowDoubleClicked defaults to edit if editable, view if not

RestGrid Editable Mode

---

admin/tabs/general/about/AboutPanel.js

This is implemented with the following choices:
The new datasource info (NDI) comes in on the /xh/environment endpoint only if the user is an admin user.
The NDI is not displayed on mobile.  Seems like when someone wants to know this, they will be debugging at a desktop, and we should save space on mobile.
The NDI presents 3 props: 
databaseConnectionString
databaseCreateMode
databaseUser
See also hoist-core PR: https://github.com/exhi/hoist-core/pull/67

Display datasource info in Admin (Fixes hoist-react #829)

---

desktop/cmp/chart/Chart.js
package.json
yarn.lock

Also Fixed chart exporting.
Exporting is now disabled by default.

Update Highcharts to v7.0.1 (Fixes hoist-react #853)

---

desktop/cmp/input/DateInput.js

+ Fix broken commitOnChange getter
+ Fix https://github.com/exhi/hoist-react/issues/848
+ Clean up handling of "Invalid Dates"
+ Tighten up code around min and max date handling.
+ Rename inputRef variable for clarity (there actually is a different 'inputRef
Still think we have serious issues with this control, and would like to consider alternative implementations, but this definitely pushes us in the right direction.

Misc. fixes to DateInput (Fixes #848)

---

desktop/cmp/panel/impl/ResizeContainer.js

Fixes https://github.com/exhi/hoist-react/issues/685
I don't think this is the last word in panel resizing by any means -- in particular, would like to have a better way for components that are layout siblings with a resizer to declare a minimum-size (based on their own header or splitter) so they don't get completely overwhelmed.
But in any case, this prevents the horrible situation of any particular resize container going beyond the bounds of its own parent.

Fix to Panel Resizing

---

cmp/grid/Grid.js
cmp/grid/GridModel.js

For #785. If we wanted to handle this all in one place, could also use ag api's onModelUpdated

Resize columns after tree grid expand/collapse

---

kit/blueprint/styles.scss

Two css tweaks to handle #862. Note that I used `break-all` instead of `break-word`. Think it looks better at least in the case of error messages, i.e. not forcing very long strings to occupy a new line.

Dialog text overflow

---

desktop/cmp/input/Select.scss
kit/onsen/styles.scss
mobile/cmp/input/Select.scss
styles/XH.scss
styles/vars.scss

For #782 - using color picker tool, determined that the default input placeholder (Mac, Chrome) is rgb(175, 183, 191). Rather than try to set `select`'s placeholder color for each browser/device, thought it would be better to enforce placeholder color across all XH inputs. Used `::-webkit-input-placeholder` selector for that purpose.

Enforce standard placeholder color across all xh inputs, mobile/desktop

---

desktop/cmp/rest/data/RestStore.js

Pretty common need when using a RestStore outside the context of a RestGrid (or grid in general) is to be able to get a reference to the new Record that was just saved/added. I specifically ran into this when doing a "Save As.." type of operation and I wanted to update the selection to the new Record after the save operation completed.

RestStore returns the new Record after a save

---

cmp/form/field/FieldModel.js

Fixes subtle bug when using FormModel in a certain way.
From slack convo:
```I have a form, which can be ‘applied’, and when applied I am updating the associated record in my store, and then calling `formModel.init()` to effectively tell the FormModel that the current values are now your initial values, and this form stays on the screen. However, I am using the `isDirty` computed prop on the FormModel to control whether the apply button is enabled or disabled, and found that the `isDirty` is not being re-computed after calling `init()` on the FormModel because the `value` in the `FieldModel` is not actually changing, only the `initialValue` is, and `initialValue` is not observable```

Observable initialValue for FieldModel

---

kit/onsen/styles.scss
kit/onsen/theme.scss
kit/onsen/vars.scss
mobile/cmp/button/Button.js

Tweaks to mobile ButtonGroupInput derived from usage in the wild:
+ Tweak styling to make a clearer distinction between selected / unselected buttons.
+ Move styling rules to our stylesheet rather than theme

Mobile ButtonGroupInput tweaks

---

cmp/grid/GridModel.js
desktop/cmp/grid/impl/ColChooserModel.js
desktop/cmp/store/StoreFilterField.js
svc/GridExportService.js

+ Use in grid export + storeFilterField integrations, to reliably query for visible cols only when required.
+ Some smaller doc comment and syntax updates for clarity
+ Fixes #935

Add excludeHidden opt to GridModel.getLeafColumns()

---

admin/tabs/general/ehcache/EhCacheModel.js
admin/tabs/general/services/ServiceModel.js
admin/tabs/logging/viewer/LogViewerModel.js
data/LocalStore.js
data/impl/RecordSet.js

This fixes https://github.com/exhi/hoist-react/issues/844
Motivation was that a client was recently hit very hard by these auto-generated ids.  auto-refreshing grid with tens of thousands of rows was in production for weeks without ids, causing performance problems and memory issues.
Also, client noted that agGrid itself warns about missing ids, so we were actually papering over that warning by silently creating these ids for users.

Force Users to opt-out of stable ids on Records

---

desktop/cmp/form/FormField.js
desktop/cmp/form/FormField.scss

+ Simplify conditions surrounding FormField sizing - HoistInputs within FormField always fill the FormField (unless sized themselves).
+ Fix CSS target to fill HoistInput within FormField
See toolbox branch: https://github.com/exhi/toolbox/pull/153

Form field sizing redux

---

cmp/input/HoistInput.js
desktop/cmp/input/TextInput.js

This changes behavior to: 
- Icon not displayed on component mount (assuming no initialValue)
- Clear Icon is displayed as soon as text entered
- From that point, the icon display status mirrors the input's committed value. (note, textinput now converts empty string to null onCommit)

Text Input Clear Icon

---

desktop/cmp/form/FormField.js
desktop/cmp/form/FormField.scss
desktop/cmp/input/JsonInput.scss

+ Tweak CSS height for an 'unsized' json input to match the code default. Fixes #997.
+ Added CSS class to FormField indicating the type of child input.
+ Fixed label alignment in inline mode.

Default JsonInput height

---

data/LocalStore.js
desktop/cmp/rest/data/RestStore.js

Fixes #1010 
Minor refactor to allow creating a single Record, and use that method in RestStore after the save operation.

Use consistent process when creating Records

---

CHANGELOG.md
admin/tabs/activity/clienterrors/ClientErrorModel.js
admin/tabs/activity/tracking/ActivityGridModel.js
admin/tabs/general/configs/differ/ConfigDifferModel.js
admin/tabs/general/users/UserModel.js
cmp/grid/GridModel.js
desktop/cmp/filechooser/FileChooserModel.js
desktop/cmp/leftrightchooser/LeftRightChooserModel.js

+ Clean up instances where we were creating a new LocalStore inline
+ Mark created store as managed within GridModel. Note that stores do not yet actually implement destroy() but will when #1014 complete.
+ Fixes #1013

GridModel.store config accepts a plain object, creates LocalStore

---

desktop/cmp/dataview/DataViewModel.js

+ Did not see a need to save extra references to the ctor params, added getter for store and selModel.
+ Rely on GridModel to parse selModel and store configs, including recently added support for plain object store configs.

DataViewModel - remove dupe references to GridModel properties

---

cmp/input/HoistInput.js

This workaround was causing tricky problems for apps that were getting stale data during this interval.

Remove 'delay' workaround to avoid focus blurring.

---

desktop/cmp/form/FormField.js
desktop/cmp/form/FormField.scss

I moved the application of the min width out of the css and into JS, and only apply it if a specific labelWidth has not been provided. This maintains the current expected behaviour, while allowing labels narrower than 80px.
Another potential solution would be to remove the concept of a min width entirely - labels are either sized explicitly, or use their natural size. This may be a simpler API, but may potentially be a breaking change to any apps currently depending on the min width.

Allow FormField labelWidth to override min width.

---

cmp/grid/Grid.js
cmp/grid/GridModel.js
cmp/grid/ag-grid/styles.scss
styles/vars.scss

+ Support rowBorders and stripeRows observables on GridModel.
+ Borders off by default, row striping remains on.
+ Move Grid.showHover prop -> GridModel.highlightOnHover.
+ Update grid variant CSS class names to BEM conventions.
+ Ensure Hoist border-color CSS var actually applies, then set to a lighter value.

Updates to Grid style / visual config and CSS

---

cmp/form/field/BaseFieldModel.js

This fixes the issue of 
reset() not triggering a rerun of computeValidationAsync 
when this.value is not changed in reset().

Bugfix: run computeValidationAsync on reset

---

CHANGELOG.md
cmp/grid/Grid.js
cmp/grid/GridModel.js
cmp/grid/ag-grid/styles.scss
styles/vars.scss

+ Fixes #946
+ Tweak to also avoid (existing) shifting on right-aligned focused cells
+ Lighten up grid row borders in general if shown

GridModel option to show cell focus

---

CHANGELOG.md
cmp/form/FormModel.js

The fact that formModel.isNotValid is not *always* equal to !formModel.isValid caught Arjun up.
See the changelog for a description of the reasoning behind removing this.  I doubt it is widely used.

Remove confusing getter FormModel.isNotValid

---

desktop/cmp/form/FormField.js

See issue: https://github.com/exhi/hoist-react/issues/1031

Fix: Changing / reordering children within a FormContext can throw an Error

---

CHANGELOG.md
cmp/grid/Grid.js
cmp/grid/GridModel.js

+ Relays to defaultGroupSortCompator, avoid need to use agOptions.
+ Keep existing default that sorts groups according to their natural order.
+ Tweak contextMenuFn config handling for symmetry (requires review).
+ Remove unused/dupe init values on class fields declarations.

Add gridModel.groupSortFn for custom group sort

---

desktop/cmp/chart/theme/Dark.js
package.json
yarn.lock

From the HC side this upgrade is largely additive, with few breaking changes:
1. Changed default X axis tickWidth option. Now tick marks are not rendered by default on category axes. Set the tickWidth to 1 to bring back the old behaviour. 
-See note in PR below
2. Renamed plotOptions.treemap.drillUpButton to traverseUpButton. 
- We do not use this in HR or Toolbox, but could theoretically effect client apps.
3. Changed default states.inactive.opacity for map and mapline series to prevent dimming map shapes.
-  We do not use this in HR or Toolbox, but could theoretically effect client apps. But not sure I would consider this a 'breaking change'

Upgrade Highcharts to ~7.1.1, Fixes: #1056

---

admin/tabs/general/configs/differ/ConfigDifferModel.js
data/Store.js

A low pressure pull request here. This seemed like a useful-enough convenience method, and I can imagine it being helpful to have an official API for efficient clearing vs. apps calling `loadData([])` as they do currently.
Initially called it `clear()` and would like the short name, but consistency with existing `removeRecords(ids)` seemed worth it.

Add Store.removeAllRecords()

---

CHANGELOG.md
promise/Promise.js

Issue #1111 
Also linted and updated change log

`Promise.track` now accepts an optional `omit` flag

---

CHANGELOG.md
format/FormatNumber.js

`formatNumber` now accepts an optional `prefix` config to be prepended to value:
+ Re: ticket #1067, and its specified use case for dollar signs (`$`)
+ `prefix` before the number, but after the sign (if any)
+  e.g., `-$13.37` or `+$5.20`

Format number

---

cmp/ag-grid/AgGridModel.js
cmp/grid/Grid.js
core/appcontainer/OptionsDialogModel.js

Support for serialization of the ag-Grid state via AgGridModel.
Supports serialization of:
- Column state
- Pivot Mode on/off
- Sort config
- Filters (optional)
- Row group expand state (optional)
- Side bar state (currently opened panel) (optional)
Some of the state is data dependent, and it is important that it not be set until after data has been loaded, and should be understood that the state may not be valid for different data sets. The state which is data dependent is:
- Filters (specifically the excel style set filters)
- Expand state (depends on the row group keys)
- Sort config (only when in pivot mode - depends on the pivot keys)
TODO

ag-Grid State Serialization

---

CHANGELOG.md
desktop/cmp/filechooser/FileChooser.js
desktop/cmp/filechooser/FileChooserModel.js

`enableMulti` config now toggles to accept multiple files in a single upload:
+ behavior of prev. `enableMulti` is now delegated to `enableDropMulti` config
+ `enableDropMulti` configs dropzone to accept multiple files; it also enables the OS file picker pop-up window to pick multiple files
+ minor code tweak: destructed some configs from `props`

FileChooser.enableMulti actually to accept multiple files in single upload Issue # 1069

---

mobile/cmp/button/ButtonGroup.js

For example, when conditionally omitting buttons, etc.

Allow nulls in mobile ButtonGroup

---

cmp/grid/Grid.js
cmp/grid/GridModel.js
data/StoreSelectionModel.js

Fixes #1150 
The cause of the poor performance when programmatically selecting several records was that the ag-Grid onSelectionChanged event was being fired for each call we make to `node.setSelected(true)` (on the subsequent frame). This results in the Grid updating the selection model based on the current ag-Grid selection state, which would then trigger another selectionReaction in the grid, etc. So if you are selecting 1000 rows programmatically you would end up with 1000 extra updates of the observable.ref `ids` property of StoreSelectionModel, and 1000 extra calls to the Grid selectionReaction. The selectionReaction would be a no-op because we do check that before updating the ag-Grid state, but we did not have a similar check on the other end before we update our selection model …

Grid/Store Selection Optimizations

---

CHANGELOG.md
cmp/grid/Grid.js
cmp/grid/GridModel.js
data/Record.js
data/Store.js
data/cube/impl/QueryExecutor.js
data/impl/RecordSet.js
desktop/cmp/grid/columns/Actions.js

#737 
Support for showing a summary/total row in our Grid component pinned to the top or bottom (uses ag-Grid pinned row feature)
In order to use the summary row the application needs to include a row in the store with an id of "summary" which contains the data to display, and set the new `showSummary` prop on the GridModel. If the store contains hierarchical data, the "summary" record will be excluded from the main record hierarchy (it is stored separately in RecordSet). I went through several iterations on this implementation and landed on this as the best approach. In the future if we end up merging the Aggregation support in Cube/CubeRecord over to Store/Record the interface for the summary support shouldn't need to change and would be able to handle summary record without needing the …

Grid Summary Row

---

mobile/cmp/panel/Panel.js

Mobile Panel uses the mobile mask, to avoid inadvertently bringing in components from the desktop framework.

Mobile Panel uses mobile mask.

---

admin/tabs/logging/viewer/LogDisplayModel.js

Fixes issue #1166: replace `this.startLine` with `parent.startLine` +
* It seems that the server returns an array that depends param `parent.startLine`, but then the client conditionally `.reverse()` the response.  Maybe we can consider removing the work from the client and instead having the server return the array in appropriate order to begin with?   (Yana is unsure whether there are other pieces that depend on that endpoint returning the way it currently does)

tailMode bug fix

---

cmp/ag-grid/AgGrid.scss

ag-grid explicitly sets the overflow to either `scroll` or `hidden` on the floating top and bottom containers based on whether the center viewport has overflow in order to keep the space taken by the scrollbar consistent in all containers. 
https://github.com/ag-grid/ag-grid/blob/fe50182e5542b4616d2ef41a03a38836a83daeae/packages/ag-grid-community/src/ts/gridPanel/gridPanel.ts#L884
I think this change is safe since we don't expect to see any scrollbars in the grid on mobile, so ag-grid forcing them on actually makes the containers unbalanced.
Note that this issue does not appear be happen on an actual mobile device.

On mobile, force overflow hidden on the floating top and bottom containers (Fixes #1179)

---

data/Record.js
data/Store.js
data/impl/RecordSet.js
utils/js/LangUtils.js

Fixes #1193 and #1194 (found while testing these changes)
Modified logic in RecordSet.updateData to properly handle hierarchical data, per proposals in #1193, and added `addData` method to Store and RecordSet

Handle updating hierarchical data in Store

---

desktop/cmp/input/ButtonGroupInput.js

Handle case where the child Buttons could be null.
Searched through all references to `children` in the codebase, didn't see any other places where we are doing anything other than passing the children through to another component, or similarly null-safe operations.
Fixes #1208

Make sure button child is not null before accessing its props (Fixes #1208)

---

CHANGELOG.md
desktop/cmp/input/DateInput.js
kit/blueprint/styles.scss

Allows adding a clear button consistent with TextInput and Select, as well as allowing setting the `rightElement` if the app doesn't want any of the built-in buttons.

Support for enableClear and rightElement props on DateInput (Fixes #1213)

---

CHANGELOG.md
mobile/appcontainer/AppContainer.js
mobile/cmp/header/AppBar.js

+ Add app icon to left of title. Tapping it returns to home. See Toolbox PR: https://github.com/exhi/toolbox/pull/216
Fixes issue #1207

Move mobile app menu to right

---

CHANGELOG.md
format/FormatNumber.js

Matches Excel behavior
+This will be a breaking change (and clean up to exportValue:  v => v/100 in appropriate cols) in client apps using it; should be added to changelog as such after merge

Percent formatter (and renderer) will multiply value by 100*,  Fixes: #1192

---

desktop/cmp/input/DateInput.js

Fixes Issue #1240
* Up to date with develop branch?
* Ready for review?
* CHANGELOG entry?
* Breaking change?
* Docs updated?
* Mobile support?
* Toolbox branch / PR?

Don't close DateInput popover when changing dates with time precision

---

CHANGELOG.md
core/mixins/LoadSupport.js

+ This appears to be a common mistake, typically made by binding loadAsync directly to a reaction - it's then passed whatever is being tracked.
+ Won't catch cases where tracked observable is a plain object and is unintentionally passed in, but this seemed better than nothing.

Warn if param passed to loadAsync that does not appear to be a loadSpec

---

CHANGELOG.md
cmp/grid/Grid.js
data/RecordAction.js

New prop in RecordAction for secondary text/label. 
The only usage of RecordAction where it makes sense to use this is in the grid context menu, where it is mapped to the `shortcut` prop in the ag-Grid menu item. Other usages of RecordActions are in buttons where an additional label doesn't really make sense (we already have tooltip support via RecordAction).

Support secondaryText prop on RecordAction (Fixes #1276)

---

CHANGELOG.md
admin/tabs/general/websocket/WebSocketModel.js
core/XH.js
core/appcontainer/MessageModel.js
core/appcontainer/MessageSourceModel.js
desktop/appcontainer/ExceptionDialog.js
desktop/appcontainer/IdleDialog.js
desktop/appcontainer/Message.js
desktop/cmp/button/Button.js
desktop/cmp/button/Button.scss
kit/blueprint/index.js
mobile/appcontainer/Message.js
styles/vars.scss

This is a non-breaking change that some users would like in a hurry.  Would be good if it could be added to framework in feature release 25.3
This change allows autofocus on any button.
In message, alert, and prompt dialogs, autofocus can put on the input, cancel, or confirm components.
This change also affects the outline that appears on non-input focused components - ie: buttons.  The outline is thinner and not offset as much.

Allow autoFocus of button, and of input, cancel, or primary button in messages and prompts. (#1284)

---

CHANGELOG.md
desktop/cmp/input/Select.js

This fixes an issue I found in the Select component on desktop:  When a Select component has enableCreate = true, the selectOnFocus logic was not finding the correct class from which to get the inputRef.   With this fix, the inputRef is found whether or not enableCreate = true.
I'll add a change log entry once we decide whether to put this in release 26 or in release 25.2.1 …

add logic to find inputRef when Select has enableCreate  = true.

---

.github/pull_request_template.md
CHANGELOG.md
cmp/ag-grid/AgGridModel.js
cmp/grid/Grid.js
data/Record.js
data/Store.js

Restores support for application usage of the ag-Grid pinned data apis and fixes potential issuers where an application might want to …

Grid summary/pinned data fixes (Fixes #1289, #1290)

---

mobile/cmp/navigator/NavigatorModel.js

Workaround for Onsen issue with duplicate pages while resetting the page stack.

Fix Onsen navigator issues.

---

CHANGELOG.md
desktop/cmp/input/ButtonGroupInput.js

Make Buttons in ButtonGroupInput individually disable-able, Fixes #1348

---

admin/AppModel.js
admin/tabs/activity/ActivityTab.js
icon/Icon.js
svc/TrackService.js

+ Standardize on `message` as documented config for main string message, still support msg as alias. Make no-op if message not provided.
+ Restore broken support for string form (`XH.track('Hello')`) shortcut, as documented.
+ Default severity to "INFO" vs. non-standard seeming "OK". Will update hoist-core default to match as well.
+ Prepend track console logs with [Track] to differentiate them, match other [XH] logs, etc.
+ Fixup incorrect doc comments on service
+ Tweaks to admin interface - column swap, icons
- …

Smaller cleanups to TrackService

---

core/HoistComponentFunctional.js

Encountered this while trying to have a component use a model from context, or create one if not found. The model lookup logic would not create in the case where it was not found on context, it would return `undefined` for the model.
- [N/A] Reviewed for breaking changes (add `breaking-change` label + CHANGELOG if so, or N/A)
> **Pull request reviewers:** …

Fix for model lookup logic when not found on context

---

CHANGELOG.md
desktop/cmp/input/DateInput.js

+ New `strictInputParsing` prop (default false) to enforce strict parsing of text input by moment
+ Inputted values exceeding max/min date reset to null, instead of being coerced to the boundary date.
+ Expanded doc strings on min/max constraints.
+ Fixes #1396  …

Stricter desktop DateInput handling

---

svc/FetchService.js

When reviewing our fetchservice code as part of looking into #307, I noticed that the CORS setting did not match what the …

Correct setting of cors property on fetch.

---

CHANGELOG.md
cmp/grid/Grid.scss
cmp/grid/columns/Column.js
cmp/grid/columns/ColumnGroup.js
svc/GridExportService.js

+ Fix issue where chooserName would be a stringified function if headerName was a function (and no chooserName specified)
+ Add support for align on ColumnGroup
+ Add changelog note about new dom/css structure for column group headers …

Column/ColumnGroup fixes/enhancement

---

package.json
svc/FetchService.js
yarn.lock

As per https://httpstatuses.com/205   205 should also return null when using fetchJson.

Handle status 205 correctly in fetchJson

---

core/XH.js

+ Specify that `message` config itself can be any `ReactNode`
+ Note - will update dev-utils to import @types/react as a transitive dev dependency - that should cause IDEs to properly recognize `ReactNode` as a type if they don't already.
+ Fixes #1405 …

Better docs for XH.message() + variants w/typedef

---

package.json
yarn.lock

+ We could add these libs to dev-utils if we think we will use them consistently, although they would need to be enabled within each app / project as we see here.
+ Add .jsx extension to our on-demand `yarn lint` command for completeness / as a template for apps that might have JSX files.
- [NA] Added CHANGELOG entry (or N/A)
- [NA] Reviewed for breaking changes (add `breaking-change` label + CHANGELOG if so, or N/A)
- [NA] Updated doc comments / prop-types (or N/A)
- [NA] Created Toolbox branch / PR (link …

Use lint-staged + husky to lint changes prior to git commit

---

CHANGELOG.md
cmp/input/HoistInput.js
desktop/cmp/input/JsonInput.js
desktop/cmp/input/RadioInput.js
desktop/cmp/input/Select.js
mobile/cmp/input/Select.js

Small change to pass the `context` through to `super` in the constructors for our HoistInput components which have constructors. 
See https://github.com/facebook/react/issues/13944
The issue was only occurring for JsonInput, since the other components were not referencing their `model` in the constructor, but seemed safest to add everywhere.
In general any HoistComponent which has `supportModelFromContext = true` and has a constructor should be doing this. Not sure how/if we should communicate that in the changelog?
- [N/A] Updated doc comments / …

Json input context model fix (Fixes #1456)

---

desktop/cmp/input/DateInput.js
desktop/cmp/input/TextInput.js

TextInput can have a right element. If this right element is focused,
the event will bubble up to the parent TextInput. This would cause the
event handler defined in TextInput to try to call select on the rightElement,
which did not work. Now the TextInput will only try to select on focus if
the event targeted the input rather than the right element.
Adding selectOnFocus to the DateInput was trivial.
We just pass selectOnFocus to the child TextInput.
> collapse …

Correct bug in textInput and add selectOnFocus to dateInput

---

CHANGELOG.md
desktop/cmp/treemap/TreeMapModel.js

--------------------
Fix for #1471 
Small change to fire …

Initialize TreeMap data immediately on model construction (Fixes #1471)

---

CHANGELOG.md
cmp/grid/columns/Column.js
svc/GridExportService.js

The export system should now handle dynamic header names. The export system will save the headerName as it appears at export.
We issue a warning when creating a column with dynamic headers and no exportName specified, since exporting dynamic header names is probably a mistake most of the time.
https://github.com/xh/toolbox/pull/306 …

Make exportName use dynamic headerName

---

mobile/cmp/input/ButtonGroupInput.js

Fixes #1486
Also add `enableClear` prop to mobile ButtonGroupInput, and generally brings it inline with the desktop version.

Allow buttons in mobile ButtonGroupInput to be individually disabled

---

CHANGELOG.md
cmp/grid/impl/ColumnHeader.js

Fix for #1520 
Decided to just fix this specific issue introduced with the recent dynamic header name support, there are other issues with auto-group column support in our ColumnHeader component which are non-trivial to address (see #1521)
> change. This …

Handle undefined xhColumn reference in ColumnHeader (Fixes #1520)

---

desktop/cmp/dash/DashContainer.js
desktop/cmp/dash/DashContainerModel.js
desktop/cmp/dash/DashViewSpec.js
desktop/cmp/dash/impl/DashContainerUtils.js
desktop/cmp/dash/impl/DashTabModel.js
kit/golden-layout/styles.scss

Tweaks to how DashContainer interprets sizes specified in state:
+ You can specify sizes on views directly, without having to wrap it in a sized stack. This is default GoldenLayout behaviour that was lost in our implementation.
+ You can specify sizes in pixels. We use the dimensions of containers to convert this into a relative size at the moment the state is applied. …

DashContainer sizing improvements

---

kit/blueprint/styles.scss
kit/onsen/styles.scss
styles/XH.scss

Use `--xh-input-placeholder-text-color` for input placeholders consistently across light / dark theme & desktop / mobile. Fixes #1516 …

Placeholder text color

---

CHANGELOG.md
cmp/dock/DockViewModel.js
desktop/cmp/dash/DashViewSpec.js
desktop/cmp/dash/impl/DashView.js
desktop/cmp/dock/impl/DockView.js
desktop/cmp/tab/impl/Tab.js
mobile/cmp/tab/impl/Tab.js
utils/react/ReactUtils.js

+ Make content arg consistent across tab/dock/dash containers
+ Apply additional props consistently regardless of how content specified
+ DRY for all implementations
Fixes: https://github.com/xh/hoist-react/issues/1537
Toolbox PR:  https://github.com/xh/toolbox/pull/325
> …

Tighten/Clean-up handling of 'content' param in containers

---

desktop/cmp/input/Select.js

Small change to make sure we log any exceptions in the Select `queryFn` or while processing the options - was at a loss as to why my select wasn't working, turned out I needed to add the `valueField` and `labelField` props, but the exception we throw was being swallowed by higher level code.
- [N/A] Reviewed and …

Don't swallow exceptions thrown by async Select option processing

---

desktop/cmp/dash/DashContainerModel.js
kit/golden-layout/styles.scss

This was trickier than anticipated to get working without totally breaking GoldenLayout!
Note: GoldenLayout automatically drops out tabs when the container shrinks. To get the undesirable overflow behaviour that prompted this ticket, you need just one tab whose title is wider than its container.
Before:
After:
Also includes styling tweaks to the title input to better suit dark mode
button below to indicate it is not ready yet for a …

Fix overflow for dash container titles

---

CHANGELOG.md
cmp/ag-grid/AgGrid.js
cmp/grid/Grid.js

+ Define ag-grid row height defaults in static objects off of the `AgGrid` component, making it easier for apps to override globally if required.
+ Fixes #1465 …

Allow (app-wide) override of ag-Grid row heights

---

desktop/cmp/dash/DashContainerModel.js
desktop/cmp/dash/impl/DashContainerUtils.js
kit/golden-layout/styles.scss

If you remove all views from a DashContainer, you end up with a completely empty view. This means that users are then unable to rebuild their dash, since the add button is in the stack header.
This change ensures that an empty DashContainer always has an empty stack.
> …

Support empty DashContainer state

---

desktop/cmp/dash/DashContainerModel.js

Split visual aspects of state reaction from publishing the state, allowing a more generous debounce without visual artifacts
> change. This helps keep the commit log clean and easy …

Make DashContainer state publishing less chatty

---

CHANGELOG.md
appcontainer/OptionsDialogModel.js
core/HoistAppModel.js
desktop/cmp/button/RestoreDefaultsButton.js

Noticed a couple things while setting up app options for a client app:
* We did not have support for an `omit` prop, which is cleaner than using if statements to build the options based on user roles
* The title and message were swapped for the RestoreDefauiltsButton confirm dialog
button below to …

App options enhancement/fix

---

CHANGELOG.md
cmp/ag-grid/AgGrid.js
cmp/ag-grid/AgGrid.scss
cmp/ag-grid/AgGridModel.js
cmp/grid/Grid.js
cmp/grid/GridModel.js
desktop/cmp/grid/columns/Actions.scss
styles/vars.scss

Fixes #1609 
Fixes #1433 
Adds support for a new `sizingMode` config on `GridModel` (really `AgGridModel`) which can be set to 'large', 'standard', 'compact', or 'tiny'. I did this is a non-breaking way to preserve support for the `compact` config which is likely used heavily. It is a very easy breaking change to handle with a mass rename, but need this merged ASAP so not sure we want to include a breaking change in a minor release ...
The 'standard' and 'compact' modes should look the same as before this change, aside from slightly shorter headers for compact mode.
This change also exposes the ability for apps to customize the grid header height for each of these modes via new `AgGrid.HEADER_HEIGHTS` property.
This is also setup in such a way that an app could provide any value they want …

Add support for multiple Grid sizing modes

---

desktop/cmp/dash/impl/DashContainerUtils.js

Workaround for GoldenLayout's activeItemIndex out of bounds issue.

---

CHANGELOG.md
mobile/cmp/navigator/Navigator.js

Prop to choose or turn off navigator animations.

---

CHANGELOG.md
icon/Icon.js

Anselm fixed bug in fontAwesomeIcon elem factory function to include 'fa-fw' as default className. Previously was overridden by additional classNames passed into props.
> change. …

Icons now have fa-fw className applied

---

data/Store.js

Encountered this case in a client-app, don't see any reason why we are throwing in this case. …

Allow empty root summary data

---

desktop/cmp/input/Select.scss

Fixes #1676
Note that this fix just buys us a few extra pixels of wriggle room before it starts scrolling. If the dev opts to use font-sizes that are larger than the toolbar height, the scrollbars will reappear. …

Fix scrollbar in toolbar multi-select when using custom fonts.

---

CHANGELOG.md
cmp/store/impl/StoreFilterFieldImplModel.js

+ Remove falsey check on `fieldVal` before passing to regex - regex happily returns false when fed null/undefined (and would allow match on ID or other field val of 0).
+ Fixes #1697 …

StoreFilterField matches on `Record.id`

---

desktop/cmp/input/Select.js
desktop/cmp/input/Select.scss

This change reduces the dropdown width from 31px > 20px. The idea was to make it look consistent with our other right-align input actions, like clear.
vs. current prod:
Don't know if there's too much more we can actually do here. See issue: #1717 …

Make dropdown indicator in Select a bit less bulky.

---

desktop/cmp/input/NumberInput.js
mobile/cmp/input/NumberInput.js

+ Appends a given string to the rendered value within the control, leveraging existing use of fmtNumber(). …

Add numberInput.valueLabel prop

---

CHANGELOG.md
cmp/ag-grid/AgGrid.scss

This new CSS reduces the size of the checkboxes used here:
https://toolbox-dev.xh.io/app/grids/treeWithCheckBox
when in Tiny mode, so that they fit correctly within the Grid's row.
Before:
After: …

CSS for checkboxes in Grid Tiny mode

---

cmp/form/FormModel.js

+ Returns `FieldModel[]` - convenient and jsdoc typed way to get a reference to all owned FieldModels.
+ Useful on its own in a case I have, but might also help to clarify that `FormModel.fields` is an object (despite ctor taking them as an []), simply by providing a contrasting public getter.
> **Pull request reviewers:** when merging this P/R, please consider using a …

Add FormModel.allFields getter

---

desktop/cmp/rest/impl/RestFormModel.js

The behavior on adding a new user preference is still less than ideal -- you still don't get the right editor.
This PR just fixes the console error that we started getting on new records, due to the change to our Record API
+ Also please note some unrelated cleanups to RestFormModel
> **Pull request reviewers:** when merging this P/R, please consider using a *squash …

Squelch Error on adding new user preference.

---

cmp/grid/GridModel.js

+ I always look for this core method on GridModel.
+ Especially given that we support `selectFirst()` - which I know is grid-specific as grid determines sort - and a few other selection-related shortcuts. …

Add GridModel.select() convenience method

---

desktop/cmp/mask/Mask.js

We have a client app that uses an element for a mask message. PropTypes logs an error without this change. …

Document Mask support elements for message

---

CHANGELOG.md
cmp/grid/GridModel.js
cmp/store/impl/StoreFilterFieldImplModel.js

+ Also, add `GridModel.getVisibleLeafColumns()` - have seen this done in a few places.
+ Remove special handling for record.id now that id is included in data object.
> change. This …

StoreFilterField supports dotSeparated col fields

---

icon/Icon.js

+ Returns empty div with fa-fw className applied, as well as any optional FA sizing class.
+ Used to take up space where an icon would be - e.g. when aligning menuItems with/without icons. …

Add Icon.placeholder()

---

CHANGELOG.md
cmp/ag-grid/AgGrid.scss
cmp/grid/Grid.scss
cmp/grid/columns/Column.js
styles/vars.scss

Gets to the root of #1878 by taking control of tree column left padding:
+ Use 'em' based `--xh-grid-tree-indent` var to account for different sizing modes
+ Use same `--xh-grid-tree-indent` var for both group indents and leaf indents
+ Use fixed width icon
> collapse …

Tree grid alignment fixes (v2)

---

cmp/grid/Grid.scss
cmp/grid/columns/Column.js
svc/GridAutosizeService.js

+ Don't depend on columns being rendered to size headers
+ Add option to always account for sort icon when sizing headers
See https://github.com/xh/hoist-react/issues/1888
> change. …

Col header autosize improvements

---

svc/GridAutosizeService.js
svc/impl/ColumnWidthCalculator.js

+ Ensure fill mode takes the latest pinned column width into account, not the rendered width.
+ Only reuse a TextNode if its the only child node. …

Autosize fixes

---

CHANGELOG.md
desktop/hooks/UseContextMenu.js

+ contextMenu property of null should consume event quietly
+ minor efficiency fix for consumed context menu events.
+ poorly formed contextMenus should also consume quietly
Please see also the following commit on develop -- this handles the [] case:
https://github.com/xh/hoist-react/commit/cc4dbb62f8f15f7eaf7efdf810cdb8377343099c …

Context Menu fixes

---

CHANGELOG.md
data/Store.js
data/StoreFilter.js

+ Simple shortcut to `setFilter(null)`.
+ Automatically null Store's xhFilterText field if setting filter to null. While this store may be linked to StoreFilterFields that bind to an alternate source for their value, in default use cases (where SFFs stash their text state in Store) this should yield the least surprising results.
+ Move new `recordIsFiltered()` function closer to other filter-related APIs.
+ Add changelog noting both new methods.
+ Callback typedef for `StoreFilterFunction`.
**If your change is still a WIP**, …

Add Store.clearFilter()

---

desktop/cmp/panel/impl/dragger/Dragger.js
desktop/cmp/panel/impl/dragger/DraggerModel.js

Note that in order to preventDefault, events listeners must be added to the element directly using a ref (React events are `passive: true`) …

Use `preventDefault()` in panel dragger event listeners to prevent overscroll on tablets

---

cmp/ag-grid/AgGrid.scss

Not sure when it changed, but the context menu is rendered in its own portal, breaking the z-index fix added here https://github.com/xh/hoist-react/pull/1840 (which expects it to also have the `xh-ag-grid` class)
Fixes #1944. …

Fix ag-grid popup zindex style.

---

desktop/cmp/input/Select.js

I can't understand why we didn't have this in the first place.  If you ever want to usefully use object values in a select with binding, or even just controlling them with an external value, you really need it.  Its also consistent with the isEqual that we use in the superclass (HoistInput)  for value comparison.
> **Pull request reviewers:** when merging this P/R, …

Improve Bindability of Select with Objects

---

kit/golden-layout/index.js

Patch GoldenLayout's DragListener to improve support for touchmove events.
> single …

Fix GoldenLayout touchmove events

---

cmp/grid/Grid.scss
cmp/grid/impl/ColumnHeader.js

+ Apply left-margin to autosize header's icon placeholders, to match updated grid header styling
Fixes #1983 …

Only render sort icon in header if we have a valid, non-null sort.

---

svc/GridExportService.js

This changes includes store summary rows to the excel export. They are added as a root-level tree row in the export:
Note that due to limitations in how excel grouping works, the summary row will aways be shown at the top of the export (even if `GridModel.showSummary = 'bottom'`
Closes https://github.com/xh/hoist-react/issues/1985 …

Include store summary row in Excel export.

---

CHANGELOG.md
core/ExceptionHandler.js
svc/PrefService.js

+ Don't post exceptions related to unloading process
+ Fix unrelated problem with preferences not being pushed before page unload
See Don's example here: 
https://github.com/xh/toolbox/tree/navAwayError …

Improvements to behavior at document unload time

---

CHANGELOG.md
svc/GridExportService.js

+ Note that for consistency, changing the semantics such that we always return explicitly enumerated columns
from columns, via array or function.
+ This also fixes an important bug in the sorting of ExportOptions that was recently introduced and has not yet been released
> …

Allow columns property on ExportOptions to take a function

---

CHANGELOG.md
data/Store.js

This fixes this issue: https://github.com/xh/hoist-react/issues/2017
> single …

Fixes "Calling gridModel.clear() does not clear summary row content"

---

appcontainer/login/LoginPanelModel.js
desktop/appcontainer/LoginPanel.js
mobile/appcontainer/LoginPanel.js

+ Debounce LoginPanelModel.submitAsync (I think this is the real fix) and also disable / modify login button text to indicate login in progress.
+ Await XH.completeInitAsync() to avoid taking down login panel mask before the app has re-rendered with its primary interface.
+ Should avoid the rare-but-persistent double init exception (manifests as an exception re. re-init of IdentityService).
button below to indicate it is not ready …

Defend against accidental double-submit of login

---

CHANGELOG.md
cmp/grid/columns/Column.js
cmp/grid/impl/ColumnHeader.js

This resolves: https://github.com/xh/hoist-react/issues/2027
This PR brings in a small code change to automatically show the full headerName value in a browser "title" attribute tooltip if the headerName is elided in a Grid column header.
If the column width is expanded enough so that the headerName is no longer elided, the title tip no longer shows.
This logic does not run if the developer has already specified a `headerTooltip` on the column.
This PR also fixes a minor bug: prior, if a developer had specified a tooltipElement and a headerTooltip on the same column, mousing over the column header triggered a JS error.
This PR fixes this by passing the headerTooltip as the value to the tooltipElement when mousing over header.
See agGrid docs …

Elided header tooltip + bonus bugfix!

---

CHANGELOG.md
cmp/dimensionchooser/DimensionChooserModel.js
cmp/filter/impl/FilterChooserFieldSpec.js
cmp/form/field/BaseFieldModel.js
cmp/grid/GridModel.js
cmp/grid/columns/Column.js
cmp/grid/columns/ColumnGroup.js
data/Field.js
data/cube/CubeField.js
desktop/cmp/filter/FilterChooser.js

+ New config `Column.displayName` as general-purpose entry-point for the user-facing name of a Column.
+ Sourced via GridModel pre-processing from the `displayName` property of a linked store `Field` or config, if available, allowing further DRYing up of field metadata.
+ Also default columns bound to numeric field types to right alignment if not otherwise specified.
+ Add utility `genDisplayName()` function and use consistently in place of multiple independent calls to `startCase`.
+ Doc tweaks and auto-formatting.
**If your …

Support for Column.displayName + defaulting

---

data/filter/FieldFilter.js

+ Comparison operators [<,<=,>,>=] always return false for null and undefined values, favoring the behavior of Excel over Javascript's implicit conversion of nullish values to 0.
> …

FieldFilter comparisons exclude null vals

---

CHANGELOG.md
core/HoistComponentClass.js
desktop/hooks/UseContextMenu.js

in the UseContextMenu hook, if contextMenu is a function, the function will now be run every time onContextMenu is called.
Prior to this change, the contextMenu arg was overwritten by its own output, and so only run the first time. …

Fix for #2048 - contextMenu function only run on first call

---

CHANGELOG.md
admin/tabs/monitor/MonitorResultsDisplay.js
admin/tabs/monitor/MonitorResultsModel.js
admin/tabs/monitor/MonitorResultsPanel.js
admin/tabs/monitor/MonitorResultsToolbar.js

This PR and [Hoist-Core PR](https://github.com/xh/hoist-core/pull/163) addresses Issue #2050 to provide a mask+message for the monitor status tab when monitors are either undefined or disabled.
button below to indicate it is not ready …

Monitor status tab is masked when monitors are undefined or disabled

---

cmp/grid/Grid.scss
cmp/grid/columns/Column.js

Column.tooltipValueGetter must *always* returns a value - if it returns a nil value, the tooltip won't be shown, even if there is a value later. See issue https://github.com/xh/hoist-react/issues/2058 for more details. To work around this, a placeholder is returned instead of a nil value.
Column always uses tooltipComponentFramework. This allows us to handle the placeholder values set by tooltipValueGetter.
+ Provide minimal default styling for tooltip component.
**If your change is still a WIP**, please use the "Create draft …

Grid tooltip issues

---

CHANGELOG.md
desktop/cmp/input/Select.js

You can see this bug in https://toolbox-dev.xh.io/admin/tests/select on the enableWindowed test. …

Fix for issue #2008: Select prop selectOnFocus not working when enabledWindowed is true

---

svc/JsonBlobService.js

+ JsonBlobService.listAsync() accepts `includeValue` argument.
+ Parse values in the client service before handing them off.
See corresponding hoist-core PR: https://github.com/xh/hoist-core/pull/167
> collapse multiple intermediate commits into a single commit representing …

JsonBlobService tweaks

---

CHANGELOG.md
desktop/cmp/input/Select.js

This fixes the case when a queryFn is used and allowCreate is true. …

selectOnFocus fix: Use while loop to traverse down to comp with inputRef

---

desktop/appcontainer/AppContainer.js
mobile/appcontainer/AppContainer.js

+ Render modal component helpers at top-level of DOM to support use of XH messages and toasts prior to authorization complete (specifically, support use from within `preAuthInitAsync()`). …

Support XH messages/toasts pre-auth

---

CHANGELOG.md
core/index.js
core/mixins/PersistSupport.js
core/persist/CustomProvider.js
core/persist/ManualProvider.js
core/persist/PersistenceProvider.js

This turned out to be a bit of a nothing burger. :-)
Think we could call it ManualProvider or CustomProvider. 
We had thought about 'InMemoryProvider', but I think at this point this has gone in another direction -- it really requires the developer to write a bit of code and provide the implementation.
> **Pull request reviewers:** when merging this P/R, please consider …

Add ManualProvider class to Persistence API.

---

CHANGELOG.md
utils/datetime/LocalDate.js

This PR fixes bug reported in https://github.com/xh/hoist-react/issues/2098.
- Moment day getter returns 0 for Sunday (not 7).
> collapse …

Fix switch value for Sunday

---

CHANGELOG.md
desktop/cmp/input/Select.js

This change allows the checkmark on selected options to be shown when the select has this config:
```
enableMulti: true,
rsOptions: {
closeMenuOnSelect: false,
hideSelectedOptions: false
}
```

Select can now show a check mark by the selected items in multiMode & hideSelectedOptions: false

---

cmp/tab/TabContainerModel.js

Follow Chrome rules for tab removal:
1. Default to active tab
2. If active tab is removed, activate nextTab, or prevTab if !nextTab
- [N/R] Added CHANGELOG entry, or determined not required.
- [N/R] Reviewed and tested on Mobile, or determined not required.
> **Pull request reviewers:** when merging this …

Handle activating next best tab after tab removal

---

CHANGELOG.md
desktop/cmp/button/Button.js
desktop/cmp/button/Button.scss
styles/vars.scss

This change sets the new `xh-button--active` css class on a button with prop `active:true`.
The class only has rules in it for buttons with `intent:none`.  If an app needs another intent to show a permanent active state the app can customize for that need.
Minimal, Standard, and Outline button types with intent:none all can now show a permanent active state.
> **Pull …

Button set to active:true renders with active styling. (fixes #2129)

---

desktop/cmp/dash/impl/DashContainerContextMenu.js

Fixes issue with unclear/non-titled inline "Add"
One extra mouse gesture to do an add
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing …

Simplify Menu for adding widgets

---

CHANGELOG.md
desktop/cmp/dash/DashContainerModel.js
desktop/cmp/dash/impl/DashContainerContextMenu.js

This PR addresses https://github.com/xh/hoist-react/issues/2145
Toolbox gets 'Restore Dash Defaults' extra item in Toolbox PR https://github.com/xh/toolbox/pull/436
> change. This …

Add support for additional dash container context menu items 

---

utils/react/LayoutPropUtils.js

I noticed that `getLayoutProps()` was converting null dimensions to a pixel string, e.g. `height: "nullpx"`.
While it wasn't causing any display issues, I don't think this is the correct behaviour. …

Don't include nil dimensions in layout props

---

CHANGELOG.md
desktop/cmp/grid/columns/Actions.js
desktop/cmp/grid/columns/Actions.scss

Am not sure why the sass import broke, but it really seemed like an unnecessary complication in this case so opted to just hardcode the padding value in the js code, and added a comment so we remember to keep the 2 places we have that value in sync. …

Fix action col width calculation

---

desktop/cmp/filter/FilterChooser.js
desktop/cmp/input/Select.js
desktop/cmp/input/Select.scss

FilterChooser height improvements.
+ Select & FilterChooser support specified height
+ FilterChooser supports `maxMenuHeight` prop
See ticket: https://github.com/xh/hoist-react/issues/2043
See toolbox branch for example usages: https://github.com/xh/toolbox/tree/filterChooserHeight
> **Pull request reviewers:** when merging this P/R, please consider using a *squash …

FilterChooser height improvements

---

CHANGELOG.md
cmp/grid/GridModel.js

Restore defaulting of stripeRows to true for non-tree grids

---

desktop/cmp/dash/DashViewSpec.js
desktop/cmp/dash/impl/DashContainerContextMenu.js

+ Default DashViewSpec.title from id. #2166
+ Hide context menu rename option if DashContainerModel.renameLocked. #2167 …

DashContainer fixes

---

desktop/cmp/tab/TabSwitcher.js

+ Use stable position based on switcher orientation
+ Increase delay before showing …

TabSwitcher tooltips tweaks

---

admin/App.js
desktop/cmp/tab/TabSwitcher.js
kit/blueprint/styles.scss

See issue https://github.com/xh/hoist-react/issues/2195
Also, fix issue where close button shown in overflow menu even if tab can not be removed. …

Enable tab overflow in admin.

---

CHANGELOG.md
cmp/dock/DockViewModel.js
cmp/form/FormModel.js
core/XH.js
core/mixins/ManagedSupport.js

+ Remove nonsensical destroy of component in DockViewModel
+ Remove extraneous destroy() call in FormModel …

Fixes to @ManagedSupport to better handle array properties

---

mobile/cmp/button/ButtonGroup.js

When testing the recent input changes, I was surprised to notice that the mobile ButtonGroup (not ButtonGroupInput) was the last non-functional component. This PR addresses that, bringing it inline with the rest of the toolkit. …

Convert mobile ButtonGroup to functional component

---

CHANGELOG.md
cmp/input/HoistInputModel.js

This change preserves the status quo for refs returned from our HoistInputs, but hopefully provides a reasonable path forward as well for some enhanced imperative access around focus management. …

Return a ref to the HoistInputModel from HoistInputs

---

kit/golden-layout/index.js

Fix an issue with GoldenLayout not being able to create drop zones in the root component.
GoldenLayout's  code assumes that the root component is full screen (i.e. the origin is 0,0).
That means that if a dashboard is not positioned at or near 0,0 in the document, the left and top root drag areas do not work. It worked on the Toolbox home screen because the main navbar is 42px high, thus offering a thin 8px drop zone from the top edge of the screen.
**If your change is still a WIP**, please use the "Create draft pull request" …

GoldenLayout root drop zones.

---

cmp/grid/Grid.js

After upgrading to ag-grid v24.0, a warning appeared the console:
```
ag-Grid: since v24.0, grid properties groupRowInnerRenderer, groupRowInnerRendererFramework
and groupRowInnerRendererParams are no longer used.
```
This change fixes that warning. …

Fix `groupRowInnerRenderer` deprecation warning

---

cmp/filter/FilterChooserModel.js
cmp/grouping/GroupingChooserModel.js
desktop/cmp/filter/FilterChooser.js
desktop/cmp/filter/FilterChooser.scss
desktop/cmp/grouping/GroupingChooser.js
desktop/cmp/grouping/GroupingChooser.scss
kit/golden-layout/index.js
mobile/cmp/grouping/GroupingChooser.js
mobile/cmp/grouping/GroupingChooser.scss

+ Add `allowEmpty` config to support setting empty values.
+ `initialValue` and `initialFavorites` can be functions.
+ Removed problematic default sizing on GroupingChooser. By default, its size is set by its label content, and devs can use LayoutSupport to enforce min/max/fixed widths.
+ Tweak favorite star styling, to be consistent size and not orange.
+ Tweak max depth messaging.
button below to indicate it is not ready yet for a …

GroupingChooser tweaks

---

CHANGELOG.md
data/cube/View.js

This can often result in an undesired total row in a grid after clearing the grid data if you are processing the root row from the view as your summary record. Doesn't seem like there is any reason for us to have a root row with no children. …

Don't create a root row when there are no leaves

---

mobile/cmp/input/NumberInput.js

+ Use type='number' when entering values to bring up the numerical keyboard on device
+ Use type=text' when displaying to facilitate formatted values.
See issue https://github.com/xh/hoist-react/issues/2235 …

Mobile number input fixes.

---

cmp/relativetimestamp/RelativeTimestamp.js

+ Moment outputs e.g. "a minute" instead of "1 minute". This creates some awkwardness when the leading number comes and goes - "<1 minute" -> "a minute" -> "2 minutes".
> change. …

Tweak RelativeTimestamp formatting

---

CHANGELOG.md
cmp/grid/impl/ColumnWidthCalculator.js
cmp/store/impl/StoreFilterFieldImplModel.js
data/Store.js

UPDATE:  Using rendered value only for dates for now, for performance reasons.
This isn't perfect, and in some cases may not be exactly what you want -- but on balance I think it handles things better --
WYSYG
+ Most Importantly searching for Date strings now works as your would expect.
+ Ledger format numbers work better -- no need to use '-' when you see '('.
+ Performance sees reasonable - tested on 50k, 7 column grid.
One potential downside is that searching for numbers now requires you to type the comma.    This is also probably the most significant behavioral difference.  If we think that is a bug, we could handle numeric fields differently, but I would be inclined to have the search work consistently on the rendered string for all fields. …

Use approximate rendered value for StoreFilterField

---

CHANGELOG.md
cmp/grouping/GroupingChooserModel.js
desktop/cmp/grouping/GroupingChooser.js
desktop/cmp/grouping/GroupingChooser.scss
mobile/cmp/grouping/GroupingChooser.js

+ Auto-expand add dim select upon show.
+ Add text to toolbar buttons to make them easier click targets.
+ If add dim button clicked and only one dim remains to add, add it immediately instead of showing select.
+ Show remove dim button on row hover only, add danger intent for general consistency.
> **Pull request reviewers:** when merging this P/R, please consider …

GroupingChooser tweaks for usability

---

mobile/cmp/panel/Panel.js

The mobile toolkit was routinely logging the below warning, which I tracked down to the mobile Panel:
`Cannot create an observer component without "memo". Memo is built-in to MobX observable. Component will be memoized.`
> collapse multiple intermediate commits into a single …

Fix memoization warning in mobile toolkit

---

cmp/dataview/DataView.js

Do we know why DataView currently only supports `onRowDoubleClicked`?
It seems it should also support `onRowClicked`, unless there is a good reason not to, particularly for mobile emulation where `onRowDoubleClicked` doesn't fire. (https://github.com/xh/hoist-react/issues/1762)
> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* …

Support `onRowClicked` in Dataview

---

mobile/cmp/button/ExpandCollapseButton.js

+ Replace icons
+ Disable the button if the grid does not contain hierarchical data
Unfortunately, I couldn't find any FontAwesome icons that seemed analogous to the icons used by the Ext JS version. Opted to use our pre-existing expand / collapse icons instead, which I feel are still a significant improvement …

Tweaks to mobile ExpandCollapse button

---

desktop/cmp/input/DateInput.js

- [N/R] Added CHANGELOG entry, or determined not required.
- [N/R] Reviewed and tested on Mobile, or determined not required. …

Set default popoverBoundary to 'viewport' in DateInput

---

cmp/grid/Grid.scss

Resolves #2293 
+ Dry up .ag-row-group-indent selector
+ $i loops from 1-20 (only those indices are supported by ag-grid)
> **Pull request reviewers:** when merging this P/R, …

Increase specificity of group leaf indent override

---

cmp/filter/impl/QueryEngine.js
desktop/cmp/filter/FilterChooser.js

+ Continue to suggest matching values across all fields, even if query matches a single field.
+ Field names and (different) field values can overlap - previously once your input matched a single field name you would no longer get other, also valid value matches, making the behavior difficult to understand.
+ Pass `rsOptions.defaultOptions:false` vs `[]` to suppress weird display of empty suggest box when user has deleted all of their query.
**If your change is still a WIP**, please use the "Create draft pull request" option in …

Minor updates to FilterChooser suggestions

---

svc/AutoRefreshService.js

+ Tweak to prevent over-aggressive auto-refresh when app loading slow.
+ Fix regression -- app instantly auto-refreshes …

Auto-refresh tweaks

---

cmp/grid/GridModel.js
desktop/cmp/grid/impl/ColChooserModel.js
mobile/cmp/grid/impl/ColChooser.js
mobile/cmp/grid/impl/ColChooserModel.js

Adds `autosizeOnCommit` option to ColChooserModel (default false for desktop, true for mobile). It is useful on mobile to automatically autosize after adding new columns with ColChooserModel.
This PR also allow configuring the mobile ColChooserModel, offering a more consistent story across desktop and mobile. …

Column Chooser Autosize

---

desktop/cmp/treemap/SplitTreeMap.js
desktop/cmp/treemap/TreeMap.scss
desktop/cmp/treemap/TreeMapModel.js

Fixes https://github.com/xh/hoist-react/issues/2336
+ TreeMap's chart holder does not participate in flex box, allowing the outer flex to take precedence over internal chart size.
+ Compute TreeMapModel.total using store records rather than internal data …

Fix SplitTreeMap flex ratio.

---

CHANGELOG.md
utils/datetime/LocalDate.js

Hi,
This seems like a pretty simple new feature, unless I'm missing something about timezones.
It's pretty useful in an app I'm upgrading where I have to test if the date passed in from URL is the current day or not.
In my local env I added this test code to `toolbox/client-app/src/admin/tests/localDate/LocalDateTestModel.js`
but not sure we want to add this to toolbox.  I didn't see any other tests for the "is" getters.
```
{
category: 'compare',
title: 'LocalDate.today().isToday() === true',
input: 'LocalDate.today()',
expected: 'true',
testFn: () => {
return LocalDate.today().isToday;
}
},
{
category: 'compare',
title: 'LocalDate.get(20190601).isToday() === false',
input: '(20190601)',
expected: 'false',
testFn: () => {
return LocalDate.get('20190601').isToday;
}
}
```
Hoist P/R …

Added LocalDate.isToday getter

---

cmp/tab/TabContainerModel.js

If you remove the currently active tab, the active tab jumps to the first tab briefly before settling on the next / previous tab.
It wasn't causing any problems, but the behaviour didn't seem right and was causing bogus track statements from the TabContainerModel. Activating the desired tab *before* modifying the tabs fixes this. …

TabContainerModel adjusts the active tab before removing the tab

---

cmp/tab/TabContainerModel.js

Since `TabModel` supports titles that are elements, when tracking is enabled for `TabContainerModel`, we should fall back to tracking its id.
button below to indicate it is …

Track tab id if its title is an element

---

cmp/layout/TileFrame.js

Namely, right now it will re-render twice in many circumstances where it could render once.
Changes due to props can always be cleanly handled in the same render.  
Seems like hooks a more efficient tool for this, although would like to understand better if there is a clean way 
to do this with mobx.
Thought this might be important for tiling containers that may have complex children.
button below to indicate it is not ready yet for …

Make TileFrame more efficient

---

cmp/layout/Box.js
cmp/layout/TileFrame.js
core/elem.js
desktop/cmp/input/ButtonGroupInput.js
desktop/cmp/panel/Panel.js
desktop/cmp/toolbar/Toolbar.js
mobile/cmp/button/ButtonGroup.js
mobile/cmp/input/ButtonGroupInput.js
mobile/cmp/panel/DialogPanel.js
mobile/cmp/panel/Panel.js

-- Best Practice
-- More consistently skip non-renderable element children (null/undefined/false)
-- Avoid extra calls to toArray()/castArray
-- Omit null children from component logic in Toolbar/Tile
> collapse multiple intermediate commits into a single commit representing …

Use React.Children object over castArray

---

kit/blueprint/styles.scss

Resolves https://github.com/xh/hoist-react/issues/2299
It seems like this style rule was the culprit, and I could not find any case where removing it was problematic for any other bp3 icons or spinner.
- [N/A] Created Toolbox branch / PR, or …

Fix misaligned right icons within inputs

---

cmp/grid/columns/Column.js
svc/GridExportService.js

Pass context params (i.e. `{record, column, gridModel}`) to function form of exportValue, for greater symmetry with column renderers. …

Improve Column.exportValue() params

---

desktop/cmp/button/AppMenuButton.js
desktop/cmp/contextmenu/ContextMenu.js

Brings our AppMenu API in line with our other menu implementations.
+ Recursively parse AppMenu items to build submenus from configs. #2393
+ Don't automatically open submenus. #2394 …

Improve support for SubMenus in AppMenu

---

mobile/cmp/menu/impl/Menu.scss
mobile/cmp/popover/Popover.js

Menu will not clip the viewport, but will scroll if necessary. See issue #1862
> …

Constrain mobile menu height and position to viewport

---

CHANGELOG.md
exception/Stringify.js
utils/js/LangUtils.js

Precipitated by issues with LocalDate in params to server that were being serialized strangely.
At this point, we could honestly remove the method `trimToDepth` --- I am not sure it ever really made sense for it to be in our API.  I certainly didn't want to include these somewhat ad-hoc semantics into the public method.
> **Pull request reviewers:** when merging this …

Improvements to exception serialization to better handle `LocalDate`

---

desktop/cmp/grid/editors/InlineEditors.scss

Inline editors use fonts, font-sizes and padding consistent with the GridModel.sizingMode to provide more predictable switching between cell and editor. Ensures that columns sized to display their cells can also show the full input. …

Inline editor sizing modes

---

cmp/grid/Grid.js
cmp/grid/Grid.scss

See issue: #2425
Only removing the hide delay is necessary to resolve the issue, but I found that removing the show delay also helps reduce the ambiguity of a tooltip is going to show or not. …

Remove show and hide delays from grid tooltips

---

CHANGELOG.md
cmp/grid/Grid.js
cmp/grid/GridModel.js

Include a flag to hide GridModel empty text until after the Store has first been loaded.
See issue https://github.com/xh/hoist-react/issues/2438 …

GridModel's emptyText before load

---

desktop/cmp/treemap/SplitTreeMap.js
desktop/cmp/treemap/SplitTreeMap.scss
desktop/cmp/treemap/SplitTreeMapModel.js
desktop/cmp/treemap/TreeMap.js
desktop/cmp/treemap/TreeMapModel.js

Issue https://github.com/xh/hoist-react/issues/2442:
+ Refactor SplitTreeMap so that titles do no factor into flex weighting.
+ Ensure non-empty sides of a SplitTreeMap have a minimum size.
+ Rotate titles in a horizontal SplitTreeMap so that sides can be sized properly.
Issue https://github.com/xh/hoist-react/issues/2437:
+ Roll up TreeMapModel emptyText into SplitTreeMap.
Other cleanups:
+ Rename TreeMapModel.hasData > TreeMapModel.empty, to match GridModel
**If your change is still a WIP**, please use the "Create draft pull …

SplitTreeMap improvements

---

cmp/ag-grid/AgGridModel.js
cmp/grid/Grid.js
cmp/grid/columns/Column.js

Refresh row heights for auto height columns on data change.
See issue: https://github.com/xh/hoist-react/issues/2465
See toolbox PR: https://github.com/xh/toolbox/pull/485
> change. …

Refresh row height on data change when autoheight = true

---

cmp/layout/TileFrame.js

The ratio score should compare `height:width` as well as `width:height`
> single …

Fix ratio score to consider the inverted ratio

---

cmp/layout/TileFrame.js

Adjust TileFrame logic to avoid degenerate single column cases caused by width constraints, e.g.:
+ Don't invalidate layouts based on constraints, and remove "fallback layout" concept
+ Add weighted "Width Filling Score" to counter tendency to list tiles in single column
Note that this PR removes the `minTileRatio` and `maxTileRatio` constraints - I couldn't think of a way to adjust a layout to enforce these constraints (how to decide which dimension do you change? What is that then validates a size constraint? etc). If we can come up with a reasonable way to enforce them I'm happy to restore, but I think in most cases the width / height constraints should be sufficient.
See Toolbox PR: https://github.com/xh/toolbox/pull/491
**Pull request …

TileFrame V2

---

CHANGELOG.md
desktop/cmp/input/TextInput.js
mobile/cmp/input/TextInput.js

Default `autoComplete` to 'off' (Fixes #2484)

---

CHANGELOG.md
desktop/cmp/input/NumberInput.js

+ Fixes #2018 (console warning thrown in development mode re. "controlled value prop does not adhere to stepSize, min, and/or max constraints") …

Sync numberInput minStepSize to precision prop

---

data/cube/row/BaseRow.js

We need to Flow aggregation updates all the way to the root, even if there is no change at an intermediate level.
Colin and I discovered this problem in a client app where aggregates on certain dimensions always aggregated to *null* but dimensions above them could still compute aggregates.
Without the changes in this PR, the dimension with null aggregates prevent the update of all aggregates for dimensions above them in the tree.
- [] Added CHANGELOG entry, or determined not required.
**If your change is still a WIP**, please use …

Fix streaming update bug in Cube

---

CHANGELOG.md
cmp/grid/GridModel.js

+ Improves `GridModel` async selection methods to ensure they do not wait forever if grid does not mount.
+ Fixes #2507 …

Add GridModel.getIsReadyAsync()

---

CHANGELOG.md
exception/Exception.js
promise/Promise.js
svc/FetchService.js

+ Throws exceptions explicitly marked as timeouts via `isTimeout` flag (in addition to name).
+ Add the same `isTimeout` flag to `fetchTimeout` exceptions. …

Add Exception.timeout() util

---

CHANGELOG.md
cmp/grid/Grid.js

Fixes #2531 
Most straightforward way to handle this. An alternative could be to add a new reaction to only update the pinned row data when the summary position/data changes, but I don't think that is really necessary.
> collapse multiple intermediate commits into a single …

Update grid data when Store `summaryRecord` changes (fixes #2531)

---

cmp/ag-grid/impl/RowKeyNavSupport.js
cmp/grid/columns/Column.js

Fixes issues with expand/collapse key stroke would also scroll grid!
+ Install back-pointer to Hoist Column from Ag column
+ Never shift cell focus after doing key-based expand/collapse
+ More selectively do key-based expand/collapse when showing cell focus
> collapse …

Improve node expand/collapse via keyboard

---

CHANGELOG.md
appcontainer/ToastModel.js
appcontainer/ToastSourceModel.js
core/XH.js

* New XH convenience methods `successToast()`, `warningToast()`, and `dangerToast()` show toast alerts with matching intents and appropriate icons.
* Note that the default `XH.toast()` call now shows a toast with the primary (blue) intent and no icon. Previously toasts displayed by default with a success (green) intent and checkmark. …

Changes to Toast defaults, new XH methods

---

CHANGELOG.md
cmp/ag-grid/AgGrid.scss
cmp/dataview/DataView.scss
format/FormatNumber.js
styles/XH.scss
styles/vars.scss

* Lighten red and green color values in dark mode for improved legibility.
* Use new dedicated CSS classes and variables for fmtNumber colorSpec defaults.
* Better named / dedicated CSS vars for styling selected grid rows. …

Update red/green styles, tweak grid sel. CSS vars

---

cmp/grid/columns/Column.js
core/elem.js
utils/react/ReactUtils.js

In the interest of keeping things moving, this PR works around, for the column editor use case only, the fact that elementFromContent does not execute the content function with its arguments. …

works around elementFromContent not calling the content function with its arguments

---

CHANGELOG.md
cmp/grid/Grid.scss
cmp/grid/columns/Column.js

+ New `.xh-cell--editable` applied, but with no default styling provided by Hoist.
+ Changed previous `.xh-invalid-cell` to `.xh-cell--invalid` for consistency.
+ Fixes #2553
> …

Apply CSS class to inline-editable grid cells

---

CHANGELOG.md
admin/tabs/activity/tracking/charts/ChartsModel.js
cmp/filter/FilterChooserModel.js
cmp/form/field/BaseFieldModel.js
cmp/grid/Grid.js
cmp/grid/GridModel.js
core/HoistBaseDecorators.js
desktop/cmp/contextmenu/ContextMenu.js
desktop/cmp/dash/DashContainerModel.js
desktop/cmp/grid/editors/impl/InlineEditorModel.js
desktop/cmp/input/DateInput.js
desktop/cmp/input/NumberInput.js
desktop/cmp/input/Select.js
desktop/cmp/panel/PanelModel.js
desktop/cmp/treemap/TreeMap.js
mobile/cmp/input/NumberInput.js
promise/Promise.js

+ deprecate start(), add default interval to wait().
+ standardize usages to wait().then()
Got tired of looking at wait(1), wait(0) and start().  Start seems especially weird, poorly named, and unecessary.
Wait does the same thing, and is more expressive. …

Standardize coding of async delays

---

CHANGELOG.md
cmp/ag-grid/AgGridModel.js
cmp/grid/Grid.js
cmp/grid/GridModel.js
cmp/grid/columns/Column.js

+ Add as top-level configs to GridModel and Column, respectively.
+ Throw if detected within agOptions to ensure migration.
+ Remove obsolete `GridModel.compact` config - deprecated in v29.
+ Fixes #1331  …

Support rowClassRules/cellClassRules configs

---

CHANGELOG.md
admin/tabs/activity/clienterrors/ClientErrorDetail.js
admin/tabs/activity/tracking/detail/ActivityDetailView.js
cmp/form/Form.js
desktop/cmp/form/FormField.js
mobile/cmp/form/FormField.js
utils/react/Hooks.js

Closes #2444
See toolbox PR that cleans up label fieldDefault …

Form supports setting readonlyRenderer in fieldDefaults prop

---

data/filter/Utils.js

`parseFilter()` converts a raw function to a `FunctionFilter` with key 'default'.
> …

`parseFilter()` accepts raw functions

---

mobile/appcontainer/ExceptionDialogDetails.js

Improve sending a message from the mobile ExceptionDialogDetails by opening the message form in a dedicated dialog.
Fixes https://github.com/xh/hoist-react/issues/2451
> change. …

Improve mobile ExceptionDialogDetails

---

cmp/store/impl/StoreFilterFieldImplModel.js

StoreFilterField uses a LocalModel, meaning it's `xhId` is not stable if it is removed from the DOM and then re-added (as happens in the column filters popover). Use the stable 'default' key instead.
If devs want to combine other FunctionFilters with a StoreFilterField, they must either give the other FunctionFilters keys or use the existing `StoreFilterField.autoApply: false`  
button below to indicate it is not ready yet for a …

Use stable 'default' key for StoreFilterField.

---

CHANGELOG.md
cmp/grouping/GroupingChooserModel.js
desktop/cmp/grouping/GroupingChooser.js
mobile/cmp/grouping/GroupingChooser.js

Based on a discussion with ATM, decided to take a crack at this simplification we have been talking about for a while.   
I was originally the one against always showing the "Add..." control, but I actually think this is much better and has far fewer UI elements/state.  Sorry!
> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* …

Simplify grouping chooser

---

package.json
yarn.lock

Did a smoke test of the Toolbox mobile app and the newer version of core-js doesn't seem to be causing any issues with Onsen.
Issue: https://github.com/xh/hoist-react/issues/2621
> …

Force OnsenUI to use core-js v3.

---

CHANGELOG.md
cmp/grid/GridModel.js

This change is an alternative solution to the solutions one would likely consider for this _sortOrder issue: 
https://github.com/xh/hoist-react/issues/2631
The reason the _sortOrder setting was picked up in a client app is because the first change to trigger a diff check in the viewManager was a "non-change" of setting a column's hidden key to true when it is already true.
button below to indicate it is not ready yet for a final …

applyColumnStateChanges only if not equal

---

desktop/cmp/rest/impl/RestGridToolbar.js

+ Believe this is the best default for our current primary usages of RestGrid within the admin console.
+ If we get any feedback that this is disruptive to any app-level uses of the comp, we could make configurable, but I didn't see any obvious/simple path to doing so proactively.
> **Pull request reviewers:** when merging this P/R, please consider using a *squash …

RestGridToolbar storeFilterField matchMode -> any

---

desktop/cmp/treemap/TreeMap.js
desktop/cmp/treemap/TreeMap.scss

+ TreeMaps apply their own theme CSS class, since their theme can be decoupled from the global theme
Fixes: https://github.com/xh/hoist-react/issues/2644 …

TreeMaps use a light border in dark theme to improve legibility

---

cmp/grid/GridModel.js

Normally would avoid this kind of fiddly cleanup change, but `_sortId` it is a rather ugly artifact in a very core piece of configuration data for us.  Also, gets us a nice cleanup.
Main point is that our column state is always only leaves at this point, and we should not need this exotic sorting.  
Will be sure to have Don take a look -- have already run it by Tom and John Haynes
- [xX] Added CHANGELOG entry, or determined not required.
**If your change is still a WIP**, please use the "Create draft pull request" option in the …

Remove _sortId artifact on grid column state

---

cmp/grid/filter/GridFilterModel.js
cmp/store/impl/StoreFilterFieldImplModel.js
data/filter/Utils.js

The first part of this PR addresses https://github.com/xh/hoist-react/issues/2640. This is fixed by updating the `withFilterByXXX` util methods respect the original `AND|OR` operator when modifying a CompoundFilter. Previously they would only create `AND` CompoundFilters.
Fixing this revealed a further issue. If your root-level filter was an `OR` CompoundFilter, adding new filters with the `GridFilterModel` or `StoreFilterField` would add these to the `OR` filter, resulting in undesirable behaviour. This PR also addresses that, by wrapping in an `AND` before modifying. This is safe to do, since if no new filters are added or just the original filter is replaced, the single child `AND` filter is discarded by `parseFilter()`.
Note: To test creating a root-level OR filter, use the Custom …

OR CompoundFilter fixes

---

CHANGELOG.md
cmp/ag-grid/AgGrid.scss
styles/vars.scss

I was enthusiastically adding the app-wide Grid Sizing options in the Navbar App Menu for a client app, when I discovered that the Tiny, Compact, and Large sizes did not produce good group row sizes when the grid is using:
```
agOptions: {
groupUseEntireRow: false,
groupSuppressAutoColumn: true
}
```
which this client app uses A LOT.
This issue is reproducible in Toolbox in this branch: https://github.com/xh/toolbox/tree/groupUseEntireRow_false on the "Grouped Columns Grid", where I have set this agOptions config.
Here is a screenshot of the issue in toolbox: …

Setup grid cell sizes for groupUseEntireRow = false

---

cmp/dataview/DataViewModel.js

`rowClassRules` are usually preferred over the already documented `rowClassFn`, so seemed like a gap in the documentation …

Document rowClassRules in DataViewModel

---

cmp/grid/impl/ColumnWidthCalculator.js

CSS class names applied to grid cells can interfere with column autosizing. This was seen in a client app where row classes were used to bold the cells, making them wider.
This PR incorporates `GridModel.rowClassFn`, `GridModel.rowClassRules`, `Column.cellClassFn` and `Column.cellClassRules` into the autosizing calculations. Please note due to the (necessary) optimisation to only sample a subset of values, there are still some cases that may slip through the gaps (e.g. conditionally applying a cell class to make an otherwise narrow cell much wider). However, for simpler cases such as bold fonts and added padding this should prove sufficient.
See Toolbox branch which replicates the issue seen in the app: https://github.com/xh/toolbox/tree/autosizeClassNames
See issue: …

Autosize aims to respect class names applied to the row and cell

---

cmp/grid/Grid.scss
desktop/cmp/grid/impl/filter/ColumnHeaderFilter.scss

Resolves #1896
Adjust grid header margin values
+ Remove extra margins from icons and svgs in header - their fixed width already creates a sufficient margin between it and the header text. This is a nice win for header names that are only Icons - they center properly now.
+ Remove margin-top from grid header (this now aligns the text and sort/menu icons much better)
Apply hover color on column header filter icon
+ In line with hover color applied to the tree expand/collapse icon
+ Chose not to hover on sort icon, since clicking into the main body of the header accomplishes sorting as well... open to feedback (could apply hover color on sort icon when hovering over entire text as well)
Left ellipsis on overflow text as is. Clipping text has the unfortunate effect of looking like typos for …

Grid Header Tweaks

---

CHANGELOG.md
cmp/grid/Grid.js
desktop/cmp/grid/editors/DateEditor.js
desktop/cmp/input/DateInput.js

Fixes #2530
This seemed like the best approach to address this. It does have the caveat that a really short or thin grid may not have enough space to render the day picker, but that seems very unlikely to be the case in an application.
Alternative solutions would be to figure out how to kill focus on the day picker popover such that it does not trigger the `focusout` event on the grid viewports, but not sure if that is easy and/or possible.
Also could convert the date editor to a popup editor and render the day picker inside of the popup editor container instead of the grid viewport, which would address the caveat above but would mean the input component would not be rendered inside the cell and be inconsistent with other non-popup editors (and the implementation would likely be more …

Enable ag-grid prop `stopEditingWhenCellsLoseFocus` by default

---

desktop/cmp/grid/impl/filter/values/ValuesTabModel.js

A number of small but important column filtering fixes, worked out on a call with @pauldelano:
+ Ensure date > ms (and any future uniquification measures) are used for the grid idSpec in Values Tab
+ Use `[blank]` for both nil and empty string values, the same as the actual filter testFn
+ Only include `[blank]` if it's in the dataset …

Column filtering fixes

---

CHANGELOG.md
desktop/appcontainer/IdlePanel.scss
desktop/cmp/mask/Mask.scss
kit/blueprint/styles.scss
kit/onsen/styles.scss
kit/onsen/theme.scss
mobile/cmp/dialog/Dialog.scss
mobile/cmp/input/DateInput.scss
mobile/cmp/popover/Popover.scss
styles/vars.scss

+ Break apart vars for `--xh-mask-bg` (load masks) and `--xh-backdrop-bg` (modal dialogs).
+ Mask defaults now less obtrusive (less opaque and closer to app bg, based on theme), with style tweaks to ensure any text remains legible.
+ Backdrop now better controlled via CSS var, instead of unintentional double-masking we had previously due to leaking blueprint styles.
+ Popover CSS vars more clearly scoped to mobile, the only place they are applied.
+ Fixes #2690
**If your change is still a WIP**, please use the "Create draft pull …

Adjustments to default mask styles

---

cmp/grid/impl/ColumnWidthCalculator.js

The output from cellClassRules, rowClassRules, etc can sometimes be several CSS classnames joined as single space-delimited string. `Element.classList.add()` requires each class to be its own argument, and will emit a warning when providing a token with a space. This change rectifies by splitting and spreading any provided custom class names.
> **Pull request …

Fix warning from ColumnWidthCalculator

---

desktop/cmp/panel/impl/PanelHeader.scss
mobile/cmp/panel/Panel.scss
styles/vars.scss

Add distinct CSS vars for panel headers (similar to what we have for dialog headers), and use different defaults for mobile
> change. This helps keep the commit log clean and easy …

Restore mobile panel headers

---

CHANGELOG.md
svc/ChangelogService.js

Closes #2695 
Console warns 'Unable to mark changelog as read - latest version or required pref not found.' …

Do not save SNAPSHOT versions to xhLastReadChangelog preference

---

CHANGELOG.md
appcontainer/AppContainerModel.js
appcontainer/ViewportSizeModel.js
core/XH.js

Add observable viewport size and orientation getters. Primary motivation is allow an easier way for mobile / tablet apps to react to orientation changes. …

Viewport orientation

---

CHANGELOG.md
desktop/cmp/dash/DashContainer.scss
desktop/cmp/dash/DashContainerModel.js
desktop/cmp/dash/impl/DashContainerContextMenu.js
desktop/cmp/dash/impl/DashContainerMenuButton.js

Decided to not make this button specific to the add menu, but to just show the context menu in case there are extra menu items added by the app. I think this makes sense and provides the most flexibility.
Toolbox branch: https://github.com/xh/toolbox/tree/dashContainerAddButton
Fixes #2768 
> **Pull request reviewers:** when merging this P/R, please consider using a …

Add ability to show a menu button in dash container stack header

---

CHANGELOG.md
desktop/cmp/grid/editors/SelectEditor.js

Spent a while also trying to get `openMenuOnFocus` to work properly - but it introduces potential issues with tabbing through cells due to some react-select bugs re: setting focus correctly in the menu to the selected option. Decided that shouldn't block getting this simple and nice enhancement in.
> **Pull request reviewers:** when merging this P/R, please consider …

Stop editing immediately after selecting a value

---

CHANGELOG.md
cmp/grid/Grid.js
cmp/grid/GridAutosizeMode.js
cmp/grid/GridModel.js
cmp/grid/impl/GridPersistenceModel.js

An alternative PR to: https://github.com/xh/hoist-react/pull/2774
Implement MANAGED autosize mode, tracking which columns have been customized on a per column basis. It is more complex the previous PR, but I feel the complexity is worth it. …

Per column MANAGED autosize mode

---

desktop/cmp/panel/impl/dragger/DraggerModel.js
styles/XH.scss

May resolve #2457 
Temporarily set `pointer-events: none` on iframe elements to capture drag events correctly for panel resizing.
**If your change is still a WIP**, please use the …

Ensure mouse events are captured over iframes

---

desktop/cmp/dash/DashContainerModel.js
kit/golden-layout/index.js

Adds support for opening the DashContainer ContextMenu via long press on dash view header in Tablet.
Note that this PR categorizes touches as one of 3:
1) Tap, to change the selected tab
2) Long-press, to open the context menu
3) Very long-press, to initiate dragging the dash view. This state can be entered earlier by moving the finger during the long-press.
> **Pull …

Support "long press" to open DashContainer ContextMenu on Tablet

---

CHANGELOG.md
cmp/chart/Chart.js

Simple mitigation strategy for the issue described in #2803.
If a chart in fullscreen mode re-renders for some reason, (usually because new data is loaded in to accommodate a date range change) the chart will now exit fullscreen.  Users can get back to fullscreen with the new date range if they want to.
There are other more complex solutions, such as "fade document.body opacity, exit fullscreen before re-render, then re-open fullscreen right after render, then restore document.body opacity" but this creates some UI "jank" and might add more to maintenance complexity than we'd like.
checked off to indicate they have been considered. If unclear if a step is …

#2803 - Chart does not re-render well in fullscreen mode so just close fullscreen mode if it's open.

---

cmp/filter/FilterChooserModel.js
cmp/filter/impl/Option.js
cmp/filter/impl/QueryEngine.js
desktop/cmp/filter/FilterChooser.js
desktop/cmp/filter/FilterChooser.scss

Implement feedback added to https://github.com/xh/hoist-react/pull/2829:
+ Add option to sort field suggestions
+ Omit 'e.g.' prefix from field suggestions when in discover mode
+ Mute styling of 'e.g.' prefix …

FilterChooser tweaks

---

mobile/cmp/tab/impl/TabContainer.js

This PR is a workaround for inconsistent behaviour resizing a mobile tab container seen in a client app.
Onsen's 'Tabbar' uses a 'Swiper' to manage its page transitions. It sets up a resize event handler, which tells it to recalculate the size of it's pages on window resize: https://github.com/OnsenUI/OnsenUI/blob/05c8ef93b55cf4c21f31d6d614153a21cd51a2f5/core/src/ons/internal/swiper.js#L180
Due to currently unknown reasons, this event handler sometimes gets removed. I haven't yet been able to understand the cause. It happens in the client app but not in Toolbox. For the client app, it happens consistently on device, and very rarely (but it *does* occur) in the emulator. I suspect it may be due to some hard to track down race condition, but this is merely a hunch.
The workaround in this PR …

Mobile TabContainer orientation change fix

---

data/Store.js

+ Allow developer to override path to children on raw data objects.
+ No change to `StoreRecord.children` (post-processing), defaults remain the same. …

New `Store.loadTreeDataFrom` config

---

CHANGELOG.md
desktop/cmp/filter/FilterChooser.js
desktop/cmp/filter/FilterChooser.scss

+ Prevent FilterChooser instructions from wrapping.
+ Add FilterChooser.menuWidth prop
Fixes [#2857](https://github.com/xh/hoist-react/issues/2857) …

Fix FilterChooser instruction wrapping

---

cmp/grid/Grid.js

Noticed an issue where if manually changing a column's size affects another column's size (i.e. there is a flex grid that can change within its min / max width constraints), `ev.column` is null. Can be seen by resizing columns in the admin Config panel.
This change accesses the more reliable `ev.columns[0]` instead. Since flex column adjustments happen left-to-right, the first entry is always the column the user interacted with. …

Fix exception when noting manually sized columns

---

CHANGELOG.md
admin/tabs/activity/clienterrors/ClientErrorsModel.js
admin/tabs/activity/tracking/ActivityTrackingModel.js
utils/datetime/LocalDate.js

This is for issue #2845.
It is a breaking change.
Apps that take this change will need to use Hoist-Core v13.0.5 or later, as mentioned in the changelog entry.
Toolbox PR (with updated LocalDate tests): https://github.com/xh/toolbox/pull/546 …

Change LocalDate's default output fmt to yyyy-mm-dd

---

CHANGELOG.md
admin/tabs/activity/clienterrors/ClientErrorDetail.js
admin/tabs/activity/tracking/detail/ActivityDetailView.js
admin/tabs/general/alertBanner/AlertBannerPanel.js
desktop/cmp/form/FormField.js
mobile/cmp/form/FormField.js

Hope this moves the ball forward for Forms, and gets us beyond the silliness, providing a good readonly story, with minimal disruption to existing apps.
Agree with Tom -- a general binding label/value mechanism could be useful as a future iteration.
Also agree with Anselm that a readOnlyField() might be useful for the developer.  If we felt that we wanted that, could just be 
syntactic sugar on what we have.  Would like to avoid adding extra components in this space, if possible, as the relationship between the input/FormField/FormModel/FieldModel/Form is already incredibly intricate and somewhat duplicated between mobile and desktop. Again, could do in a future iteration. 
Also fixed an annoying issue preventing us from wrapping HoistInputs.
**Pull …

Support for readonly form fields without children.

---

CHANGELOG.md
mobile/cmp/button/Button.js

Fix regression introduced to mobile buttons with https://github.com/xh/hoist-react/pull/2792/files …

Fix disabling mobile buttons

---

CHANGELOG.md
cmp/grid/Grid.js
cmp/grid/GridModel.js

If every column in a grid is autosizable (visible, resizable, non-flex and non elementRenderer), autosize will reset the column order.
This is because after an autosize completes, column state is updated for each autosized column with `manuallySized: false` - and if ***all*** columns are included in a column state change, the system takes that as a sign that we should update the column order.
The problem arose because autosize takes it's column ids from the 'code order' specified in `gridModel.columns` rather the  'state order' from `gridModel.columnState`. The solution is to ensure that columns are autosized in their 'state order' rather than their 'code order'.
See Toolbox branch which can be used to reproduce the issue: https://github.com/xh/toolbox/tree/autosizeColumnOrder
Note that …

Fix autosize resetting column order

---

CHANGELOG.md
cmp/grid/impl/ColumnWidthCalculator.js

This seems to work well, tested in client app where I ran into this limitation.
> …

Fix autosizing headers when `headerName` is a react element

---

CHANGELOG.md
cmp/grid/Grid.js

Fixes user-reported bug with Excel (Windows) that adds an empty line beneath the range pasted from the clipboard in editable grids.
https://www.ag-grid.com/react-data-grid/grid-properties/ …

Suppress adding empty cell when pasting from Excel

---

CHANGELOG.md
desktop/cmp/input/NumberInput.js

As part of this fix, am also allowing the user to type in commas, the way the can currently type in the shorthand units …

Fix to NumberInput issue with `min/max` and `displayWithCommas` 

---

cmp/grid/columns/Column.js
desktop/cmp/grid/editors/impl/InlineEditorModel.js
desktop/cmp/input/NumberInput.js

Fix to issues with NumberEditor and SelectEditor.
+ Improve NumberInput workaround to avoid remounting
+ Adapt SelectEditor to new ag-Grid behavior
Note that SelectEditor still has some unfortunate focus behavior when using the enter key when grid editing.  This is *NOT* regression, and the focus with this PR is to allow us to move forward with the ag-Grid upgrade.
> …

Fix issues with NumberEditor/SelectEditor

---

CHANGELOG.md
cmp/input/HoistInputModel.js
desktop/cmp/input/NumberInput.js
mobile/cmp/input/NumberInput.js

This fixes a number of issues with NumberInput. :-)
- Precision now enforced when first focused on overprecise source value.
- Precision now enforced when setting value back to source.
- Debounce provides less thrashing when user typing in numbers
- scaleFactor now clearly documented as being a factor of 10
- Max/min are enforced.  Workaround for related Blueprint errors with this prop handled more reliably 
Also provides some additional template Hooks in HoistInputModel for future use.
**If your change is still a WIP**, please …

Enhance NumberInput

---

desktop/cmp/dash/canvas/DashCanvasModel.js

Could have sworn we made this change with previous enhancements, but apparently we did not ... this should get the `state` member initialized to the initial state in the constructor, without publishing it to the provider until it changes again (triggering the publish reaction)
> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* …

Initialize `state` member after loading initial state

---

cmp/ag-grid/AgGridModel.js

Only redraw rows when necessary - when only the absSort on a column has changed.
> …

Only redraw rows when absSort on a column has changed

---

cmp/dataview/DataView.scss
desktop/cmp/grid/editors/Editors.scss
desktop/cmp/input/DateInput.js

Adjust styling to account for removed `ag-react-container`, notably around inline editors
See issue: https://github.com/xh/hoist-react/issues/3004 …

AgGrid styling tweaks

---

cmp/store/impl/StoreFilterFieldImplModel.js

Properties includeFields and excludeFields were previously defined on the model but are now accessible via the componentProps. …

Fix destructuring to get StoreFilterField's includeFields and excludeFields values

---

desktop/cmp/grid/find/GridFindField.scss

The height of the up / down buttons messes with vertical alignment in compact toolbars: …

Fix sizing of GridFindField in compact toolbars

---

CHANGELOG.md
desktop/cmp/treemap/SplitTreeMapModel.js

Fix bug where SplitTreeMapModel.showSplitter property wasn't being set

---

CHANGELOG.md
cmp/grid/Grid.js
cmp/grid/GridModel.js
cmp/grid/impl/ColumnWidthCalculator.js
svc/GridAutosizeService.js

+ Solves a critical row-gap rendering problem jbar found in client app, which is reproduced in a toolbox branch with same name.
+ Improves autosizing to use asynchronous loops, throw away obsolete results, and start right away in managed mode.
+ I like the debounce change, because even if there is some fix to ag-Grid that would handle the "multiple data updates in single tick" we would not want to thrash in that way -- could be problematic in a number of ways for large data sets.
+ I like the async loop change because, it allows grid sizing to degrade better as grids get too large.  We should aim to never write code that can lock up browser.
+ One major client flagship app testing fine.  Want to test a bit more on a few more in-the-wild apps, and see if it (hopefully) solves other related …

Debounce Grid's data reaction + autosize improvements

---

desktop/cmp/dash/canvas/DashCanvasModel.js

DashCanvas's `setLayout()` can throw in a nasty way, bringing down the whole app with a `An error occurred while rendering this Component.` message. Seen in a client app. 
If you have saved state that references a non-existent or omitted DashCanvasViewSpec, the `setLayout()` callback gets called before the component has rendered. The check for scrollbar visibility then throws because the ref has not yet been set.
button below to …

Fix DashCanvas rendering exception

---

CHANGELOG.md
cmp/filter/FilterChooserFieldSpec.js
desktop/cmp/input/NumberInput.js
format/FormatNumber.js

Filter chooser model now accepts shorthand number inputs

---

CHANGELOG.md
cmp/form/field/BaseFieldModel.js

+ Avoid false positive when comparing array values - e.g. those emitted by multi-select inputs.
+ Fixes #3160 …

Form field dirty checking now uses lodash `isEqual`

---

CHANGELOG.md
cmp/grid/impl/ColumnWidthCalculator.js

+ Caused by grid autosizing - `ColumnWidthCalculator` is supposed to clean up the classes on its top-level DOM elements after sizing. Change back in #3057 to make these methods async defeated the cleanup in the `finally` clause.
+ A rare example where `return await` is required, and not an anti-pattern! …

Fix to gaps between select inputs and their dropdown menus

---

desktop/cmp/dock/DockViewModel.js
desktop/cmp/dock/impl/Dock.scss
desktop/cmp/modalsupport/ModalSupport.js
desktop/cmp/modalsupport/ModalSupport.scss
desktop/cmp/modalsupport/ModalSupportModel.js
desktop/cmp/modalsupport/ModalSupportOptions.js

+ Fix docked views appearing on the left due to 1 frame with `width: 100%` due to waiting for observable ref. See https://github.com/xh/hoist-react/blob/develop/desktop/cmp/modalsupport/ModalSupport.js#L59-L60
+ Don't flex-shrink docked views.
+ Remove unwanted default `500px` width for modal support dialogs. Width should either be configured, default to `90vw`, or be explicitly unset.
+ Add support for starting modal support in modal mode. Used to fix `DockView.docked = false`.
See issue: https://github.com/xh/hoist-react/issues/3148
unchecked and note in …

Dock Container fixes

---

mobx/decorators.js
mobx/decorators.ts
mobx/index.ts
mobx/makeObservable.ts

A little more complicated than you may have expected -- happy to go through this in more detail if you like.
A few unrelated cleanups to how the `mobx` imports are organized.
See interesting discussion I started on mobx discussion group on this topic.
https://github.com/mobxjs/mobx/discussions/3587
- [xX] Added CHANGELOG entry, or determined not required.
> **Pull …

Fix @bindable to produce enumerable properties

---

CHANGELOG.md
mobile/cmp/navigator/NavigatorModel.ts
mobile/cmp/navigator/impl/Page.scss

This was a tricky one to track down and figure out!
We already had code to prevent flashing pages following a transition, but it was no longer working. It's not clear **why** it stopped working, possibly a difference in the browsers CSS transition API or a change to make promises wait a frame before resolving.
The solution was to move that code to trigger on the `transitionend` event, which triggers the on the correct frame. As part of this, it was necessary to force hiding the page with a CSS class (rather than an inline style) since the inline style would be cleared as part of finishing the transition.
See issue: https://github.com/xh/hoist-react/issues/3226
**Pull request authors:** Review and check off the below. Items that do not apply can also …

Fix mobile navigator animation bug.

---

desktop/cmp/button/AppMenuButton.ts
desktop/cmp/contextmenu/ContextMenu.ts
mobile/cmp/menu/impl/Menu.ts

+ Desktop AppMenuButton now implements the advertised MenuItemLike interface, including actionFn, prepareFn and hidden.
+ Fixed a bug where ContextMenu and mobile Menu would strip out Elements and Strings.
See issue: https://github.com/xh/hoist-react/issues/3222
> collapse …

AppMenuButton fixes

---

core/HoistProps.ts
core/elem.ts
desktop/cmp/rest/RestGridModel.ts

+ Catch ReactElements passed to StandardElementFactory in typescript.
+ Don't incorrectly conflate HoistProps with ElementSpec
+ Improve documentation …

Improve Core typing of ElementSpec

---

cmp/relativetimestamp/RelativeTimestamp.ts

This fixes the bug in question.
There may be a separate issue regarding whether an element rendered in a grid cell *should* always have a context model (the grid perhaps?).  I think it should.  I will look into that and file it separately, if needed. …

RelativeTimestamp should not require a model

---

CHANGELOG.md
desktop/cmp/rest/RestGridModel.ts
desktop/cmp/rest/data/RestStore.ts

+ Use `StoreRecordId` type where applicable.
* Do not mark `id` as a required param when adding a new record - we often don't want to assign one up front - the store will use the new ID returned by the server when inserting the saved record. …

Improved signatures of `RestStore` APIs

---

CHANGELOG.md
cmp/ag-grid/AgGrid.scss
desktop/cmp/grid/impl/filter/ColumnHeaderFilter.ts
desktop/cmp/grid/impl/filter/values/ValuesTab.scss
desktop/cmp/grid/impl/filter/values/ValuesTabModel.ts

+ Allow internal grid of values to autosize + scroll horizontally so long values can be viewed in full. Pin checkbox column to keep it in place.
+ Always left-align values - right align interferes with the above + looked weird with fresh eyes.
+ Use text "(Select All)"" for values col header - client request / same as Excel.
+ Fixup remaining checkbox alignment jank.
+ Remove tiny-mode specific checkbox sizing tweak, have BP controls follow grid font size instead across modes.
+ Don't collect all store values in advance when rendering checkbox col header - do so when clicked.
+ Fixes #3293
checked off to indicate they have been considered. If unclear if a …

Minor fixes / improvements to Grid column filter UI

---

desktop/cmp/button/ButtonGroup.ts
package.json
yarn.lock

Desktop ButtonGroupProps: Allow children (for *.tsx) but make children optional (since not needed by ElementFactory)
This fixes this TS error when using the ButtonGroup and ButtonGroupInput components in *.tsx:
"Property 'children' does not exist on type 'IntrinsicAttributes & ButtonGroupProps'."
> **Pull request reviewers:** when merging this P/R, please consider using …

fix to Desktop ButtonGroupProps

---

CHANGELOG.md
cmp/filter/FilterChooserModel.ts
cmp/grid/filter/GridFilterFieldSpec.ts
desktop/cmp/grid/impl/filter/values/ValuesTabModel.ts

So FieldFilters have "unparsed" values that can evaluated at the time of filtering/evaluations.  Its a bit surprising, but there are good reason for it.  
But it can trip us up, as there are a number of places we need to remember to do that before using the value.
> collapse …

Need to parse values in FieldFilter before comparing to existing values

---

desktop/cmp/input/ButtonGroupInput.ts

I checked all other FormField props - `commitOnChange` is the only one that leaks through to the underlying component, because FormField passes it on to all HoistInput children.
See issue: https://github.com/xh/hoist-react/issues/3323 …

Fix React error when rendering ButtonGroupInput within a FormField with commitOnChange: true

---

core/HoistComponent.ts
core/HoistProps.ts

Solves this problem:
found in app that uses TSX, not elementFactory.
> single …

Support children on TSX elements

---

CHANGELOG.md
desktop/cmp/input/Select.scss
desktop/cmp/input/Select.ts

…Multi is true.
There is a corresponding Toolbox
PR: https://github.com/xh/toolbox/pull/649
and branch: https://github.com/xh/toolbox/tree/selectTagToolTips
which demo this new prop `enableTooltipsOnTags`. …

Add new `enableTooltipsOnTags` prop to `Select`

---

CHANGELOG.md
desktop/cmp/input/CodeInput.ts

Fix broken `CodeInput` copy-to-clipboard feature + enable by default

---

desktop/cmp/panel/impl/Splitter.scss

Our resizable splitter button styles were not being applied, due to the high-level of specificity in our main button styles. Particularly noticeable in dark mode where we were also losing the border.
Before:
After: …

Fix expand/collapse button styling within resizable splitter

---

CHANGELOG.md
svc/EnvironmentService.ts

+ Deprecate config `xhAppVersionCheckEnabled` in favor of object based `xhAppVersionCheck`.
+ Add support for `shouldRequireRefresh` flag
See corresponding hoist-core PR: https://github.com/xh/hoist-core/pull/299
Note that while this PR requires the hoist-core change for the `shouldRequireRefresh`, `shouldUpdate` will continue to work with prior versions of hoist-core. …

Version checking and forcing refresh

---

CHANGELOG.md
cmp/dataview/DataViewModel.ts

Resolves  #3419.
DataViewConfig no longer extends from GridConfig. Instead, any additional configs can be set through `gridOptions: GridOptions`, which is an interface of all `GridConfig` properties, less those specified in `DataViewConfig` (ie, those that were previously extended). 
This is a *breaking* change and all applications that rely on passing such properties will need to update their usage of DataViewConfig. An example of such a change is provided:
Before:
```ts
dataViewModel = new DataViewModel({
itemHeight: 80,
onKeyDown: () => {...}
});
```
After:
```ts
dataViewModel = new DataViewModel({
itemHeight: 80,
gridOptions: {
onKeyDown: () => {...}
}
});
```
**Pull request authors:** Review and check off the below. Items that do not apply can …

DataViewConfig no longer extends from GridConfig.

---

cmp/dataview/DataViewModel.ts

After re-examining the DataViewModel API, we've made explicit the support for `groupSortFn`, `showGroupRowCounts`, and `hideEmptyTextBeforeLoad`. Our previous "escape hatch" to pass parameters to GridModel did not call attention to the lack of formal support for these properties -- recent changes (#3421) have highlighted this and motivated this corresponding change.
Associated toolbox PR: https://github.com/xh/toolbox/pull/662
button …

Promote supported properties as part of DataViewModel API

---

CHANGELOG.md
cmp/grid/GridAutosizeOptions.ts
cmp/grid/GridModel.ts

Makes the experience when using "grid views" feel a lot smoother and less janky in some cases compared to autosizing after changing columns
Toolbox branch adding this to the grid tests panel: https://github.com/xh/toolbox/tree/autosizeHiddenCols …

Add support for including hidden columns when autosizing

---

CHANGELOG.md
cmp/ag-grid/AgGrid.scss
cmp/ag-grid/AgGrid.ts
cmp/grid/Grid.scss

Grid with `hideHeaders:true` omits extraneous header border

---

CHANGELOG.md
mobile/cmp/input/NumberInput.ts

Mobile number input was previously using `type=number` to constrain input to numbers. Unfortunately, browser validation interprets decimals as non-numeric and clears the input. My best guess as to why this is a recent regression is that browsers have gotten stricter about complying with the spec.
According to the docs, it is better to user `type=text` and a regex pattern to constrain valid inputs: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#using_number_inputs
We can continue to rely on `inputMode` to bring up the correct device keyboard, and use the pattern to only allow either numeric characters or numeric + shorthand units.
See issue [3450](https://github.com/xh/hoist-react/issues/3450)
**Pull request authors:** Review …

Fix mobile number input.

---

CHANGELOG.md
mobile/cmp/dialog/Dialog.scss

Fix the mobile Dialog max height to styling to prevent it becoming taller than the visible viewport. See issue https://github.com/xh/hoist-react/issues/3451
We were previously using `vh` units to achieve a similar result... however, it turns out `vh` units don't account for the url bar or navigation. Webkit bug reports have been filed, but have been responded to with "wont fix": https://nicolas-hoizey.com/articles/2015/02/18/viewport-height-is-taller-than-the-visible-part-of-the-document-in-some-mobile-browsers/#february-23rd-update 🤷 
unchecked and note in …

Fix mobile dialog max-height constraints

---

desktop/cmp/input/DateInput.scss
desktop/cmp/input/DateInput.ts

+ Ensure calendar picker shows when clicked as intended.
+ Fixes breaking change in Chrome v116
+ Fixes #3460 - see ticket for additional details on the Chrome change.
+ Add className to click handler wrapper div - no functional effect, just wanted to better document why it's there, help clarify when inspecting markup
> **Pull request reviewers:** when merging this P/R, …

Fix to DateInput with enableTextInput: false

---

CHANGELOG.md
desktop/cmp/panel/impl/PanelHeader.scss

Restore flexbox for horizontal panel header titles.

---

CHANGELOG.md
desktop/cmp/dash/canvas/DashCanvas.ts
desktop/cmp/dash/canvas/DashCanvasModel.ts

* `DashCanvas` now properly updates its layout when shown if the browser window had been resized while the component was hidden (e.g. in an inactive tab).
* Fixes #3215
> change. …

Ensure `DashCanvas` layout updated if window resized while hidden

---

CHANGELOG.md
cmp/markdown/Markdown.ts
cmp/markdown/index.ts
desktop/appcontainer/Banner.scss
desktop/appcontainer/Banner.ts
kit/react-markdown/index.ts
mobile/appcontainer/Banner.scss
mobile/appcontainer/Banner.ts
package.json
svc/AlertBannerService.ts
yarn.lock

+ Added `reactMarkdown` component and dependency. …

Allow Banners to render basic markdown such as links and emphasis.

---

CHANGELOG.md
data/cube/Query.ts
data/cube/View.ts
data/cube/row/BaseRow.ts

Post processing functions on query

---

CHANGELOG.md
cmp/grid/GridSorter.ts
cmp/grid/columns/Column.ts

I'm not 100% sure on the flag name `bottomNullSort` - suggestions welcome
Apps that implement custom Column.comparators should *not* need to make any adjustments, as long as they fall back to the provided defaultComparator.
See Toolbox example: https://github.com/xh/toolbox/pull/678
> **Pull request reviewers:** when merging this P/R, please consider using a *squash …

Add flag to Column to sort nulls to the bottom

---

CHANGELOG.md
desktop/cmp/input/TextInput.ts
mobile/cmp/input/TextInput.ts

Clicking on the right hand clear button in a `textInput` (mobile or desktop) now maintains focus on the `textInput`,
allowing a user to quickly type something else into the field.  This behaviour already existed
on the `select` input.
The loss of focus is really annoying when using the storeFilterField. …

Maintain focus on textInput on textInput clearButton click.

---

CHANGELOG.md
core/HoistComponent.ts

Thanks to Colin for finding this problem.    
useContext will force a re-render whenever it value changes -- we were changing the object reference of our ModelLookup object every time we rendered it, leading to a cascade of spurious re-renders throughout the hierarchy below.
Think the not-so recent (oct. 2022) changes to TabContainer to include a RefereshContext exacerbated this problem such that components on hidden tabs  were also re-rendering on tab switch.
To see the effect of this change, simply put a console log statement in any render method within a tab and start switching tabs in the tab container.  
checked off to indicate they have been …

Avoid spurious model lookup context changes

---

cmp/store/StoreFilterField.ts

TS Fix: allow "string | number", not just "number" on StoreFilterField "width" prop, since underlying TextInput in desktop and mobile takes "string | number" for "width".   A string width like '100%' can be useful when the StoreFilterField is the only field in a narrow "picker" grid's toolbar, and you want the field's width to adjust with the user's adjustment of the grid panel width, so that the field's clear button always stays visible.
**If your change is still a WIP**, please use the "Create draft pull request" option in the …

TS Fix: allow `string | number`, not just `number` on StoreFilterField `width` prop

---

CHANGELOG.md
desktop/cmp/button/ZoneMapperButton.ts
desktop/cmp/grouping/GroupingChooser.ts
desktop/cmp/input/Select.ts
utils/js/DomUtils.ts

Prevent 'mousedown' events within Select from closing Popovers.
See issue https://github.com/xh/hoist-react/issues/3516 …

Prevent 'mousedown' events within Select from closing Popovers.

---

CHANGELOG.md
cmp/grid/Grid.ts
cmp/grid/impl/GridHScrollbar.ts
cmp/grid/impl/GridScrollbar.ts

Add experimental `enableFullWidthScroll` Grid feature

---

CHANGELOG.md
cmp/relativetimestamp/RelativeTimestamp.ts

This is a refactor of Colin's work in the related branch, that I think better clarifies what we are doing, and how it differs from Moment.
Am curious if folks think we really need the mode 'limited' -- could either discard completely, or fold in to default as Colin has done. …

RelativeTimeStamp localDateMode v2

---

CHANGELOG.md
cmp/zoneGrid/ZoneGridModel.ts

Make ZoneGridModel more forgiving (handle possibly out of sync state)

---

CHANGELOG.md
core/HoistBase.ts

Updated `ReactionSpec.equals` type to include supported string shorthands

---

core/HoistBase.ts

Fixed the ReactionSpec type fix

---

CHANGELOG.md
cmp/ag-grid/AgGridModel.ts

Fixed bug in `AgGridModel.getExpandState()`

---

CHANGELOG.md
cmp/ag-grid/AgGrid.scss

Inline popup editor background fix

---

CHANGELOG.md
desktop/cmp/error/ErrorMessage.ts
desktop/cmp/treemap/SplitTreeMap.ts

Fix bug where `SplitTreeMap` would not render errors

---

CHANGELOG.md
admin/tabs/activity/clienterrors/ClientErrorsModel.ts
core/exception/ExceptionHandler.ts
svc/TrackService.ts

This change updates the `TrackService` and `ExceptionHandler` to post new fields to the server for logging. Support for these fields have been added in the [corresponding `hoist-core` changes](https://github.com/xh/hoist-core/pull/344).
This change also updates the `ClientErrorsModel` to pass `filterChooserModel` filters to the server for server-side filtering. This pattern exists in `TrackLogAdminPanel`.
button below to indicate it …

Harmonize TrackLog and ClientError

---

CHANGELOG.md
cmp/ag-grid/AgGrid.scss
cmp/ag-grid/AgGrid.ts
cmp/ag-grid/AgGridModel.ts
cmp/grid/Grid.ts
cmp/grid/GridModel.ts
cmp/grid/impl/ColumnWidthCalculator.ts
core/HoistComponent.ts
desktop/cmp/input/NumberInput.ts
desktop/cmp/input/TextArea.ts
kit/ag-grid/index.ts
package.json
yarn.lock

This can be reviewed in Toolbox with its corresponding PR: https://github.com/xh/toolbox/pull/709
This is a breaking change even if an app made no use of `ColumnApi` (which has been removed) because the version getting logic in an app's`Bootstrap.ts` file will need to be redone as in the [Toolbox example.](https://github.com/xh/toolbox/pull/709/files/5626e21d778e1fc72f9735d2d8f011513e1ac9c6#diff-304055320a29f66ea1255446ba8f13e0f3f1b13643bcea0c0466aa60e9288a8f)
See [What's New in AG Grid 31](https://blog.ag-grid.com/whats-new-in-ag-grid-31/) and [Upgrading to AG Grid 31](https://www.ag-grid.com/javascript-data-grid/upgrading-to-ag-grid-31/?ref=blog.ag-grid.com) for more details.
**Pull request authors:** Review and check off the below. Items that do …

Upgrade ag-grid to 31.x

---

CHANGELOG.md
desktop/cmp/grouping/GroupingChooser.ts

This fixes this issue:
caused by the the BP5 upgrade's move to popper2.
> single …

HotFix: fix groupingChooser to work with popper2

---

CHANGELOG.md
appcontainer/AppContainerModel.ts
svc/FetchService.ts

Remove ping call from FetchService.ts; move 'ping check' suggestion to AppContainerModel.ts.
This will help prevent misleading 'server unavailable' alerts if ping fails before an auth proxy session has been established.
> collapse multiple intermediate commits into a single …

Remove ping call from FetchService.ts; move 'ping check' suggestion to AppContainerModel.ts

---

CHANGELOG.md
mobile/appcontainer/Toast.scss
mobile/appcontainer/Toast.ts

We cannot use our standard `xh-bg-intent-xxx` classes for Onsen toasts, as the element we actually want to style is an inner div that we do not have a direct hook into.
See issue: https://github.com/xh/hoist-react/issues/3657 …

Fix mobile Toast intent

---

admin/tabs/userData/roles/graph/RoleGraph.ts
admin/tabs/userData/roles/graph/RoleGraphModel.ts

Improved RoleGraph error handling, added a "Top 2 levels" select

---

package.json
yarn.lock

This is needed to get projects that are installed with `npm` able to resolve this 
`import '@blueprintjs/datetime/lib/css/blueprint-datetime.css';` 
in
`hoist-react/kit/blueprint/index.ts`  
(BPjs instructs us to declare this import at the bottom of their datetime2 docs: https://blueprintjs.com/docs/#datetime2)
It turns out NPM and YARN hoist deps a little differently.
~@blueprintjs/datetime/lib/css/blueprint-datetime.css is not found because it is nested within datetime2
Blueprint's `datetime2` package declares a dependency on `datetime`.  
Yarn puts them both right under `@blueprint/`.
Npm keeps the `datetime` pkg nested in a `node_modules` dir under `datetime2` - *unless* - `datetime` is added as a top level dep, in which case `datetime` moves up to right under `@blueprint/`  - and is …

Add @blueprintjs/datetime as top level dependency

---

CHANGELOG.md
mobile/cmp/tab/impl/Tabs.scss

Previous styling inherited from Onsen was `position: absolute`. This meant that it obscured other children within a flex container, always filling the entire container.
> change. …

Mobile `TabContainer` now flexes properly within flexbox containers.

---

CHANGELOG.md
kit/blueprint/styles.scss

…sed in a grid inside a dialogBody.
Resolves the issue described here:  https://github.com/xh/hoist-react/issues/862#issuecomment-2195113273 …

Fix `datePicker` dates wrapping when used within a grid within a dialog

---

CHANGELOG.md
desktop/cmp/contextmenu/ContextMenu.ts
desktop/cmp/panel/Panel.ts
desktop/hooks/UseContextMenu.ts

Fix bug where `ContextMenu` items were being improperly positioned

---

CHANGELOG.md
data/impl/RecordSet.ts

Fix issues with `descendants` and `allDescendants`

---

CHANGELOG.md
desktop/cmp/grid/editors/SelectEditor.ts

Fix SelectEditor to ensure new value is flushed before editing stops

---

CHANGELOG.md
svc/FetchService.ts

This provides support I need for being able to catch 401s, in non-SSO based scenario, and respond appropriately by bringing up.
The handler for the successful response seemed like a good thing to add at the same time for symmetry, and we have seen a couple of places where it might have been useful, and avoided the need for  overriding FetchService to look for e.g. 200 returns with `success: false` 
- [X ] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
**If your change is still a WIP**, please use …

New handlers for FetchService

---

svc/EnvironmentService.ts

Slightly different take on this, main differences from ATM proposal are:
- the seperation of things into two endpoints, to distinguish between the full download on init (including admin info) and the lightweight heartbeat, optimized for frequent calling.
- the simplification of both of these two things into *non-whitelisted* endpoints.  Specifically, would actually like to be able to monitor this polling check in app AuthModel implementations (PRs coming soon), so as to recognize auth problems, and potentially address with banners or idling of the app.
Considered actually working auth failure into the handling here, but think we can keep it decoupled with our new hooks on FetchService.
**Pull request authors:** Review and check off the below. Items …

Handle instance changes

---

CHANGELOG.md
admin/tabs/cluster/hzobject/HzObjectModel.ts
admin/tabs/cluster/hzobject/HzObjectPanel.ts
admin/tabs/cluster/services/ServiceModel.ts
admin/tabs/cluster/services/ServicePanel.ts

Update Cluster Admin

---

CHANGELOG.md
desktop/cmp/panel/impl/dragger/DraggerModel.ts

Safari is not setting `buttons` or `button` to `1` on Drag events, which is causing our Panel resizing to early out.
See: https://github.com/xh/hoist-react/issues/3797
This workaround adds a fallback check to the deprecated `MouseEvent.which` property, which *is* being set:
https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/which#value_for_mouseevent_non-standard
As a deprecated API we obviously should not rely on it, but I **think** its safe to use as fall back for this specific issue in lieu of a better solution.
**If …

Panel dragger workaround for Safari

---

core/HoistBase.ts

+ Supports resolving the generic `T` for multiple `ReactionSpec<T>` args passed to this function, where `T` is inferred from the return type of the `track` function within each spec, individually. …

Update generic signature of `addReaction`

---

admin/tabs/cluster/logs/levels/LogLevelDialog.ts
admin/tabs/cluster/logs/levels/LogLevelDialogModel.ts
desktop/cmp/rest/impl/RestGridToolbar.ts

Threw in a Refresh button to our RestGrid for good measure -- hope that makes sense?  Obviously not attached to that. …

Update all log levels when a single row is changed

---

CHANGELOG.md
admin/tabs/cluster/memory/MemoryMonitorModel.ts
admin/tabs/cluster/memory/MemoryMonitorPanel.ts

Persist memory monitoring

---

CHANGELOG.md
promise/Promise.ts

+ Take optional `interval` and `timeout` arguments in a single options object - allow for easier (common) customization of timeout without needing to think about interval.
+ Fixes #3825 …

Breaking change to signature of `waitFor()`

---

core/persist/viewmanager/ViewManagerModel.ts
desktop/cmp/viewmanager/ViewManager.ts

+ For use by apps to mask components during view select/rebuild. …

Add public `ViewManagerModel.viewSelectionObserver`

---

desktop/cmp/dash/container/DashContainerModel.ts

+ State updates were being dropped if new state applied during re-render, when ref not available.
+ Observed in use case with ViewManager, where the parent component was being moved in the layout at same time as new dash state applied.
+ Don't ignore state updates if not rendered - store and save for later application.
+ But improve ref reaction and async state application code to avoid unintended / overlapping application of state when both state and render changing at the same time.
**If your change is still a WIP**, please use …

Fixes to DashContainerModel state handling + renders

---

cmp/viewmanager/SaveAsDialogModel.ts
cmp/viewmanager/View.ts
cmp/viewmanager/ViewInfo.ts
cmp/viewmanager/ViewManagerModel.ts
cmp/viewmanager/ViewToBlobApi.ts
desktop/cmp/viewmanager/ViewManager.ts
desktop/cmp/viewmanager/ViewMenu.ts

Harden views

---

cmp/viewmanager/View.ts
cmp/viewmanager/ViewInfo.ts
cmp/viewmanager/ViewManagerModel.ts
cmp/viewmanager/ViewToBlobApi.ts
cmp/viewmanager/index.ts
desktop/cmp/viewmanager/ViewManager.scss
desktop/cmp/viewmanager/ViewManager.ts
desktop/cmp/viewmanager/ViewManagerLocalModel.ts
desktop/cmp/viewmanager/ViewMenu.ts
desktop/cmp/viewmanager/dialog/EditForm.ts
desktop/cmp/viewmanager/dialog/EditFormModel.ts
desktop/cmp/viewmanager/dialog/ManageDialog.ts
desktop/cmp/viewmanager/dialog/ManageDialogModel.ts
desktop/cmp/viewmanager/dialog/SaveAsDialog.ts
desktop/cmp/viewmanager/dialog/SaveAsDialogModel.ts
desktop/cmp/viewmanager/dialog/Utils.ts
desktop/cmp/viewmanager/dialog/ViewMultiPanel.ts
desktop/cmp/viewmanager/dialog/ViewPanel.ts
desktop/cmp/viewmanager/dialog/ViewPanelModel.ts
svc/JsonBlobService.ts
svc/storage/BaseStorageService.ts

- Maybe never prepend? We could use unmodified name if copying global\shared, blank out name if your own

Further refinements to `ViewManager`

---

CHANGELOG.md
security/authzero/AuthZeroClient.ts

Added support for `AuthZeroClientConfig.audience`

---

data/cube/Query.ts
data/cube/row/BaseRow.ts

See issue: https://github.com/xh/hoist-react/issues/3843
Seemed like a quick win, that would allow us to clean up some code at a flagship client app. Wasn't sure about the name, its tricky to describe what this does in just a couple of words - any suggestions welcome!
> …

Allow Cube Query to opt-out of flattening redundant children

---

cmp/grid/GridModel.ts
desktop/cmp/viewmanager/dialog/ManageDialogModel.ts

Sort ungrouped items at bottom.

---

CHANGELOG.md
mobile/cmp/tab/impl/Tabs.scss

Leverages Onsen's CSS var to fix issue: https://github.com/xh/hoist-react/issues/3819  …

Fix mobile TabContainer switcher sizing and position

---

CHANGELOG.md
desktop/cmp/button/Button.scss

See issue: https://github.com/xh/hoist-react/issues/3268
Vertical:
Horizontal:
> …

Fix `ButtonGroup` borders incorrect when `vertical: true`

---

cmp/viewmanager/ViewManagerModel.ts

In `ViewManagerModel.initAsync`, `initialState` will be `undefined` if the call to `dataAccess.fetchDataAsync()` fails.  This change prevents that method from throwing under those circumstances. …

Make initialState null-safe in ViewManagerModel.stateReactions

---

cmp/viewmanager/ViewManagerModel.ts
core/model/HoistModel.ts
desktop/cmp/tab/TabSwitcher.ts
desktop/cmp/viewmanager/dialog/ManageDialog.ts
desktop/cmp/viewmanager/dialog/ViewMultiPanel.ts

Turns out our homemade class definition was a little *too* close to a general function definition, and was capturing that.
This alternative from typefest works better, and seems more standard, although it precludes HoistModels with private constructors, like our new ViewManagerModel.  Think that's probably ok.
Other changes here and in toolbox were unrelated, just pickups from the stricter typing.
button below to indicate it is not …

Improve model selector type

---

CHANGELOG.md
desktop/cmp/dash/canvas/DashCanvas.ts
desktop/cmp/dash/canvas/DashCanvasModel.ts
package.json
yarn.lock

react-grid-layout 1.4.3 -> 1.5.0

---

core/model/HoistModel.ts

- Fix difficult bug with re-render loops.
- Avoid mobx object/proxy object creation for models that don't use this property
- Avoid extra prop processing for linked models that don't use this property
> collapse multiple intermediate commits into a single commit representing …

Tighten/simplify implementation of HoistModel.componentProps

---

cmp/relativetimestamp/RelativeTimestamp.ts
desktop/cmp/input/NumberInput.ts
mobile/cmp/input/NumberInput.ts
mobile/cmp/popover/Popover.ts

Move logic referencing componentProps out of constructors and into onLinked

---

cmp/viewmanager/ViewManagerModel.ts
desktop/cmp/viewmanager/dialog/ViewPanelModel.ts

Only update dirty properties of views

---

cmp/viewmanager/DataAccess.ts
cmp/viewmanager/ViewInfo.ts
cmp/viewmanager/ViewManagerModel.ts
desktop/cmp/viewmanager/ViewManager.ts
desktop/cmp/viewmanager/ViewManagerLocalModel.ts
desktop/cmp/viewmanager/ViewMenu.ts
desktop/cmp/viewmanager/dialog/ManageDialogModel.ts

In my routable views implemention in which routes have view tokens,
I had to do this when the route got a new token:
```
const info = viewMngr.views.find(v => v.token === token);
if (!info) {
try {
await XH.jsonBlobService.getAsync(token)
} catch (e) {
// handle view doesn't exist & view not shared errors
}
viewMngr.selectViewAsync(info);
}
```
After this change, the flow is simplified to:
```
try {
await viewMngr.selectViewAsync(info);
} catch (e) {
// handle view doesn't exist & view not shared errors
}
```
**If your change is …

Pass token, not viewInfo and surface raw errors to make API more flexible.

---

desktop/appcontainer/Message.scss

Hoist React Issue: https://github.com/xh/hoist-react/issues/3792
- [ X] Caught up with `develop` branch as of last change.
- [ X] Added CHANGELOG entry, or **determined not required.**
- [ X] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [ X] Updated doc comments / prop-types, or determined not required.
- [ X] Reviewed and tested on Mobile, or determined not required.
- [ X] Created Toolbox branch / PR, or determined not required.
**If your change is still a WIP**, please use the "Create draft …

Constrain desktop message height to viewport 

---

core/persist/PersistenceProvider.ts

Tweak PersistenceProvider types

---

package.json

@lbwexler you had added this line a long while back (maybe when doing the initial Typescript stuff?) but this doesn't work on windows and causes the pre-commit hooks to fail (which really messes up merges in intellij). I could maybe figure out how to make this work on windows but pretty sure it shouldn't be needed.
Do you remember why this was added? There should be an executable installed in `node_modules/.bin` to run the local install of `tsc` so we should not need to alias it like this in our package.json - curious if you guys have issues with this script removed on your macs
checked off to indicate they have been considered. If unclear if a step is …

Remove windows-unfriendly script from package.json

---

mobile/cmp/navigator/NavigatorModel.ts

Prevent short swipes if starting a gesture on an internally scrolling element, mitigating accidental navigation while still allowing for intentional navigation gestures.
> change. …

Mobile Navigator tweak

---

CHANGELOG.md
admin/tabs/cluster/instances/websocket/WebSocketColumns.ts
admin/tabs/cluster/instances/websocket/WebSocketModel.ts
svc/WebSocketService.ts

Ticket https://github.com/xh/hoist-react/issues/3947
Server update [here](https://github.com/xh/hoist-core/pull/451)

Log client app version in websocket to be displayed for admins

---

desktop/cmp/grid/editors/BooleanEditor.ts

Fixes https://github.com/xh/hoist-react/issues/3943
I'm not entirely happy with this workaround - however, I spent far too long trying different approaches to no avail. Its still a net positive over the previous behaviour. If anybody has any better solutions I'm all ears :)
> …

Workaround for `BooleanEditor.quickToggle` and keyboard tab interaction

---

CHANGELOG.md
data/Store.ts

For https://github.com/xh/hoist-react/issues/3950

Null check on summaryRecords before accessing / using value

---

desktop/appcontainer/AboutDialog.ts
kit/onsen/theme.scss
mobile/appcontainer/AboutDialog.scss
mobile/appcontainer/AboutDialog.ts
svc/ClientHealthService.ts
svc/TrackService.ts

- Fix to ensure mobile toasts are shown above fullscreen dialogs.
- Make `XH.clientHealthService.sendReport()` public, although comment as internal.
- Same with `XH.trackService.pushPendingAsync()`.
- Tweak to about table alignment on mobile. …

Option in About dialog to send client health report on-demand

---

admin/tabs/activity/tracking/ActivityTrackingModel.ts
data/filter/BaseFilterFieldSpec.ts

- Nulls within provided values appear to break `FilterChooser` - suggestions don't show, and general typeahead support is compromised.
- Compact provided values in ctor processing.
- Repeat in admin activity tracking, where we mutate these directly (in an unsupported way).
> …

Ensure `FilterFieldSpec.values` compacted to remove nulls

---

admin/tabs/cluster/instances/logs/LogDisplayModel.ts

- Remove previous heuristic around setting width of main "content" column within the log viewer based on char count. This was not accurately ensuring all content was shown, leading to unwanted truncation of longer lines.
- Replace with hard-coded 5000px width, disable autosize completely to continue avoiding overhead there, then also hard-code width and pin line number col.
button below to indicate it is not ready yet for a final …

Update Admin log viewer handling for long lines

---

CHANGELOG.md
svc/EnvironmentService.ts

* Previously the versions loaded from the server on init were used as the baseline.
* The two versions *should* be the same, but in cases where a browser "restores" a tab and re-inits an app without reloading the code itself, the upgrade check would miss the fact that the client remained on an older version. …

Use baked-in client `XH.appVersion|Build` for upgrade check

---

CHANGELOG.md
core/types/Interfaces.ts
promise/Promise.ts
svc/TrackService.ts

This is a minor change to introduce a new 'ERROR' severity to our tracking.
It includes some unrelated typescript enhancements
This also helps set us up to provide a potentially dynamic tracking function that could be passed the received promise resolution -- but I pulled that portion of the change for now pending further discussion.
Hopefully this change is relatively simple and mergable.
See also eponymous Hoist core PR.
button …

Add 'ERROR' Severity to TrackSeverity and  Apply to rejected promise.track() calls.

---

CHANGELOG.md
desktop/cmp/button/DashCanvasAddViewButton.ts

This fix prevents this kind of ugly: …

Disable dashCanvasAddViewButton if there are no menuItems to show.

---

admin/columns/Rest.ts
admin/columns/Tracking.ts
admin/tabs/activity/tracking/ActivityTrackingModel.ts
admin/tabs/activity/tracking/ActivityTrackingPanel.ts
admin/tabs/activity/tracking/detail/ActivityDetailModel.ts
admin/tabs/activity/tracking/detail/ActivityDetailView.ts
admin/tabs/client/clients/ClientsModel.ts
admin/tabs/client/clients/ClientsPanel.ts
admin/tabs/client/clients/activity/ClientDetail.scss
admin/tabs/client/clients/activity/ClientDetailModel.ts
admin/tabs/client/clients/activity/ClientDetailPanel.ts

- New `ActivityDetailProvider` interface for common parent models to allow us to re-use `ClientDetailModel` + view.
- Assorted UI/UX tweaks …

Embed activity detail within Clients tab

---

CHANGELOG.md
core/HoistBaseDecorators.ts
mobx/decorators.ts
mobx/overrides.ts

I noticed this issue on a client app.  Tab state was initialized from saved prefKey value, but changing tab state in the app did not trigger a write to prefKey.
This issue can also be observed in toolbox on the inspector's `active` property.
-Colin …

Fix persist decorator

---

CHANGELOG.md
cmp/grouping/GroupingChooserModel.ts
desktop/cmp/grouping/GroupingChooser.scss
desktop/cmp/grouping/GroupingChooser.ts
mobile/appcontainer/FeedbackDialog.ts
mobile/appcontainer/OptionsDialog.ts
mobile/cmp/grid/impl/ColChooser.ts
mobile/cmp/grouping/GroupingChooser.scss
mobile/cmp/grouping/GroupingChooser.ts
mobile/cmp/panel/DialogPanel.scss

- Avoid two distinct popovers - show existing UIs for adjusting grouping chooser value (levels) and favorites (if enabled) side-by-side in a single popover.
- Update mobile to match, now using a full-screen dialogPanel, as with columnChooser
- Minor adjustments to CSS classnames and testIds to support
- Remove unused props / properties related to showing distinct favorites menu
- Minor tweaks to some built-in mobile dialog buttons and dialog header padding for consistency/polish.
**If your change is still a WIP**, please use the …

Consolidate `GroupingChooser` value/favorites mgmt into one popover

---

CHANGELOG.md
cmp/grouping/GroupingChooserModel.ts
desktop/cmp/grouping/GroupingChooser.scss
desktop/cmp/grouping/GroupingChooser.ts
utils/js/LangUtils.ts

* Added new props `favoritesSide` and `favoritesTitle`.
* Deprecated `popoverTitle` prop - use `editorTitle` instead.
* Moved "Save as Favorite" button to a new compact toolbar within the popover. …

Further refinements to the `GroupingChooser` desktop UI

---

CHANGELOG.md
cmp/grid/impl/Utils.ts
core/HoistComponent.ts
core/XH.ts
core/exception/ExceptionHandler.ts
core/load/LoadSupport.ts
data/filter/Utils.ts
desktop/cmp/dash/container/impl/DashContainerUtils.ts
inspector/instances/InstancesModel.ts
kit/ag-grid/index.ts
kit/highcharts/index.ts
promise/Promise.ts
svc/FetchService.ts
utils/js/LangUtils.ts
utils/js/LogUtils.ts

Started with moving toward a client-side XH.LogService, which had some nice properties for code organization, but ultimately the complexity around not having it available to  use for *early* framework logging, made me discard the idea.
Also explored some server-side configuration discussed by ATM-- but decided to hold off on that for this version.  We can always revisit (and if we added, at that point, a service might make sense).
Also, unrelated -- removed one obsolete bit of Promise code for Edge that was bothering me, and I think is now safe to remove. …

Add `XH.logLevel` for dynamic logging severity and reduced console use

---

cmp/dataview/DataView.ts
desktop/cmp/viewmanager/dialog/ManageDialog.ts

Changed to `suppressGroupChangesColumnVisibility: "suppressShowOnUngroup"`.
> …

Cleaned up deprecated agOption `suppressMakeColumnVisibleAfterUnGroup`
