admin/tabs/activity/VisitsChartModel.js
Not 100% sure about this. First ways I tried look like Month-Year to me, not necessarily Month-Day (See below).
I went with D-MMM so: 8 May, 18 Jul, 28 Aug...ect. is this too exotic for the US?
=> Drop years from visits chart labels, Fixes #217

core/HoistComponent.js
=> Added `addReaction` to hoistComponent.

app/impl/LoginPanel.js, app/impl/LoginPanel.scss, cmp/index.js, cmp/panel/Panel.js, cmp/panel/impl/PanelHeader.js, cmp/panel/impl/PanelHeader.scss, cmp/panel/index.js, styles/vars.scss
https://github.com/exhi/hoist-react/issues/234
=> Panel component

app/impl/ExceptionDialogModel.js, cmp/ToastManager.js, cmp/feedback/FeedbackDialogModel.js, promise/Promise.js, svc/ErrorTrackingService.js, svc/FeedbackService.js, utils/JsUtils.js
These are the changes to the JS in hoist react.   Are you guys thinking you want the groovy server coder in hoist core to also support message & msg?
=> Standardize on msg vs. message (or support both) (#230)

cmp/LoadMask.js, cmp/LoadMask.scss
https://github.com/exhi/hoist-react/issues/259
=> LoadMask text

columns/Core.js
See: https://www.ag-grid.com/javascript-grid-performance/#3-create-fast-cell-renderers
=> Use vanilla cellRenderer on bool check column

cmp/LoadMask.js, cmp/LoadMask.scss, styles/vars.scss
https://github.com/exhi/hoist-react/issues/259
=> LoadMask code enhancement / styling

cmp/form/dropdown/BaseComboField.js, cmp/form/dropdown/ComboField.js, cmp/form/dropdown/SelectField.js
Options can be changed through the fields props
=> Allow dynamically changing options for ComboField and SelectField

admin/tabs/activity/ActivityGrid.js, admin/tabs/clienterrors/ClientErrorPanel.js, admin/tabs/configs/differ/ConfigDiffer.js, admin/tabs/logging/viewer/LogViewerModel.js, admin/tabs/services/ServiceModel.js, admin/tabs/services/ServicePanel.js, admin/tabs/users/UserPanel.js, cmp/dataview/DataView.js, cmp/dataview/DataViewModel.js, cmp/grid/Grid.js, cmp/grid/GridModel.js, cmp/leftrightchooser/LeftRightChooser.js, cmp/leftrightchooser/LeftRightChooserModel.js, cmp/leftrightchooser/impl/ChooserToolbar.js, cmp/leftrightchooser/impl/Description.js, cmp/rest/RestGrid.js, cmp/rest/RestGridModel.js, cmp/rest/RestGridToolbar.js, data/StoreSelectionModel.js
+ Refactoring of Grid to simplify AG property setting.
=> Enhancements to Selection API for Grid and DataView

admin/tabs/logging/viewer/LogViewerDisplay.js, admin/tabs/logging/viewer/LogViewerModel.js, admin/tabs/logging/viewer/LogViewerToolbar.js, cmp/form/NumberField.js
https://github.com/exhi/hoist-react/issues/325
=> Fixed LogViewer tail mode

cmp/dataview/DataView.js, cmp/dataview/DataViewModel.js
https://github.com/exhi/hoist-react/issues/332
=> DataView emptyText

app/impl/LoginPanel.js, exception/ExceptionHandler.js, svc/FetchService.js
https://github.com/exhi/hoist-react/issues/355
=> Hide credentials on error

kit/blueprint/styles.scss
https://github.com/exhi/hoist-react/issues/343
=> [BUG] Solid background color defined for pt-minimal buttons

cmp/form/SwitchField.js, cmp/form/index.js
https://github.com/exhi/hoist-react/issues/345
=> SwitchField Component

cmp/appbar/AppBar.scss, kit/blueprint/styles.scss
https://github.com/exhi/hoist-react/issues/384
=> appBar separator extra margin

admin/tabs/configs/ConfigPanel.js, admin/tabs/configs/differ/ConfigDiffer.js, admin/tabs/configs/differ/ConfigDifferDetailModel.js, admin/tabs/configs/differ/ConfigDifferModel.js
Fixes "Accept Remote" button in popup
Admin config differ requires added "/api" URL in a deployed app
Improved JSON diffing
Triggers a reload of underlying config panel on apply remote
=> Config differ improvements, Fixes #380, Fixes #381, Fixes #392

svc/PrefService.js
+ New event prefsPushed
+ Simplify and consolidate saving of local and remote preferences.
+ Fix to brokent pushAsync
+ Fix to broken prefChange ('oldVal' now 'oldValue' as advertised)
=> Preferences Refactor

admin/tabs/logging/viewer/LogViewer.js, admin/tabs/logging/viewer/LogViewerDisplay.js, admin/tabs/logging/viewer/LogViewerModel.js
https://github.com/exhi/hoist-react/issues/330
=> Log viewer tail refresh

.eslintrc, core/XH.js
Dependent on:
[This PR should be merged first](https://github.com/exhi/hoist-dev-utils/pull/5/commits/2ae50d17861ae98aa4dd10749037e1b7b95ed5cc)
=> Add XH.IsDevelopmentMode, Fixes #399

app/impl/LoginPanel.js, cmp/rest/RestControl.js
https://github.com/exhi/hoist-react/issues/388
=> Component commit on change

cmp/grid/ColChooser.js, cmp/grid/ColChooserModel.js, cmp/leftrightchooser/LeftRightChooserFilter.js, cmp/toolbar/ToolbarSeparator.js
https://github.com/exhi/hoist-react/issues/415
=> ColChooser enhancements

kit/blueprint/styles.scss, styles/vars.scss
+ Expose dedicated CSS variables for Blueprint intents. Fixes #420
+ Use these vars for Toasts. Fixes #404
=> CSS variables for Blueprint intents.

cmp/grid/ag-grid/styles.scss
https://github.com/exhi/hoist-react/issues/370
=> Grid ContextMenu Highlight Issue

cmp/clipboard/ClipboardButton.js
=> Update ClipboardButton to use elementRef button prop

cmp/clipboard/ClipboardButton.js, core/XH.js, svc/ConfigService.js, svc/ErrorTrackingService.js, svc/FeedbackService.js, svc/FetchService.js, svc/IdentityService.js, svc/PrefService.js, svc/TrackService.js
+ Requires exhi/hoist-core#48 to be merged
+ Apologies as did not mean to loop in clipboard change as well - that also has a dedicated PR #442
=> Ensure client and session user in sync for relevant HoistImpl endpoints

desktop/cmp/grid/ag-grid/styles.scss
https://github.com/exhi/hoist-react/issues/445
=> Enforce ag-cell-focus style

admin/tabs/preferences/PreferencePanel.js, desktop/cmp/rest/data/RestStore.js
https://github.com/exhi/hoist-react/issues/405
=> Refresh RestField lookup on update

styles/XH.scss
Think we should have this, and I have use of it in a client app. We already have the var, and symmetrical a green-muted class.
=> Add xh-red-muted css class

desktop/cmp/store/StoreFilterField.js
=> Debounce filtering of the store in StoreFilterField (#465)

desktop/cmp/leftrightchooser/LeftRightChooser.js, desktop/cmp/leftrightchooser/LeftRightChooser.scss, desktop/cmp/leftrightchooser/LeftRightChooserModel.js
=>  Add option for chooser to render collapsed groups

columns/Column.js, format/FormatDate.js, format/FormatNumber.js
Referenced in https://github.com/exhi/hoist-react/issues/509
=> Tooltip API updates for Column + number/date formatters

desktop/cmp/form/NumberField.js, desktop/cmp/form/TextAreaField.js, desktop/cmp/form/TextField.js
See https://github.com/exhi/hoist-react/issues/554 for original issue
=> New "selectOnFocus" property for Text, TextArea, Number

core/HoistComponent.js, desktop/appcontainer/ExceptionDialog.js, mobile/appcontainer/ExceptionDialog.js
This seems like it is not worth the API complexity, and better to always create our internal components according to the standard patterns
Applications free to do this if they so wish.  Its a one-liner....
=> Remove hoistComponentFactory()

desktop/cmp/grid/ColChooserModel.js, desktop/cmp/grid/ExportManager.js, desktop/cmp/grid/GridModel.js, desktop/cmp/grid/GridStateModel.js
Open for review. Think this is good, but would like to test once more in updated group col demo in toolbox before merge.
=> Column Chooser and export manager handle grouped columns. Fix #588, Fix #589

admin/tabs/logging/viewer/LogViewer.js, desktop/cmp/panel/Panel.js
Looking at application code, this has the potential to remove a lot of bolierplate.
=> Enhance 'mask' prop on Panel to take a PendingTaskModel

admin/tabs/general/users/UserModel.js, admin/tabs/general/users/UserPanel.js
- UserModel: replace includeInactive boolean with activeOnly (default = true)
- Remove refresh button in panel
=> Admin/UserPanel: Toolbar changes

desktop/cmp/leftrightchooser/LeftRightChooserFilter.js
Now matches pattern in StoreFilterField.
=> Fixed error in LeftRightChooserFilter Regex. 

field/validation/constraints.js
+ Remove `notBlank` constraint as I don't see a strong use case for null-OK-but-empty-not.
+ Fixes #638
=> Empty strings should not pass required validation constraint

core/XH.js, desktop/cmp/form/JsonInput.js
Also passing props into the constructor.
This is required for Toolbox Other/Modals tab to work properly
=> (Bug Fix) JSONInput reacts to value changes

desktop/cmp/dataview/DataView.js, desktop/cmp/grid/Grid.js
=> Modify valueGetter to produce a string of each cell's data

cmp/grid/Grid.js
=> Avoid adding consecutive separators in grid context menu

core/XH.js, core/mixins/ReactiveSupport.js
+ Enhance Reactive Support to expose disposer returned by mobx
+ XH is now Reactive
=> Refactor AppTracking to account for login time.

desktop/cmp/form/FormField.scss
- set border on new select component
- use xh classes over bp3 where possible
- apply box shadow on CheckBox, Slider, ButtonGroup in non-minimal mode
=> Minimal validation css tweaks

desktop/cmp/rest/data/RestStore.js
=> RestStore should only send editable fields when saving / updating records

desktop/cmp/toolbar/Toolbar.scss
=> Toolbar css

desktop/columns/Actions.js
Fixes #784 
Just did a direct port of the logic and resulting html from our react components, everything looks and behaves the same as it did previously, and performance while scrolling grids with actions columns is much improved.
=> Action Column Performance

CHANGELOG.md, desktop/cmp/form/inputs/Checkbox.js
Fixes https://github.com/exhi/hoist-react/issues/841
=> Add Checkbox.displayUnsetState

svc/GridExportService.js
(Fixes [hoist-core #65](https://github.com/exhi/hoist-core/issues/65))
=> Add file extension and contentType args to downloadjs download call.

desktop/appcontainer/VersionBar.scss, mobile/appcontainer/VersionBar.scss
For merging IFF https://github.com/exhi/hoist-core/pull/66
=> VersionBar color mappings for additional Hoist environments

svc/GridExportService.js
Recursively build export rows for nested data, accounting for depth and sorting. #929
=> Include tree structure when exporting tree grids.

desktop/cmp/input/RadioInput.scss, desktop/cmp/input/SwitchInput.js, desktop/cmp/input/SwitchInput.scss
=> Ensure SwitchInput and RadioInput visibly show validation error.

desktop/cmp/form/FormField.js, kit/onsen/styles.scss, mobile/cmp/form/FormField.js, mobile/cmp/form/FormField.scss, mobile/cmp/input/NumberInput.js, mobile/cmp/input/SearchInput.js, mobile/cmp/input/Select.js, mobile/cmp/input/TextArea.js, mobile/cmp/input/TextInput.js
+ Add support for Form defaulted `commitOnChange` to mobile FormField
=> Catch up mobile FormField and HoistInput sizing and layout

desktop/cmp/rest/impl/RestFormModel.js
=> RestForm should check response to confirm before saving (#961)

core/XH.js
Fixes https://github.com/exhi/hoist-react/issues/966
=> Support for refreshAppAsync.

kit/onsen/theme.scss, mobile/cmp/tab/impl/Tab.js, mobile/cmp/tab/impl/TabContainer.js, mobile/cmp/tab/impl/Tabs.scss
+ Always render an onsenPage to prevent issues with Onsen's Tabbar
+ Add support for switcherPosition: 'top' to mobile
=> Fix mobile tabs

desktop/cmp/dimensionchooser/DimensionChooser.js, mobile/cmp/dimensionchooser/DimensionChooser.js, mobile/cmp/dimensionchooser/DimensionChooser.scss
- html title on desktop dimchooser button, mirroring implementation for history items
- display mobile dimchooser overflow with ellipsis
=> Dim Chooser formatting tweaks

cmp/form/validation/constraints.js
+ When dateIs validator given a max of "today", allow a value at any time on the current day.
+ Use moment() for constraint date comparisons, time-setting, formatting.
=> Update dateIs validator handling of max:today

cmp/tab/TabContainerModel.js
+ squelches react warning.
+ avoids extra rendering of default tab
=> Avoid 'late' decision about active tab.

admin/AppModel.js, cmp/tab/TabContainerModel.js
Improve handling of currentlyActive tab and route handling in TabContainer.
=> Tab improvements

svc/GridExportService.js
This allows export to support absolute sorting. Fixes #1068
=> Export use GridSorter's comparator to sort

desktop/cmp/form/FormField.scss, desktop/cmp/input/RadioInput.js, desktop/cmp/input/RadioInput.scss, desktop/cmp/input/Select.scss
See Toolbox PR: https://github.com/exhi/toolbox/pull/172. Fixes #1059
=> Ensure that Forms and FormFields are usable within Toolbars.

core/ExceptionHandler.js
Fixes #675
See hoist-core PR: https://github.com/exhi/hoist-core/pull/75
=> Force app-level refresh on SessionMismatchException.

CHANGELOG.md, cmp/grid/columns/Column.js
=> Grid Column supports function form of header/cellClass config.

cmp/grid/Grid.js
=> Workaround for AG-2879

CHANGELOG.md, core/XH.js, svc/LocalStorageService.js, utils/js/LangUtils.js
=> Local storage namespace uses appCode and username.

desktop/cmp/input/JsonInput.js, desktop/cmp/input/JsonInput.scss
=> JsonInput width should shrink beyond minimum content size

cmp/ag-grid/AgGrid.scss
=> Fix grid selection delay across pinned columns on odd rows.

CHANGELOG.md, core/elem.js
=> Include null values in `elem`'s children object

cmp/grid/columns/Column.js, data/cube/Cube.js, data/cube/Field.js, data/cube/Query.js, data/cube/View.js, data/cube/aggregate/Aggregator.js, data/cube/aggregate/SumStrictAggregator.js, data/cube/record/AggregateCubeRecord.js, data/cube/record/CubeRecord.js, data/cube/record/index.js
+ Rename Record -> CubeRecord
+ Remove additional cruft related to streaming updates.
+ Cleanup documentation, use ES6 collections, iterations
=> Cube cleanups

CHANGELOG.md, desktop/appcontainer/VersionBar.js, mobile/appcontainer/VersionBar.js
Applies to both desktop and mobile!
💎😁
=> Hoist Admin always see VersionBar in the bottom of the page

desktop/cmp/dock/impl/Dock.scss
=> Ensure DockContainer is in front of any mask in parent container.

CHANGELOG.md, core/appcontainer/AppOption.js, core/appcontainer/OptionsDialogModel.js, data/cube/View.js, desktop/appcontainer/OptionsDialog.js, mobile/appcontainer/OptionsDialog.js
Trigger a _refresh_ of the app (data) if any options changed that don't require a _reload_.
=> Rename AppOption.requireRefresh -> requireReload

desktop/cmp/input/JsonInput.scss
=> Fix JsonInput hidden text bug

data/cube/Cube.js, data/cube/Field.js, data/cube/aggregate/Aggregator.js, data/cube/aggregate/MaxAggregator.js, data/cube/aggregate/MinAggregator.js, data/cube/aggregate/SumAggregator.js, data/cube/aggregate/SumStrictAggregator.js, data/cube/aggregate/UniqueAggregator.js, data/cube/impl/QueryExecutor.js, data/cube/record/AggregateCubeRecord.js
+ Performance improvements (remove cloning, extraneous map)
+ Don't aggregate Dimensions by default!
+ Remove Cruft.
+ Support for canAggregateFn
=> Cube enhance

mobile/cmp/tab/impl/TabContainer.js
=> Allow mobile tab switcher to be hidden

mobile/cmp/input/Select.js
=> scrolling blocked in mobile when menuselect

mobile/appcontainer/Toast.js, mobile/appcontainer/Toast.scss
=> Fix how mobile toasts are positioned

CHANGELOG.md, cmp/ag-grid/AgGrid.js, cmp/ag-grid/AgGrid.scss, cmp/ag-grid/AgGridModel.js, cmp/grid/GridModel.js
Addresses Issue #1041 & also:
+ moved `showHover` around to be more consistent with configs order
=> GridModel.cellBorders

cmp/relativetimestamp/RelativeTimestamp.js
Open more for review and discussion than merge
=> Short formats for relative timestamps, Fixes #1115

mobile/cmp/grid/impl/ColChooser.js, package.json, yarn.lock
Carefully read through release notes and tested on device. Made a small tweak to the mobile column chooser - no other app changes required. Fixes #1152
=>  Update react-beautiful-dnd to 11.x.

CHANGELOG.md, kit/react-select/index.js, package.json, yarn.lock
Applied necessary changes from upgrade guide here: https://github.com/JedWatson/react-select/issues/3585
Tested and seems fine. Resolves #1153
=> Update react-select to 3.x.

CHANGELOG.md, desktop/appcontainer/AppContainer.js, desktop/cmp/button/ColChooserButton.js, desktop/cmp/dimensionchooser/DimensionChooser.js, desktop/cmp/dimensionchooser/DimensionChooser.scss, desktop/cmp/grid/impl/ColChooser.js, desktop/cmp/grid/impl/ColChooserDialog.js, desktop/cmp/grid/impl/ColChooserModel.js, desktop/cmp/grid/index.js, desktop/cmp/leftrightchooser/LeftRightChooserModel.js, styles/XH.scss
When open in a popover, immediately sync changes to the grid. Resolves #1171
=> Open desktop col chooser in a popover when using the ColChooserButton.

desktop/cmp/input/DateInput.js
+ DateInput popover closes on escape key
+ DateInput popover closes faster on blur
Fixes https://github.com/exhi/toolbox/issues/207
=> Improve DateInput popover close behaviour

CHANGELOG.md, mobile/cmp/mask/Mask.js, styles/vars.scss
+ Restore Mask.onClick handler, to enable close on tap
+ Adjust mobile mask background color to match the Onsen provided dialog mask
Fixes: #1211
=> Mobile app menu - close on mask tap

desktop/cmp/input/DateInput.js
=> Fix DateInput 'showPickerOnFocus'.

core/ExceptionHandler.js
+ Fixes #1189 (or at least hopefully improves it - won't be perfect e.g. if proxies are in play)
=> Target sessionExpired check to relative URLs only

CHANGELOG.md, desktop/cmp/input/Select.js
=> Ensure Select shows all options when refocused

desktop/cmp/input/DateInput.js
Played around with things quite a bit and landed on this setup working as expected for me in all configurations. I think it makes sense when `showPickerOnFocus` is enabled to just let the default popover interaction handling take control instead of us trying to open manually on focus.
I didn't see any issues interacting with the picker after I removed the `wait` in `onBlur` ... not sure if the issues were platform/browser/vdi specific or if they were specific to a certain configuration of the picker props, but it seemed to be working fine for my on my mac, so maybe worth exploring if that workaround is no longer needed?
=> DateInput showPickerOnFocus fixes

mobile/cmp/grid/impl/ColChooser.js, mobile/cmp/grid/impl/ColChooser.scss
Tested on device in MobileIron, VMWare Web, Chrome and Safari. Can not be tested in BB Access until released with a client app.
=> Fix mobile column chooser sizing on devices

admin/tabs/preferences/PreferencePanel.js
=> Remove edit warning for Preferences. Fixes #1204

desktop/appcontainer/VersionBar.js
Addresses issue #1201: new Pref with full control over VersionBar
co PR: HoistCore [#79](https://github.com/exhi/hoist-core/pull/79)
=> Version Bar Footer

CHANGELOG.md, desktop/appcontainer/VersionBar.js, mobile/appcontainer/VersionBar.js
update to original PR: #1223 
addresses issue: #1201
+ mobileVersionbar; + getPref with default; + env on class
=> Update to VersionBar

CHANGELOG.md, cmp/dock/DockContainer.js, cmp/dock/DockViewModel.js, desktop/cmp/dock/impl/Dock.scss, desktop/cmp/dock/impl/DockContainer.js, desktop/cmp/dock/impl/DockView.js, desktop/cmp/panel/Panel.js, desktop/cmp/panel/impl/PanelHeader.js, desktop/cmp/panel/impl/PanelHeader.scss, styles/vars.scss
* Up to date with develop branch?
* Ready for review?
* CHANGELOG entry?
* Breaking change?
* Docs updated?
* Mobile support?
* Toolbox branch / PR?
=> Compact panel headers

CHANGELOG.md, cmp/grid/GridModel.js
Half address Issue #1216: defaultCol config to be applied to all columns, except where otherwise specified
(co dev with jhaynes)
=> GridModel to accept a `defaultCol`

CHANGELOG.md, cmp/dimensionchooser/DimensionChooserModel.js
See Toolbox PR: https://github.com/exhi/toolbox/pull/219
Resolves #1233
=> DimensionChooser persists both last value and history to preference.

core/XH.js
=> Ping url for grails server exception is generated based on env

CHANGELOG.md, cmp/grid/columns/Column.js
Part 2/2 for Hoist Issue #1216 
=> Add comparator prop to Column class

CHANGELOG.md, desktop/cmp/input/Select.js
=> Add a selectOnFocus to Select Component. Issue #1248

desktop/cmp/rest/impl/RestFormModel.js
=> Submit *dirty* changes only for record editing.  Fixes 1245

CHANGELOG.md, desktop/cmp/button/ExportButton.js
=> Auto disable export button

desktop/cmp/input/TextInput.js
=> Omit clear trigger in TextInput if disabled + Prevent tabbing into clear trigger

desktop/cmp/rest/impl/RestFormField.js
(Don't change based on value alone)
=> Stabilize default rendering of Boolean control for RestGrid. Fixes #1244

CHANGELOG.md, format/FormatNumber.js
=> Number formatters should accept a partial colorSpec

desktop/cmp/form/FormField.js, mobile/cmp/form/FormField.js
=> FormField respects child input's disabled prop

CHANGELOG.md, core/XH.js, core/appcontainer/MessageModel.js, core/appcontainer/MessageSourceModel.js
- [ N/A] Created Toolbox branch / PR (link provided here, or N/A)
=> Default autoFocus to confirm button more widely

CHANGELOG.md, desktop/cmp/input/DateInput.js, yarn.lock
+ Fix issue with click closing popup immediately when enableTextInput= false
+ Fix issue with focus blur not closing popup
+ Fix issue with keyboard events not being consumed and doing multiple actions
e.g. causing parent scrolling after opening up menu via up/down
- [ X] Up to date with `develop` branch as of last change.
- [ X] Ready for review (or add `wip` label).
- [ X] Added CHANGELOG entry (or N/A)
- [X ] Checked for breaking changes (add `breaking-change` label + CHANGELOG if so, or N/A)
- [ X] Updated doc comments / prop-types (or N/A)
- [ N/A] …
=> DateInput Fixes (Fixes #1293)

CHANGELOG.md, desktop/cmp/input/Checkbox.js
=> CheckBox: accept autoFocus prop and pass to bpCheckBox

cmp/grid/Grid.js, cmp/grid/GridModel.js
=> Add experimental flags for optimizing grid reactions 

desktop/cmp/grid/columns/Actions.js, desktop/cmp/grid/columns/Actions.scss
+ Fixes #1287
- [NA] Added CHANGELOG entry (or N/A)
- [NA] Checked for breaking changes (add `breaking-change` label + CHANGELOG if so, or N/A)
- [NA] Updated doc comments / prop-types (or N/A)
> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to collapse multiple intermediate commits into a single commit representing the overall feature change. This helps keep the commit log clean and easy to scan across …
=> Tighten up action button sizing/padding in compact grids

CHANGELOG.md, admin/tabs/activity/tracking/VisitsChartModel.js, desktop/cmp/chart/Chart.js, desktop/cmp/chart/ChartModel.js
=> Rename ChartModel.config > ChartModel.highchartsConfig

cmp/ag-grid/AgGridModel.js
=> Ignore null or undefined data when retrieving pinned row data (Fixes #1303)

desktop/appcontainer/Message.js
- [ N/A] Created Toolbox branch / PR (link provided here, or N/A)
=> If dialog has cancelProps, enable close by Escape key (#1306).

desktop/cmp/toolbar/ToolbarSep.js
=> Adopt toolbarSep as a valid (legacy) alias. Fixes #1323

CHANGELOG.md, cmp/grid/columns/Column.js, svc/GridExportService.js
See issue: https://github.com/exhi/hoist-react/issues/1343
See hoist-core PR: https://github.com/exhi/hoist-core/pull/92
=> Support setting a different exportFormat per cell when exporting to Excel

CHANGELOG.md, desktop/cmp/dataview/DataViewModel.js
See https://github.com/exhi/hoist-react/issues/1337
- [https://github.com/exhi/toolbox/pull/259] Created Toolbox branch / PR (link provided here, or N/A)
=> Add sortBy support to DataViewModel

desktop/cmp/dataview/DataViewModel.js
=> Support delimited string form of sortBy in DataViewModel

CHANGELOG.md, admin/tabs/activity/clienterrors/ClientErrorModel.js, cmp/input/HoistInput.js, desktop/cmp/input/DateInput.js
=> Support local dates as minDate maxDate. Harden HoistInputs. Fixes: #1339, #1338 

CHANGELOG.md, cmp/form/validation/constraints.js
This new constraint allows an input field to exclude specific characters.
The function works on an input value that is either a string or an array of strings, …
=> New form validation constraint: stringExcludesAll

cmp/ag-grid/AgGrid.js, cmp/ag-grid/index.js, cmp/grid/Grid.js, cmp/grid/impl/ColumnHeader.js, cmp/relativetimestamp/RelativeTimestamp.js, cmp/store/StoreCountLabel.js, desktop/cmp/clipboard/ClipboardButton.js, desktop/cmp/clipboard/ClipboardMenuItem.js, desktop/cmp/dock/impl/DockView.js, kit/blueprint/Dialog.js, utils/js/LangUtils.js
=> Additional Core Functional Components

desktop/cmp/input/Select.js
=> Fix isEmpty() checks with Select.enableMulti.

desktop/cmp/dimensionchooser/DimensionChooser.js, desktop/cmp/grid/impl/ColChooser.js, desktop/cmp/leftrightchooser/LeftRightChooser.js, desktop/cmp/leftrightchooser/LeftRightChooserFilter.js, desktop/cmp/loadingindicator/LoadingIndicator.js
=> More functional

admin/tabs/general/websocket/WebSocketPanel.js, admin/tabs/monitor/MonitorResultsToolbar.js, cmp/relativetimestamp/RelativeTimestamp.js
=> Add 'bind' prop to RelativeTimestamp. Fixes #1368

CHANGELOG.md, cmp/ag-grid/AgGrid.scss
- [N/A] Reviewed for breaking changes (add `breaking-change` label + CHANGELOG if so, or N/A)
=> Set z-index on .ag-tooltip to 9999.  Fixes #1377

desktop/cmp/panel/Panel.js, mobile/cmp/panel/Panel.js
=> Make mask: 'onLoad' more robust

CHANGELOG.md, data/Record.js, data/Store.js, data/impl/RecordSet.js
- N/A Reviewed and tested on Mobile (or N/A)
#1375 
Added new properties and methods to Store and Record for accessing and iterating over children, descendants, and ancestors. Tried to maintain …
=> Store and Record Helpers (Fixes #1375)

appcontainer/ExceptionDialogModel.js, core/ExceptionHandler.js
=> Harden exception report.  Fixes: #1365

cmp/grid/helpers/GridCountLabel.js, cmp/relativetimestamp/RelativeTimestamp.js, cmp/store/StoreCountLabel.js, cmp/websocket/WebSocketIndicator.js, desktop/cmp/filechooser/FileChooser.js, desktop/cmp/leftrightchooser/LeftRightChooser.js, desktop/cmp/rest/RestGrid.js, desktop/cmp/treemap/SplitTreeMap.js
=> Pass on layout and classname props to underlying component more cleanly.

CHANGELOG.md, cmp/grid/columns/Column.js
=> Support for using renderer and elementRenderer on tree columns (Fixes #1390)

CHANGELOG.md, svc/FetchService.js
=> Edge promise fix

CHANGELOG.md, promise/Promise.js, svc/FetchService.js
- [NA] Reviewed for breaking changes (add `breaking-change` label + CHANGELOG if so, or N/A)
- [NA] Updated doc comments / prop-types (or N/A) …
=> Edge promise fix2

CHANGELOG.md, desktop/cmp/input/Select.js
- [NA] Reviewed for breaking changes (add `breaking-change` label + CHANGELOG if so, or N/A)
- [NA] Updated doc comments / prop-types (or N/A) …
=> Debounced select

CHANGELOG.md, cmp/form/Form.js, cmp/form/field/FieldModel.js, cmp/tab/TabContainer.js, cmp/tab/TabContainerModel.js, cmp/tab/TabModel.js, core/HoistComponentFunctional.js, core/HoistModel.js, core/hooks/Models.js, core/impl/ModelLookup.js, core/modelspec/ModelSpec.js, core/modelspec/creates.js, core/modelspec/uses.js, core/refresh/RefreshContextModel.js, core/refresh/RefreshContextView.js, desktop/cmp/form/FormField.js, desktop/cmp/panel/Panel.js, desktop/cmp/panel/PanelModel.js, desktop/cmp/panel/impl/PanelHeader.js, desktop/cmp/panel/impl/ResizeContainer.js, desktop/cmp/panel/impl/Splitter.js, desktop/cmp/panel/impl/dragger/Dragger.js, desktop/cmp/tab/impl/Tab.js, mobile/cmp/form/FormField.js, mobile/cmp/tab/impl/Tab.js
Change `toContext` flag to more nuanced `publishMode` to allow `ModelPublishMode.LIMITED`
=> Enhance Model Lookup

desktop/cmp/panel/impl/PanelHeader.js, desktop/cmp/panel/impl/ResizeContainer.js, desktop/cmp/panel/impl/Splitter.js, desktop/cmp/panel/impl/dragger/Dragger.js
=> Panel Model Context Fix - Fixes #1421

CHANGELOG.md, desktop/cmp/panel/PanelModel.js, desktop/cmp/panel/impl/dragger/DraggerAnimatedModel.js, desktop/cmp/panel/impl/dragger/DraggerModel.js
=> minSize config prop added to panelModel

CHANGELOG.md, cmp/dataview/DataView.js
- [ x ] Up to date with `develop` branch as of last change.
- [ x ] Ready for review (or open as a draft PR / add `wip` label).
- [ x ] Added CHANGELOG entry (or N/A)
- [ x ] Reviewed for breaking changes (add `breaking-change` label + CHANGELOG if so, or N/A)
- [ x ] Updated doc comments / prop-types (or N/A)
- [ N/A ] Reviewed and tested on Mobile (or N/A)
- [ N/A ] Created Toolbox branch / PR (link provided here, or N/A) …
=> Updated DataView to add propTypes and make itemHeight required

desktop/cmp/rest/RestGrid.js, desktop/cmp/rest/impl/RestGridToolbar.js
=> Preserve model Context for extraToolbarItems in RestGrid (Fixes #1439)

desktop/cmp/rest/data/RestStore.js
- [ x ] Up to date with `develop` branch as of last change.
- [ x ] Ready for review (or open as a draft PR / add `wip` label).
- [ N/A ] Added CHANGELOG entry (or N/A)
- [ N/A ] Reviewed for breaking changes (add `breaking-change` label + CHANGELOG if so, or N/A)
- [ x ] Updated doc comments / prop-types (or N/A)
- [ N/A ] Reviewed and tested on Mobile (or N/A)
- [ N/A ] Created Toolbox branch / PR (link provided here, or N/A) …
=> Fixed issue where dataRoot was not accounted for in RestStore response

svc/GridExportService.js
=> Use rendered ordering to sort columns for export.

core/mixins/LoadSupport.js
=> 'lastLoadRequested' and 'lastLoadComplete' should be observable (Fixes #1387)

CHANGELOG.md, desktop/cmp/input/NumberInput.js
=> fix autoFocus on NumberInput

CHANGELOG.md, cmp/dataview/DataViewModel.js, cmp/grid/Grid.js, cmp/grid/GridModel.js, desktop/cmp/rest/RestGridModel.js
- [N/A] Reviewed for breaking changes (add `breaking-change` label + CHANGELOG if so, or N/A)
=> replace contextMenuFn with contextMenu (#1419)

desktop/cmp/input/Slider.js
=> Validate labelStepSize on Slider

CHANGELOG.md, desktop/cmp/leftrightchooser/LeftRightChooserModel.js
=> Add option to show counts in column headers

CHANGELOG.md, desktop/cmp/input/NumberInput.js, desktop/cmp/input/TextArea.js, desktop/cmp/input/TextInput.js
=> Expose inputRef prop

core/ExceptionHandler.js
- [NA] Added CHANGELOG entry (or N/A)
=> Skip auto refresh failure log

CHANGELOG.md, svc/GridExportService.js
=> Use agGrid's aggData

CHANGELOG.md, cmp/grid/Grid.scss, cmp/grid/columns/Column.js
=> Add tooltipElementRenderer Column config (Fixes #1459)

CHANGELOG.md, desktop/cmp/rest/RestGridModel.js, desktop/cmp/rest/impl/RestGridToolbar.js
=> Rest grid export

cmp/grid/GridModel.js, svc/GridExportService.js
=> Add typedef for ExportOptions (Fixes #1491)

CHANGELOG.md, desktop/cmp/treemap/TreeMap.js
=> Add auto-scrolling to Treemap

CHANGELOG.md, cmp/grid/Grid.js, cmp/grid/GridModel.js
https://github.com/xh/toolbox/tree/dynamicEmptyText
Not suggesting we pull these changes in, but might be useful to see.
=> Dynamic empty text

cmp/relativetimestamp/RelativeTimestamp.js
=> Fix bug when getRelativeTimeStamp given no options

CHANGELOG.md, cmp/chart/Chart.js
=> Stop resize on hiding chart

desktop/cmp/input/Select.js
=> Suggested clean up

cmp/relativetimestamp/RelativeTimestamp.js
=> Add default prefix

cmp/chart/Chart.js
=> Observe chartRef.current

appcontainer/ImpersonationBarModel.js, svc/IdentityService.js
=> Move config check to identityService

cmp/chart/Chart.js
=> Observe theme and re-render on change

CHANGELOG.md, desktop/cmp/form/FormField.js, mobile/cmp/form/FormField.js
https://github.com/xh/toolbox/pull/326 …
=> Added `requiredIndicator` to FormField

CHANGELOG.md, admin/tabs/general/about/AboutPanel.js, appcontainer/AboutDialogModel.js, appcontainer/AppContainerModel.js, mobile/appcontainer/UpdateBar.js, svc/EnvironmentService.js
+ Clarify client vs. server-side build and version tags
+ Build info included with hoist-core 6.4+ only - will be null + check will be a no-op otherwise …
=> App build included in version check

desktop/cmp/dash/DashContainerModel.js, desktop/cmp/dash/DashViewModel.js, desktop/cmp/dash/DashViewSpec.js, desktop/cmp/dash/impl/DashContainerUtils.js, icon/Icon.js, kit/golden-layout/index.js, kit/golden-layout/styles.scss
+ User can rename tabs by double-clicking on the title when ViewSpec.allowRename = true.
+ Make DashViewModel's icon and title distinct observables from viewState
See Toolbox PR: https://github.com/xh/toolbox/pull/327/files …
=> Allow user to rename tabs in DashContainer

desktop/cmp/dash/DashContainer.js, desktop/cmp/dash/DashContainerModel.js, desktop/cmp/dash/DashViewModel.js, desktop/cmp/dash/DashViewSpec.js, desktop/cmp/dash/impl/DashContainerUtils.js, desktop/cmp/dash/impl/DashContainerViewDialog.js
+ Allow preventing adding views to the DashContainer …
=> Allow conditionally excluding views from the DashContainer

CHANGELOG.md, desktop/cmp/input/CodeInput.js
=> Add autoFocus prop to CodeInput

CHANGELOG.md, desktop/cmp/input/Select.js, mobile/cmp/input/Select.js
=> Add `hideIndicator` prop to Select

CHANGELOG.md, cmp/chart/Chart.js, utils/react/Hooks.js
=> Add guards to useOnResize to ignore visibility changes

utils/react/Hooks.js
=> Fix useOnResize hook to respond to size changes along a single dimension

desktop/cmp/dash/impl/AddViewMenu.js
Groups are inserted at the ordered position of the first item in the group
> single …
=> Allow devs full control over the order of groups within the AddViewMenu

CHANGELOG.md, desktop/cmp/dimensionchooser/DimensionChooser.js
=> Allow overriding popover position for dimension chooser

appcontainer/login/LoginPanelModel.js, desktop/appcontainer/LoginPanel.js, mobile/appcontainer/LoginPanel.js
+ This is almost always instant during local development, but can take a bit of time on a slower connection.
+ Mask should also help to avoid double-submits, which can result in app init being called twice. …
=> Mask login panel while submitting

CHANGELOG.md, desktop/cmp/leftrightchooser/LeftRightChooserFilter.js
=> Correct LeftRightChooserFilter

CHANGELOG.md, data/Store.js
=> Store constructor data

CHANGELOG.md, cmp/grid/columns/Column.js, cmp/grid/columns/ColumnGroup.js, svc/GridExportService.js
=> Add support for non-string headerName

CHANGELOG.md, cmp/grid/GridModel.js, desktop/cmp/contextmenu/StoreContextMenu.js
=> Add default Autosize Columns option

CHANGELOG.md, desktop/cmp/grid/columns/Actions.js
=> Add buttonEl param for action columns actionFn calls

data/cube/Cube.js, data/cube/View.js, data/cube/impl/AggregateRow.js, yarn.lock
+ Set parent info on row metadata …
=> + Enhance Cube API for dynamic queries on View and observable info

data/cube/Cube.js, data/cube/CubeField.js, data/cube/View.js, data/cube/aggregate/Aggregator.js, data/cube/aggregate/MaxAggregator.js, data/cube/aggregate/MinAggregator.js, data/cube/aggregate/SumAggregator.js, data/cube/aggregate/SumStrictAggregator.js, data/cube/aggregate/UniqueAggregator.js, data/cube/impl/AggregateRow.js, data/cube/impl/LeafRow.js, data/cube/impl/RowUpdate.js, data/cube/impl/index.js
=> Cube performance + assorted API improvements

CHANGELOG.md, mobile/cmp/pinpad/PinPad.js
=> Fix bug where pinPad would not display 0

desktop/cmp/rest/impl/RestFormField.js
=> RestFormFields of type 'int' should not allow decimals

data/cube/Query.js, data/cube/View.js
=> Add getDimensionValues() to View

CHANGELOG.md, admin/tabs/general/configs/differ/ConfigDifferModel.js
=> Fix Record problem in ConfigDiffer

core/XH.js, desktop/cmp/button/AppMenuButton.js, mobile/cmp/header/AppMenuModel.js
=> Add Impersonate app menu item

core/XH.js
=> Include exception message in "Failed to initialize services" exception dialog

CHANGELOG.md, cmp/store/StoreFilterField.js, desktop/cmp/store/impl/StoreFilterField.js, mobile/cmp/store/impl/StoreFilterField.js
=> Added ...props to StoreFilterField components

CHANGELOG.md, cmp/grid/Grid.js
=> Change grid to configure selection on pinned row click

CHANGELOG.md, core/XH.js, svc/EnvironmentService.js
=> Set Doc title to clientAppName

desktop/cmp/dash/DashContainerModel.js
Fixes: #1669
See Toolbox branch: https://github.com/xh/toolbox/tree/dashReRender
> …
=> Regenerate GoldenLayout after unmount

cmp/dataview/DataViewModel.js
- N/A Added CHANGELOG entry, or determined not required. …
=> Correct order of arguments in apiRemoved

CHANGELOG.md, cmp/tab/TabContainerModel.js
=> Tab container model tracker

cmp/grid/Grid.js, core/HoistComponentFunctional.js
=> Fix to issue with DisplayName in React Dev tools

CHANGELOG.md, admin/tabs/logging/viewer/LogViewerModel.js, core/mixins/ReactiveSupport.js, yarn.lock
=> debounce support for reactions

CHANGELOG.md, cmp/dataview/DataView.js, cmp/dataview/DataView.scss, cmp/dataview/DataViewModel.js, cmp/grid/Grid.js, cmp/grid/GridModel.js
=> Allow GridModel to provide custom group row renderers.

CHANGELOG.md, package.json, yarn.lock
=> Upgrade to react-beautiful-dnd 12.2

desktop/cmp/dash/DashContainerModel.js
Also please merge matching branch on toolbox
> single commit should be *rebased* …
=> Support for viewSpecDefaults

desktop/cmp/dash/impl/DashContainerContextMenu.js
=> Fix menu when there are no available widgets to add.

core/mixins/LoadSupport.js
=> LoadSupport skips auto-refresh if we have a pending triggered refresh

CHANGELOG.md, desktop/cmp/input/ButtonGroupInput.js
=> Work around Blueprint bug

core/ExceptionHandler.js, desktop/cmp/rest/impl/RestFormModel.js, exception/Exception.js
=> Exception handling -- support isRoutine on client

data/cube/Cube.js, data/cube/View.js, utils/async/AsyncUtils.js
=> Enhancements to Cube API

desktop/cmp/panel/PanelModel.js
Added for consistency with changes made for https://github.com/xh/hoist-react/pull/1680 …
=> Use debounce rather than delay for MobX reactions

data/Store.js, data/cube/Cube.js
+ Early return Store.updateData() …
=> Add Cube.updateInfo()

core/XH.js
=> Tweaks to service init exception wrapping and re-throwing

admin/tabs/general/configs/ConfigModel.js, admin/tabs/preferences/PreferencePanel.js, admin/tabs/preferences/UserPreferencePanel.js
=> Truncate JSON column values in Admin Config + Preference grids

desktop/cmp/button/ButtonGroup.scss, styles/vars.scss
- N/A Added CHANGELOG entry, or determined not required. …
=> Fix broken colors on ButtonGroup

CHANGELOG.md, cmp/grid/columns/Column.js
=> Add headerAlign config on Column

cmp/dataview/DataViewModel.js
=> Fixed DataViewModel column mapping with field type-checking

CHANGELOG.md, cmp/relativetimestamp/RelativeTimestamp.js
=> Relative Timestamp fixes

core/mixins/ReactiveSupport.js
=> Fix to 'debounce' argument in addReaction

CHANGELOG.md, svc/WebSocketService.js
=> WebSocketService reports connected *after* channelKey installed

CHANGELOG.md, admin/tabs/logging/viewer/LogViewerToolbar.js
=> Properly destructure props for LogViewerToolbar

CHANGELOG.md, desktop/cmp/input/Select.js
=> Change default selectOnFocus behavior in Select

desktop/cmp/dash/DashContainer.js, desktop/cmp/dash/DashContainer.scss, desktop/cmp/dash/DashContainerModel.js
=> Overlay for empty dash container

CHANGELOG.md, cmp/dock/DockContainerModel.js, cmp/dock/DockViewModel.js, cmp/dock/impl/DockViewRefreshContextModel.js, desktop/cmp/dock/impl/DockView.js
See issue #1752.
See Toolbox PR: https://github.com/xh/toolbox/pull/377
> single …
=> Add RenderMode / RefreshMode support to DockContainer.

CHANGELOG.md, cmp/grid/impl/ColumnHeader.js
=> Autosize columns on column header double-click / double tap.

mobile/cmp/grid/impl/ColChooser.js, mobile/cmp/grid/impl/ColChooser.scss
=> Fix Mobile Col Chooser Draggable flex following scrolling Panel changes

cmp/grid/columns/Column.js
=> Don't allow hiding columns via dragging on mobile

kit/onsen/index.js
Improve tap speed detection, which was problematic in certain components (i.e. PinPad) …
=> Enable Onsen's built-in FastClick for secure mobile browsers

kit/onsen/index.js, mobile/cmp/pinpad/PinPad.js, mobile/cmp/pinpad/PinPadModel.js
=> Limit FastClick scope to just the PinPad, to fix touch regression react-select

cmp/grid/Grid.js
See Toolbox example: https://github.com/xh/toolbox/pull/380 …
=> Add experimental 'externalSort' flag to Grid

desktop/cmp/panel/impl/PanelHeader.js, desktop/cmp/panel/impl/PanelHeader.scss
Co-dev: John and Petra
This PR addresses issue https://github.com/xh/hoist-react/issues/1769
- [N/R] Added CHANGELOG entry, or determined not required.
- [N/R] Updated doc comments / prop-types, or determined not required.
> **Pull request …
=> Stopped event propagation in panel header items

CHANGELOG.md, admin/tabs/logging/LoggingTab.js
This addresses issue https://github.com/xh/hoist-react/issues/1768
To-do: 
- Create hoist-core PR for Bootstrap Config Creation and to disable endpoints on grails app
> **Pull request reviewers:** when merging this P/R, please consider …
=> Log viewer config

CHANGELOG.md, cmp/grid/GridStateModel.js
=> Do not save/restore width of non-resizable columns

icon/Icon.js, icon/impl/IconCmp.js
=> Restore rest arguments for icon factories

cmp/ag-grid/AgGridModel.js
See issue https://github.com/xh/hoist-react/issues/1745 …
=> Summary row height responds to sizingMode is changes.

kit/blueprint/styles.scss
See issue https://github.com/xh/hoist-react/issues/1594 …
=> Fix NumberInput's left icon styling.

CHANGELOG.md, desktop/cmp/panel/Panel.js, desktop/cmp/panel/Panel.scss
=> Consistent ClassName placement on Panel dom elements

CHANGELOG.md, desktop/cmp/panel/Panel.js, desktop/cmp/panel/Panel.scss
See small corresponding Toolbox PR: https://github.com/xh/toolbox/pull/383
> single …
=> Panel class

desktop/cmp/button/AppMenuButton.js
=> Don't pass extraItems prop to button element in AppMenuButton

CHANGELOG.md, cmp/dock/DockViewModel.js, desktop/cmp/dock/impl/Dock.scss, desktop/cmp/dock/impl/DockView.js
See issue: https://github.com/xh/hoist-react/issues/1773
See toolbox PR: https://github.com/xh/toolbox/pull/381 …
=> Dock view dimensions

cmp/ag-grid/AgGrid.js
=> Set headerHeight according to initial sizingMode, not only upon change

desktop/cmp/dock/impl/Dock.scss, desktop/cmp/dock/impl/DockView.js
See https://github.com/xh/hoist-react/issues/1806 …
=> Unsized DockViews elide their titles to fit inner content width.

CHANGELOG.md, cmp/chart/Chart.js, desktop/cmp/dash/DashContainer.js, desktop/cmp/treemap/TreeMap.js, package.json, utils/js/DomUtils.js, utils/react/Hooks.js, yarn.lock
=> Update resize hooks

CHANGELOG.md, cmp/grid/Grid.js, cmp/grid/GridModel.js
Here is a branch in Toolbox to test this change:
https://github.com/xh/toolbox/tree/allow-no-sort-on-group-rows
(that branch doesn't need to be merged in, IMO) …
=> Allow no sort on group rows

CHANGELOG.md, kit/blueprint/styles.scss
Fixes https://github.com/xh/hoist-react/issues/1803 …
=> Allow Icons as rightElements in inputs.

cmp/ag-grid/AgGrid.scss
=> Update grid header css to use our css variables

core/mixins/LoadSupport.js
=> Less Intrusive Exception Logging for Routine Exceptions

desktop/cmp/contextmenu/StoreContextMenu.js
=> Use Column.getValueFn to retrieve cell values for Copy Cell action

cmp/grid/columns/ColumnGroup.js
See issue: https://github.com/xh/hoist-react/issues/1828
Toolbox PR: https://github.com/xh/toolbox/pull/392 …
=> Fix header alignment for ColumnGroups

utils/datetime/LocalDate.js
=> Add LocalDate isWeekday and currentOrNextWeekday()

CHANGELOG.md, cmp/grid/columns/Column.js, cmp/grid/columns/ColumnGroup.js
=> Remove ColumnGroup.align from API

desktop/cmp/dash/DashViewSpec.js
=> Support storing arbitrary additional properties on DashViewSpec.

CHANGELOG.md, appcontainer/ExceptionDialogModel.js
=> Don't overwrite existing severe exceptions in the exception dialog

CHANGELOG.md, cmp/grid/columns/Column.js, data/Record.js
Please also merge related:
https://github.com/xh/toolbox/pull/393/files
> single …
=> Enhance record data with id

cmp/ag-grid/AgGrid.scss
+ Changed z-index of ag-popups to appear over bp-dialogs
+ Applied padding to select all checkbox option in col set filter
Co-dev: Anselm and Petra
=> Styling fixes to ag-grid popups and column set filter

cmp/tab/TabContainerModel.js
=> Add TabContainerModel prev/next tab getters + nav

svc/GridExportService.js
See issue: https://github.com/xh/hoist-core/issues/74
See corresponding hoist-core pr: https://github.com/xh/hoist-core/pull/137 …
=> Use `xhExportConfig` config to manage export toasts.

svc/GridExportService.js
=> Don't throw if `xhExportConfig` config does not exist.

CHANGELOG.md, cmp/input/HoistInput.js, cmp/store/StoreFilterField.js, cmp/store/impl/StoreFilterFieldImplModel.js, core/HoistModel.js, core/mixins/ReactiveSupport.js, data/Store.js, desktop/cmp/store/impl/StoreFilterField.js, mobile/cmp/store/impl/StoreFilterField.js
-  Hold state on Store or Model, not locally 
-  Ensure that it always resynchronizes with Grid/Store when mounted
-  Don't freeze filter related props.
Please also merge related toolbox PR …
=> Fix and Simplify StoreFilterField

CHANGELOG.md, mobile/cmp/menu/Menu.js, mobile/cmp/menu/Menu.scss
See issue: https://github.com/xh/hoist-react/issues/1862 …
=> Constrain mobile menus to the bottom of the viewport, scrolling if necessary.

CHANGELOG.md, desktop/cmp/button/ColAutosizeButton.js, desktop/cmp/button/index.js, mobile/cmp/button/ColAutosizeButton.js, mobile/cmp/button/index.js
See issue https://github.com/xh/hoist-react/issues/1736 …
=> Add column autosize buttons.

styles/vars.scss
=> Reduce tree grid indentation for mobile

cmp/store/impl/StoreFilterFieldImplModel.js
=> Avoid spurious change events in SFF

data/Store.js
- [x ] Caught up with `develop` branch as of last change. …
=> Fix issue with incorrect re-use of parent pointers in Store.loadData

cmp/store/StoreFilterField.js, desktop/cmp/store/impl/StoreFilterField.js, mobile/cmp/store/impl/StoreFilterField.js
=> Ensure impl components are bound to the local impl model and prop

cmp/grid/GridModel.js, cmp/grid/columns/Column.js, svc/GridAutosizeService.js
+ Enhance documentation
+ Look at allRecords, not just records to size based on currently filtered records.
+ Minor style tweaks
+ Avoid copying record array for every column
> …
=> Prepare for early release with optional new resizing mode flag

CHANGELOG.md, cmp/grid/Grid.scss, cmp/grid/GridModel.js, cmp/grid/columns/Column.js, core/XH.js, svc/GridAutosizeService.js, svc/index.js
=> Autosize columns

cmp/grid/columns/Column.js, svc/GridAutosizeService.js
See https://github.com/xh/hoist-react/issues/1877 …
=> Autosize tweaks:

cmp/grid/Grid.js, cmp/grid/GridModel.js
- [X ] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so. …
=> Add useVirtualColumns

CHANGELOG.md, cmp/grid/GridModel.js, cmp/grid/columns/Column.js, cmp/grid/impl/ColumnHeader.js, desktop/cmp/button/ColAutosizeButton.js, desktop/cmp/contextmenu/StoreContextMenu.js, mobile/cmp/button/ColAutosizeButton.js, svc/GridAutosizeService.js
=> Ensure consistent casing of 'autoSize' throughout

CHANGELOG.md, cmp/grid/GridModel.js, cmp/grid/GridStateModel.js, desktop/cmp/grid/impl/ColChooser.js, desktop/cmp/grid/impl/ColChooserModel.js, mobile/cmp/grid/impl/ColChooser.js, mobile/cmp/grid/impl/ColChooserModel.js, yarn.lock
=> Allowing grid to reset without a StateModel

cmp/grid/GridModel.js, cmp/grid/columns/Column.js, cmp/grid/impl/ColumnHeader.js, desktop/cmp/button/ColAutosizeButton.js, desktop/cmp/contextmenu/StoreContextMenu.js, mobile/cmp/button/ColAutosizeButton.js, svc/GridAutosizeService.js
=> autosizeColumns options param, allow autosize without overlay

cmp/grid/GridModel.js, cmp/grid/columns/Column.js
Fixes https://github.com/xh/hoist-react/issues/1656 …
=> Fix issues with Tooltip & TooltipElement

cmp/grid/impl/ColumnHeader.js
+ Minor cleanup with use of olderThan …
=> Avoid Sorting on end of drag operation.

svc/GridAutosizeService.js
=> Autosize header warning

CHANGELOG.md, cmp/grid/GridModel.js, cmp/grid/columns/Column.js, svc/GridAutosizeService.js, svc/impl/ColumnWidthCalculator.js
=> Autosize distributes extra space

CHANGELOG.md, cmp/grid/columns/Column.js
=> Set lockVisible when Column.hideable = false

core/AppSpec.js, desktop/appcontainer/AppContainer.js, desktop/appcontainer/IdleDialog.js, mobile/appcontainer/AppContainer.js, mobile/appcontainer/IdleDialog.js
=> Cleanup to internal idleDialog to export factory

desktop/appcontainer/ExceptionDialog.js, mobile/appcontainer/ExceptionDialog.js
=> WIP - ExceptionDialog will include a button to end impersonation if appropriate, Fixes: 

CHANGELOG.md, admin/tabs/general/ehcache/EhCacheModel.js, admin/tabs/general/websocket/WebSocketModel.js, admin/tabs/logging/LogLevelPanel.js, cmp/grid/GridAutosizeMode.js, cmp/grid/GridModel.js, cmp/grid/columns/Core.js, cmp/grid/helpers/GridCountLabel.js, cmp/grid/impl/ColumnHeader.js, cmp/grid/impl/ColumnWidthCalculator.js, cmp/grid/index.js, desktop/cmp/button/ColAutosizeButton.js, desktop/cmp/contextmenu/StoreContextMenu.js, mobile/cmp/button/ColAutosizeButton.js, svc/GridAutosizeService.js
Please also merge related toolbox PR …
=> Promote Hoist autosizing / Remove emptyFlexColumn

utils/js/LangUtils.js
=> Avoid trailing separators!

CHANGELOG.md, desktop/cmp/dash/DashContainerModel.js
See Toolbox PR: https://github.com/xh/toolbox/pull/402 …
=> Add `layoutLocked` and `contentLocked` modes to DashContainer

cmp/grid/Grid.js, desktop/cmp/contextmenu/StoreContextMenu.js
=> Remove `export` context menu tokens when not on a desktop device.

desktop/cmp/contextmenu/StoreContextMenu.js
Per Anselm, updating icons for Export to Excel and Export to CSV context menu items
- [x ] Caught up with `develop` branch as of last change. …
=> Changed export icons in store context menu

cmp/grid/GridModel.js
=> Workaround for AG-4243 (Fixes #1928)

desktop/cmp/panel/impl/dragger/Dragger.js, desktop/cmp/panel/impl/dragger/DraggerModel.js
=> Get panel resizing working with touch events

CHANGELOG.md, cmp/pinpad/PinPad.js, cmp/pinpad/PinPadModel.js, cmp/pinpad/index.js, desktop/appcontainer/AppContainer.js, desktop/cmp/pinpad/impl/PinPad.js, desktop/cmp/pinpad/impl/PinPad.scss, dynamics/desktop.js, dynamics/mobile.js, mobile/appcontainer/AppContainer.js, mobile/cmp/pinpad/impl/PinPad.js, mobile/cmp/pinpad/impl/PinPad.scss
Moves PinPad to `cmp`, and add desktop implementation.
See Toolbox PR: https://github.com/xh/toolbox/pull/404 …
=> Cross platform PinPad

CHANGELOG.md, LICENSE.md, package.json
=> Update to Apache 2.0 open source license

data/Store.js
+ JsDoc and method param name updates for clarity. (I found "fromFiltered" a bit ambiguous - i.e. could be incorrectly interpreted as "from the records that have been filtered OUT".) …
=> Add Store.recordIsFiltered()

core/mixins/LoadSupport.js, svc/TrackService.js, utils/js/WithDebug.js
=> Log elapsed durations with ms units label

cmp/pinpad/PinPadModel.js, mobile/cmp/pinpad/impl/PinPad.js
=> Include FastClick on desktop / tablet pinpad

desktop/cmp/input/ButtonGroupInput.js
=> More Cleanly Seperate props in ButtonGroupInput

cmp/dimensionchooser/DimensionChooserModel.js
=> Fix to history in persistence in DimChooser

CHANGELOG.md, admin/App.js, admin/AppModel.js
=> Add option to omit Monitor tab in Admin app, Fixes: #1959

cmp/grid/columns/Column.js, cmp/grid/impl/GridSorter.js, kit/ag-grid/index.js
See Toolbox PR: https://github.com/xh/toolbox/pull/413 …
=> Remove requirement to import AgGridUtils

core/XH.js, svc/LocalStorageService.js
This PR simplifies the load sequence, and also fixes a problem with the EnvironmentService not being properly loaded when an admin user starts a new session
+ Load EnvrionmentService post
+ Harden selected aliases in XH
+ Remove long-lines in XH …
=> Load EnvironmentService post-auth

CHANGELOG.md, exception/Exception.js, promise/Promise.js, svc/FetchService.js
1) Improve Promise.timeout
- Don't mutate argument
- Throw exception with name, interval
2) Throw clean exception for timeouts in fetchService
+ Include fetchOptions (needed by ExceptionHandler), name
3) Remove Stacktraces from non-server Fetch Exceptions.
+ This is usually noise, and better to have consistent expectation for these Exceptions.
(They are *not* returned if there is an HTTP Error)
button below to indicate it is not …
=> Enhance Fetch and timeout related exceptions

CHANGELOG.md, desktop/cmp/treemap/TreeMapModel.js
This fixes [this issue](https://github.com/xh/hoist-react/issues/1989).
> single …
=> Tree map sort fix

svc/GridExportService.js
=> Fixes: Exports no longer sorted properly.  (#1994)

core/XH.js
+ In particular, we don't otherwise/generally track the app version with each entry, but including that with the initial load bundle seemed expedient. …
=> Track app version/build/href with initial load

desktop/cmp/input/CodeInput.scss, svc/GridExportService.js
=> Export sort fix

CHANGELOG.md, kit/blueprint/styles.scss, styles/vars.scss
Signed-off-by: Petra Laohakul <petra@xh.io>
button below to indicate it is not ready …
=> Minimal / outlined buttons use CSS vars for intent colors

CHANGELOG.md, desktop/cmp/input/CodeInput.js
=> Debug CodeInput readonly/disabled reaction

CHANGELOG.md, cmp/tab/TabContainerModel.js, desktop/cmp/treemap/SplitTreeMapModel.js
=> TabContainerModel accepts an emptyText property, Fixes: #2003

CHANGELOG.md, cmp/form/validation/constraints.js
Addresses https://github.com/xh/hoist-react/issues/2013
Added toolbox example, which replaces previous email validation: https://github.com/xh/toolbox/pull/417 …
=> Add valid email constraint

cmp/ag-grid/AgGridModel.js, cmp/grid/GridModel.js, svc/FetchService.js, utils/js/LangUtils.js
=> Add and use `apiDeprecated` util function

CHANGELOG.md, data/Record.js, data/Store.js, data/impl/RecordSet.js
=> Tighten up freezing of records.

CHANGELOG.md, admin/App.js, core/AppSpec.js, desktop/appcontainer/AppContainer.js
Couldn't take these annoying context menus popping up everywhere.
If you agree, please merge.
Merge also related toolbox branch. …
=> Support for showBrowserContextMenu

CHANGELOG.md, cmp/grid/GridModel.js
+ Along with `showColumn()` and `hideColumn()` convenience methods. …
=> Add GridModel.setColumnVisible() method

admin/differ/DifferModel.js, admin/tabs/activity/tracking/ActivityTrackingModel.js, cmp/filter/FilterChooserModel.js, cmp/filter/impl/FilterChooserFieldSpec.js, cmp/store/impl/StoreFilterFieldImplModel.js, data/Store.js, data/cube/Query.js, data/filter/FieldFilter.js, data/filter/Filter.js, data/filter/FilterModel.js, data/filter/FunctionFilter.js, desktop/cmp/filter/FilterChooser.js
=> Filter model tweaks

cmp/filter/FilterChooserModel.js, data/filter/CompositeFilter.js, data/filter/CompoundFilter.js, data/filter/FieldFilter.js, data/filter/FilterModel.js, data/filter/Utils.js, data/index.js
+ Add CompositeFilter.
+ FieldFilter always takes a single value.
=> CompositeFilter

CHANGELOG.md, utils/datetime/LocalDate.js, utils/js/Decorators.js
+ Add methods/getters for start/end of month.
+ Add internal map to cache getter/method returns that are immutable for a given instance.
+ JsDoc return types. …
=> LocalDate - additional getters/caching/docs

admin/tabs/activity/clienterrors/ClientErrorsModel.js, admin/tabs/activity/tracking/ActivityTrackingModel.js, cmp/filter/FilterChooserFieldSpec.js, cmp/filter/FilterChooserModel.js, cmp/filter/impl/Option.js, cmp/filter/impl/QueryEngine.js, data/filter/FieldFilter.js, desktop/cmp/filter/FilterChooser.js
- [x ] Caught up with `develop` branch as of last change. …
=> FilterChooser enhancements, support for is empty

desktop/cmp/input/CodeInput.js, desktop/cmp/input/CodeInput.scss
=> Rationalize CodeInput's use of flex.

CHANGELOG.md, admin/tabs/activity/feedback/FeedbackPanel.js, admin/tabs/general/configs/ConfigModel.js, admin/tabs/logging/LogLevelPanel.js, admin/tabs/preferences/PreferenceModel.js, admin/tabs/preferences/UserPreferencePanel.js, desktop/cmp/input/CodeInput.js, desktop/cmp/input/CodeInput.scss, desktop/cmp/rest/RestGridModel.js, desktop/cmp/rest/impl/RestForm.js, desktop/cmp/rest/impl/RestForm.scss, desktop/cmp/rest/impl/RestFormField.js, desktop/cmp/rest/impl/RestFormModel.js
+ Source default editor label from displayName property on store field.
+ Update admin rest editors to remove use of undocumented label property in editor configs.
+ Enable search/toolbar on JsonInput by default, make input larger.
+ Make rest editor dialog larger by default, responsive to screen size, and allow scrolling internally if needed.
+ Use BEM conventions for codeInput implementation CSS classes.
button below to indicate it …
=> Rest editor updates

core/ExceptionHandler.js
+ Allow errors to be thrown with requireReload:true to be picked up as such by standard exception handling. …
=> ExceptionHandler supports Error.requireReload

CHANGELOG.md, admin/AppModel.js, admin/tabs/preferences/JsonBlobPanel.js, admin/tabs/preferences/PreferencesTab.js, core/XH.js, svc/JsonBlobService.js, svc/index.js
See hoist-core PR here: https://github.com/xh/hoist-core/pull/165 …
=> JsonBlobService

svc/JsonBlobService.js
Further tweaks from CR with Lee
See https://github.com/xh/hoist-core/pull/167
> …
=> JsonBlobService tweaks pt2

CHANGELOG.md, desktop/cmp/input/DateInput.js
=> Harden DateInput

static/bootstrap.js, static/index.html
See issue #2062.
See corresponding hoist-dev-utils PR here: https://github.com/xh/hoist-dev-utils/pull/27 …
=> Move inline scripts into standalone file.

CHANGELOG.md, cmp/grid/GridModel.js, cmp/grid/impl/GridPersistenceModel.js
=> Add support for GridModelPersistOptions.legacyStateKey

admin/tabs/preferences/JsonBlobPanel.js, svc/JsonBlobService.js
+ Listing JsonBlobs on the client supports specifying owner(s)
+ Creating JsonBlobs on the client supports specifying owner
See hoist-core PR: https://github.com/xh/hoist-core/pull/168 …
=> JsonBlob Owners

desktop/cmp/filter/FilterChooser.js
Be more explicit regarding which of Select's PropTypes are actually supported by FilterChooser.
Give FilterChooser a default filter left icon. …
=> Audit FilterChooser PropTypes

cmp/grid/GridModel.js
=> GridModel checks isReady before reading selection

CHANGELOG.md, desktop/cmp/filter/FilterChooser.js
This PR addresses: https://github.com/xh/hoist-react/issues/2088
- [ N/A ] Reviewed and tested on Mobile, or determined not required.
- [ N/A  ] Created Toolbox branch / PR, or determined not required.
> collapse multiple intermediate commits into a single commit representing …
=> Add disabled prop to FilterChooser

admin/tabs/preferences/JsonBlobPanel.js, svc/JsonBlobService.js
+ Implement ACL in JsonBlobService
+ Remove JsonBlob.valueLastUpdated
See hoist-core PR: https://github.com/xh/hoist-core/pull/169 …
=> JsonBlob ACL

CHANGELOG.md, admin/tabs/general/services/ServiceModel.js, admin/tabs/general/services/ServicePanel.js, cmp/ag-grid/AgGridModel.js, cmp/grid/Grid.js, cmp/grid/GridModel.js, desktop/cmp/filechooser/FileChooser.js, desktop/cmp/filechooser/FileChooserModel.js
This PR addresses https://github.com/xh/hoist-react/issues/1263
Updated Toolbox in https://github.com/xh/toolbox/pull/428 …
=> Hide headers grid config

CHANGELOG.md, admin/tabs/activity/tracking/ActivityTrackingModel.js, cmp/form/FormModel.js
I love this little method!  Can't believe we did not add this earlier
> single …
=> New method: FormModel.setValues

CHANGELOG.md, cmp/grid/columns/Column.js, cmp/grid/impl/ColumnHeader.js
=> Fix regression in headerValueGetter caused by PR #2085

admin/differ/Differ.js, admin/differ/DifferModel.js, admin/tabs/general/configs/ConfigModel.js, admin/tabs/preferences/JsonBlobModel.js, admin/tabs/preferences/JsonBlobPanel.js, admin/tabs/preferences/PreferenceModel.js
See hoist-core PR: https://github.com/xh/hoist-core/pull/170 …
=> Add remote diff functionality to JsonBlob admin

admin/tabs/preferences/JsonBlobModel.js, admin/tabs/preferences/JsonBlobPanel.js, svc/JsonBlobService.js
See hoist-core PR: https://github.com/xh/hoist-core/pull/171 …
=> Add UUID column to JsonBlobs

admin/tabs/userData/JsonBlobModel.js, svc/JsonBlobService.js
See hoist-core PR: https://github.com/xh/hoist-core/pull/173 …
=> Add 'archived' flag to JsonBlob

CHANGELOG.md, cmp/ag-grid/AgGrid.scss, styles/vars.scss
=> Use flexbox to vertically center cell contents.

CHANGELOG.md, appcontainer/MessageModel.js, appcontainer/MessageSourceModel.js, core/XH.js
=> + Add support for messageKey

CHANGELOG.md, cmp/tab/TabContainerModel.js, cmp/tab/TabModel.js, desktop/cmp/tab/impl/Tab.js, desktop/cmp/tab/impl/TabContainer.js, mobile/cmp/tab/impl/Tab.js, mobile/cmp/tab/impl/TabContainer.js, utils/react/ReactUtils.js
See also: https://github.com/xh/toolbox/pull/430 …
=> Dynamic Tabs for TabContainer

CHANGELOG.md, desktop/cmp/input/Select.js, mobile/cmp/input/Select.js
=> Add new Select.menuWidth prop

cmp/tab/TabContainerModel.js, cmp/tab/TabModel.js
Minor tweaks from usage of dynamic tabs
+ Remove Tab should take a TabModel.
> …
=> Enhance tab container

desktop/cmp/dash/impl/DashContainerUtils.js
See issue https://github.com/xh/hoist-react/issues/2126 …
=> Round relative sizes to 2dp in DashContainer state.

utils/datetime/LocalDate.js
Adds `isStartOfQuarter`, `startOfQuarter()`, `isEndOfQuarter`, `endOfQuarter()` to `LocalDate` …
=> LocalDate quarter handling

desktop/cmp/input/Checkbox.js, desktop/cmp/input/SwitchInput.js
This PR addresses https://github.com/xh/hoist-react/issues/2138
- [N/R] Added CHANGELOG entry, or determined not required. …
=> Update prop type to include element for switchInput and checkbox labels

desktop/cmp/dash/DashContainerModel.js
See Toolbox PR: https://github.com/xh/toolbox/pull/434
See issue: https://github.com/xh/hoist-react/issues/2136 …
=> Improve DashContainer state documentation and example

CHANGELOG.md, admin/differ/DifferModel.js, admin/tabs/userData/JsonBlobModel.js
+ Add archivedDate to JsonBlob
+ Add unique constraint across name/type/owner/archivedDate
+ Match jsonBlobs diffs using this constraint
+ Fix admin differ id generation
See hoist-core PR: https://github.com/xh/hoist-core/pull/178
> collapse multiple intermediate commits into …
=> JsonBlob - ArchivedDate

CHANGELOG.md, cmp/grid/columns/Column.js
This PR fixes https://github.com/xh/hoist-react/issues/2132 …
=> Column tooltip function fix

CHANGELOG.md, desktop/cmp/button/AppMenuButton.js, mobile/cmp/header/AppMenuModel.js
Wasn't 100% sure where this item should go in the menu, ended up putting it just before the Logout item, so should be the last item in SSO environments which seemed the most appropriate for where you usually expect an about item to be. …
=> Add about item to app menus

desktop/cmp/dash/DashContainerModel.js
Tweak to docs per https://github.com/xh/hoist-react/commit/1ac46fae3b94f549ce3531642ffa1f2b7bdb2182
=> Tweak docs

desktop/cmp/tab/Tabs.scss
See issue: https://github.com/xh/hoist-react/issues/2158 …
=> Fix close tab button styling

admin/tabs/activity/tracking/ActivityTrackingModel.js, cmp/grid/Grid.js, cmp/grid/Grid.scss, cmp/grid/GridModel.js, cmp/grid/enums/TreeStyle.js, cmp/grid/index.js, core/index.js
=> Move TreeStyle enum to grid package, simplify names, default to highlights

admin/tabs/userData/JsonBlobModel.js, svc/JsonBlobService.js
See hoist-core PR: https://github.com/xh/hoist-core/pull/179 …
=> Add JsonBlob meta column

CHANGELOG.md, admin/App.scss, admin/AppModel.js, admin/tabs/activity/ActivityTab.js, admin/tabs/general/GeneralTab.js, admin/tabs/logging/LoggingTab.js, admin/tabs/monitor/MonitorTab.js, admin/tabs/userData/UserDataTab.js, cmp/tab/TabContainer.js, cmp/tab/TabContainerModel.js, cmp/tab/TabModel.js, desktop/cmp/tab/TabSwitcher.js, desktop/cmp/tab/Tabs.scss, desktop/cmp/tab/impl/TabContainer.js, kit/blueprint/styles.scss, mobile/cmp/tab/impl/TabContainer.js, utils/react/Hooks.js
A proposed solution based on Intellij IDE behaviour.
See issue: https://github.com/xh/hoist-react/issues/2144
See toolbox PR: https://github.com/xh/toolbox/pull/440
> change. This …
=> TabSwitcher Enhancements

desktop/cmp/tab/TabSwitcher.js, desktop/cmp/tab/Tabs.scss
See issue: https://github.com/xh/hoist-react/issues/2171 …
=> Allow TabSwitcher to overflow when in a flex container.

cmp/grid/Grid.scss, styles/vars.scss
=> Summary row gets hightlighted in all grids, Fixes #2163

desktop/cmp/tab/TabSwitcher.js
=> Add LayoutProps support to TabSwitcher.

desktop/cmp/input/Select.js
See issue https://github.com/xh/hoist-react/issues/2095 …
=> Ensure Select's input value is synced if internal value changes while focused

CHANGELOG.md, cmp/layout/Placeholder.js, cmp/layout/Placeholder.scss, cmp/layout/index.js
See Toolbox PR: https://github.com/xh/toolbox/pull/442 …
=> Add Placeholder component with standardized styling

desktop/cmp/rest/RestGridModel.js, desktop/cmp/rest/data/RestField.js, desktop/cmp/rest/impl/RestFormField.js, desktop/cmp/rest/impl/RestFormModel.js
+ Add assorted doc comments and member type hints on related classes.
+ Fixes #2134
+ Alternate approach to PR #2184 …
=> Skip empty readonly RestEditor fields when adding

cmp/grid/columns/Column.js
=> Fix Summary record handling in tooltip

desktop/cmp/input/Select.js
=> Don't apply default Select.filterFn in async mode

desktop/cmp/input/CodeInput.js
Ensure CodeInput cmp receives sizing and className. …
=> CodeInput Regression Fix

desktop/cmp/panel/PanelModel.js
=> Panels should not persist state that is not dynamic.

CHANGELOG.md, cmp/grid/GridModel.js
This PR closes issue https://github.com/xh/hoist-react/issues/2194
- [NR] Updated doc comments / prop-types, or determined not required.
- [NR] Reviewed and tested on Mobile, or determined not required.
- [NR ] Created Toolbox branch / PR, or determined not required.
> …
=> Autosize empty text fix

CHANGELOG.md, data/Field.js, package.json, yarn.lock
+ Sanitize incoming String content to defend against possible XSS attacks or other issues with malformed HTML or scripting content before it is rendered into grids or other components …
=> Call DOMPurify within parseFieldValue

CHANGELOG.md, cmp/grid/GridModel.js, cmp/grid/columns/ColumnGroup.js
=> Add `lockColumnGroups` config to `GridModel`

CHANGELOG.md, desktop/cmp/grid/impl/ColChooser.js, desktop/cmp/grid/impl/ColChooserModel.js, desktop/cmp/leftrightchooser/LeftRightChooserFilter.js, desktop/cmp/leftrightchooser/impl/Description.js
+ Fix filter function in leftRightChooserFilter
+ Fix regression in description component of leftRightChooser
This PR closes: https://github.com/xh/hoist-react/issues/2242
Add example in toolbox PR: https://github.com/xh/toolbox/pull/460
button below to indicate it is not ready yet for a final …
=> Add group to included fields in colChooser filter

appcontainer/ImpersonationBarModel.js, desktop/appcontainer/AppContainer.js, desktop/appcontainer/ImpersonationBar.js, svc/IdentityService.js
Tweak to impersonation to avoid disconcerting appearance in menu when impersonating non-admins …
=> Impersonation UI tweak

core/HoistComponentFunctional.js
+ Code now obeys "rules of hooks" …
=> Commenting/cleanup to HoistComponent implementation

CHANGELOG.md, data/cube/BucketSpec.js, data/cube/Cube.js, data/cube/View.js, data/cube/impl/AggregateRow.js, data/cube/impl/BucketRow.js
Toolbox branch: https://github.com/xh/toolbox/tree/cubeRowBucketing (not a great example so not sure if we want to merge) …
=> Cube row bucketing

cmp/grid/GridModel.js
Track grid autosize with short debug for timing info on completion
button below to …
=> Track grid autosizing with short debug

cmp/form/Form.js, core/HoistComponent.js, desktop/cmp/form/FormField.js, desktop/cmp/panel/Panel.js, desktop/cmp/panel/impl/ResizeContainer.js, mobile/cmp/dialog/Dialog.js, mobile/cmp/form/FormField.js, mobile/cmp/header/AppBar.js, mobx/index.js, package.json, yarn.lock
+ explicitly use mobx-react-lite, preparing for future removal of mobx-react
- [X ] Caught up with `develop` branch as of last change. …
=> + Update to our non-deprecated use of observer.

cmp/grid/Grid.js, mobile/cmp/panel/Panel.js
=> Add missing forwardRefs

cmp/grid/columns/Column.js, cmp/grid/impl/ColumnHeader.js
=> Harden sorting

CHANGELOG.md, mobile/cmp/button/ExpandCollapseButton.js, mobile/cmp/button/index.js
See issue: https://github.com/xh/hoist-react/issues/2267
See toolbox PR: https://github.com/xh/toolbox/pull/462 …
=> Added mobile ExpandCollapseButton. #2267

CHANGELOG.md, cmp/dock/DockViewModel.js, cmp/tab/TabModel.js, desktop/cmp/dash/DashViewSpec.js, mobile/cmp/menu/MenuButton.js, mobile/cmp/menu/impl/Menu.js, mobile/cmp/menu/impl/Menu.scss, mobile/cmp/navigator/PageModel.js, mobile/cmp/popover/Popover.js, mobile/cmp/popover/Popover.scss, mobile/cmp/popover/index.js, styles/vars.scss, utils/react/ReactUtils.js
+ Use Popover to implement mobile MenuButton.
See issue: https://github.com/xh/hoist-react/issues/2266
See Toolbox PR: https://github.com/xh/toolbox/pull/463 …
=> Add Popover to mobile toolkit.

CHANGELOG.md, desktop/cmp/panel/Panel.js, desktop/cmp/panel/PanelModel.js
=> When uncollapsing panel restore default size.

data/cube/View.js
=> Detect View dimension changes when updating

mobile/cmp/menu/MenuButton.js, mobile/cmp/menu/impl/Menu.js, mobile/cmp/menu/impl/Menu.scss
See issue: https://github.com/xh/hoist-react/issues/2280
See Toolbox PR: https://github.com/xh/toolbox/pull/464 …
=> Add `title` prop to mobile MenuButton.

mobile/cmp/header/AppMenuButton.js, mobile/cmp/popover/Popover.js
=> Add popoverClassName prop to mobile Popover

CHANGELOG.md, cmp/grid/GridModel.js, data/Store.js
=> Store fixes/enhancements

desktop/cmp/input/DateInput.js
=> Pass 'boundary' prop through dateInput to date picker popover

mobile/cmp/menu/MenuButton.js, mobile/cmp/popover/Popover.js
=> Allow disabling mobile Popover / MenuButton

CHANGELOG.md, data/Field.js
=> Improve parsing of integers in Field

CHANGELOG.md, cmp/dataview/DataView.js, cmp/dataview/DataViewModel.js
See issue https://github.com/xh/hoist-react/issues/2196 …
=> DataView accepts a function for itemHeight

cmp/grid/Grid.js, cmp/grid/GridModel.js, cmp/grid/columns/Column.js
=> Ensure 'pinned' and 'hidden' are well-defined types

desktop/cmp/treemap/TreeMapModel.js
=> Fix TreeMap -> Grid selection syncing

CHANGELOG.md, desktop/appcontainer/AppContainer.js, desktop/hooks/UseHotkeys.js, kit/blueprint/index.js, package.json, yarn.lock
Also able to cleanup some hacky usage of Blueprint, in favor of a simple usage of the new public API -- sweet. …
=> Blueprint upgrade

CHANGELOG.md, admin/tabs/general/websocket/WebSocketModel.js, core/HoistModel.js, core/HoistService.js, core/index.js, core/refresh/LoadSpec.js, core/refresh/LoadSupport.js
=> New Class for LoadSpec, with additional properties

desktop/cmp/treemap/TreeMapModel.js
We don't want to and are unable to consider non-numerical values. …
=> Only consider valid numerical heat values when calculating TreeMap heat colors

desktop/cmp/treemap/SplitTreeMap.js, desktop/cmp/treemap/TreeMap.js, desktop/cmp/treemap/TreeMap.scss, desktop/cmp/treemap/TreeMapModel.js
+ Treat invalid heat values as zero (i.e. grey)
+ Skip invalid values in tooltip
+ Allow custom renderers for `value` and `heat` values
+ Use standard placeholder component
+ Use standard errorMessage component …
=> TreeMap enhancements

CHANGELOG.md, data/Store.js
+ Setup changelog entry for v38.1.1 …
=> Add Store.fieldDefaults config

data/Store.js, data/cube/Cube.js
+ Matching same config recently added to Store.
> single commit should be *rebased* …
=> Add new Cube.fieldDefaults config

CHANGELOG.md, cmp/grid/Grid.js, data/Store.js, data/impl/RecordSet.js, desktop/cmp/rest/RestGridModel.js, desktop/cmp/rest/data/RestStore.js, svc/AutoRefreshService.js, utils/async/AsyncUtils.js, utils/js/WithDebug.js
=> Store performance

CHANGELOG.md, data/Record.js, data/Store.js, data/impl/RecordSet.js, svc/AutoRefreshService.js
=> Store perf2

mobile/cmp/grouping/GroupingChooser.js, mobile/cmp/grouping/GroupingChooser.scss
The mobile part of https://github.com/xh/hoist-react/issues/2291 …
=> Add `popoverMinHeight` to mobile GroupingChooser, and implement `popoverWidth`

data/Store.js
=> Make Stores safe to create pre-XH.init

CHANGELOG.md, cmp/dataview/DataViewModel.js, cmp/grid/GridModel.js, data/StoreSelectionModel.js
=> Selected record

CHANGELOG.md, svc/AutoRefreshService.js, utils/async/AsyncUtils.js
=> Stop Auto-Refresh when document hidden + related Async tweaks

desktop/cmp/treemap/SplitTreeMapModel.js, desktop/cmp/treemap/TreeMap.js, desktop/cmp/treemap/TreeMapModel.js
+ Related and Unrelated tweaks
=> Fix overeager scrolling in TreeMap/Grid combo.  Related TreeMap cleanups

CHANGELOG.md, admin/tabs/activity/tracking/charts/ChartsModel.js, cmp/chart/ChartModel.js
=> More convenient method to update ChartModel

CHANGELOG.md, svc/FetchService.js
=> FetchService.defaultTimeout

cmp/grid/Grid.js
See issue: https://github.com/xh/hoist-react/issues/2341 …
=> Resize flex columns upon ColumnState change.

CHANGELOG.md, desktop/cmp/toolbar/Toolbar.js, desktop/cmp/toolbar/Toolbar.scss, styles/vars.scss
See issue: https://github.com/xh/hoist-react/issues/2333
See Toolbox PR: https://github.com/xh/toolbox/pull/470 …
=> Add `compact` prop to Toolbar

desktop/cmp/panel/impl/PanelHeader.scss
=> Ensure collapsed vertical panel title aligned properly, Fixes: #2335

core/refresh/LoadSpec.js, exception/Stringify.js, utils/js/LangUtils.js
=> Restore minimal loadSpec for output purposes

cmp/grid/GridModel.js
Add `omit` property to column, supporting boolean and function forms.
> single …
=> Support `Column.omit` in GridModel

CHANGELOG.md, desktop/cmp/rest/RestGrid.js, desktop/cmp/rest/impl/RestForm.js
=> Add formClassName prop to RestGrid to be passed to form

cmp/grid/GridModel.js, cmp/grid/columns/ColumnGroup.js
Fixes a potential NPE when attempting to validate columns. …
=> Recursively omit ColumnGroups with all children omitted.

desktop/cmp/treemap/TreeMapModel.js
=> Clarify and split colorMode handling in TreeMap to improve readability.

desktop/cmp/error/ErrorMessage.scss, mobile/cmp/error/ErrorMessage.scss
Allow ErrorMessages to break long words if necessary (i.e. server class names in exception messages) …
=> ErrorMessages can break long words
