xh/hoist-react

cmp/layout/TileFrame.scss
See issue: https://github.com/xh/hoist-react/issues/2378 …
=> Overlay the TileFrame scrollbar so that it doesn't take up width

CHANGELOG.md, admin/tabs/config/ConfigTabModel.js, admin/tabs/logging/LogLevelPanel.js, admin/tabs/monitor/MonitorEditorPanel.js, admin/tabs/userData/JsonBlobModel.js, admin/tabs/userData/PreferenceModel.js, admin/tabs/userData/UserPreferencePanel.js
+ Unrelated tweak to avoid displaying misleading archiveDate on JSONBlob editor form when not set (date in that case is serialized as 0, parsed to 1/1/1970). …
=> Disable XSS protection on Admin RESTEditorGrids

cmp/tab/TabContainerModel.js
+ Restore last active tab when removing active tab.
+ Related cleanup of removeTab() method …
=> Improve TabContainer behavior when active tab removed

CHANGELOG.md, appcontainer/AboutDialogModel.js, appcontainer/AppContainerModel.js, appcontainer/ChangelogDialogModel.js, core/XH.js, desktop/appcontainer/AboutDialog.js, desktop/appcontainer/AppContainer.js, desktop/appcontainer/ChangelogDialog.js, desktop/appcontainer/ChangelogDialog.scss, desktop/cmp/appbar/AppBar.js, desktop/cmp/button/AppMenuButton.js, desktop/cmp/button/WhatsNewButton.js, svc/ChangelogService.js, svc/index.js, utils/js/VersionUtils.js
Will require merging and release of https://github.com/xh/hoist-dev-utils/pull/31
You can demo with current Toolbox `develop` branch - specify `"@xh/hoist-dev-utils": "6.0.0-SNAPSHOT.1617838130290"` in your devDependencies and run against this branch inline.
To test support for highlighting notes on unread latest version via "What's new?" button, ensure your local DB has a string pref `xhLastReadChangelog` - I have optimistically added to toolbox-dev DB.
**If your change is still a WIP**, please use the "Create draft pull …
=> Changelog support

CHANGELOG.md, core/ExceptionHandler.js, core/XH.js
=> Add XH.showException()

CHANGELOG.md, desktop/cmp/button/Button.scss, desktop/cmp/input/CodeInput.js, desktop/cmp/input/CodeInput.scss, desktop/cmp/toolbar/Toolbar.scss, kit/blueprint/styles.scss
=> Code input tweaks

CHANGELOG.md, format/FormatDate.js, format/FormatMisc.js, format/FormatNumber.js, format/FormatUtils.js
=> Clean formatters

CHANGELOG.md, appcontainer/ExceptionDialogModel.js, core/ExceptionHandler.js, exception/Stringify.js
=> Exception stringify

CHANGELOG.md, appcontainer/MessageSourceModel.js, desktop/cmp/error/ErrorMessage.js, mobile/cmp/error/ErrorMessage.js
=>  ErrorPanel should try to get error from context model

CHANGELOG.md, desktop/cmp/treemap/SplitTreeMapModel.js, desktop/cmp/treemap/TreeMapModel.js
Add maxHeat config to TreeMap and SplitTreeMap.
See issue: https://github.com/xh/hoist-react/issues/1316
See Toolbox PR: https://github.com/xh/toolbox/pull/477 …
=> Tree map colors

mobile/cmp/grid/impl/ColChooser.js, mobile/cmp/grid/impl/ColChooserModel.js
=> After restoring defaults, close mobile col chooser

desktop/cmp/grid/editors/HoistInlineEditorModel.js, desktop/cmp/grid/editors/InlineEditors.scss, desktop/cmp/grid/editors/InlineSelectEditor.js, desktop/cmp/grid/editors/index.js
See Toolbox PR: https://github.com/xh/toolbox/pull/479
=> Add InlineSelectEditor

CHANGELOG.md, core/HoistComponent.js
=> Add support for 'modelRef' prop on all hoist components

mobile/appcontainer/OptionsDialog.js, mobile/cmp/button/RestoreDefaultsButton.js, mobile/cmp/button/index.js
See issue: https://github.com/xh/hoist-react/issues/2446 …
=> Add RestoreDefaultsButton to mobile options dialog.

CHANGELOG.md, desktop/cmp/button/AppMenuButton.js, desktop/cmp/button/ColChooserButton.js
=> Fix disabled property for buttons that use popover.

cmp/grid/Grid.js
=> Context menu should respect agOption 'suppressRowClickSelection'

utils/datetime/LocalDate.js
=> LocalDate.get() and LocalDate.from() should be nil-safe

format/FormatDate.js
Went back and forth about doing the logic in the parameter default, but it seemed to be that if you ever would, this would be the time. …
=> fmtCompactDate should support LocalDate.

cmp/layout/TileFrame.js, cmp/layout/TileFrame.scss
Tom -- for your review/discussion.  
Would like to understand a tiny bit more about the algorithm.  Are there any links to the source of the scoring heuristic?
+ Simplify docs
+ More vertical/horizontal symmetry
~+ Change to defaults suggested by ATM.~ …
=> TileFrame tweaks

CHANGELOG.md, admin/tabs/activity/tracking/ActivityTrackingModel.js, cmp/form/FormModel.js, cmp/form/field/BaseFieldModel.js, cmp/form/field/SubformsFieldModel.js, utils/js/LangUtils.js
=> Improve behavior of FormModel.init()

CHANGELOG.md, admin/differ/Differ.js, admin/differ/DifferModel.js, admin/tabs/activity/tracking/ActivityTrackingModel.js, admin/tabs/activity/tracking/ActivityTrackingView.js, cmp/dataview/DataView.js, cmp/dataview/DataViewModel.js, cmp/grid/Grid.js, cmp/grid/GridModel.js, desktop/cmp/leftrightchooser/LeftRightChooser.js, desktop/cmp/leftrightchooser/LeftRightChooserModel.js, desktop/cmp/rest/RestGrid.js, desktop/cmp/rest/RestGridModel.js
See matching toolbox PR.
Also, discussed with Lee, we will double check the mobile grids after merge. …
=> Grid cmp callbacks

CHANGELOG.md
=> Improve CL entry WRT model lookups

cmp/grid/columns/Column.js
=> Fix to restore tooltips for ag-Grid update

desktop/cmp/grid/editors/DateEditor.js, desktop/cmp/grid/editors/SelectEditor.js, desktop/cmp/grid/editors/TextAreaEditor.js, desktop/cmp/grid/editors/impl/InlineEditorModel.js, desktop/cmp/input/DateInput.js
=> Date input fix

desktop/cmp/grid/editors/DateEditor.js, desktop/cmp/grid/editors/SelectEditor.js, desktop/cmp/grid/editors/TextAreaEditor.js, desktop/cmp/grid/editors/impl/InlineEditorModel.js, desktop/cmp/input/DateInput.js
=> Revert "Date input fix"

CHANGELOG.md, svc/GridExportService.js
=> Fixes to exportService

CHANGELOG.md, cmp/grid/Grid.js, cmp/grid/GridModel.js, core/XH.js, core/refresh/LoadSupport.js, data/Store.js, desktop/cmp/treemap/TreeMap.js, utils/js/Decorators.js, utils/js/WithDebug.js
+ new @logWithDebug annotation
+ simplify WithDebug() to always do short messages
+ Tighten console tracking messages …
=> Client-side log/performance tracing cleanup/enhancement

cmp/grid/Grid.js
=> Grid context menu "suppressRowClickSelection" means don't manipulate selection

CHANGELOG.md, core/AppSpec.js, data/Field.js
+ One-stop flag to disable Field-level XSS protection by default within an app.
> …
=> Add AppSpec.disableXssProtection config

data/cube/View.js, utils/impl/Equals.js, utils/impl/index.js
=> Column filters performance

cmp/grid/GridModel.js, data/Record.js, data/Store.js, data/StoreSelectionModel.js, data/impl/RecordFieldValidator.js, data/impl/RecordValidator.js, data/impl/StoreValidator.js, desktop/cmp/treemap/TreeMapModel.js
+ Define convenience typedefs for:
- `RecordId`
- `RecordOrId`
- `StoreErrorMap`
- `RecordErrorMap` …
=> JsDoc updates in data package

CHANGELOG.md, desktop/cmp/panel/impl/PanelHeader.scss
=> Panel headerItems minimal button intent

CHANGELOG.md, cmp/layout/Placeholder.scss
+ If first child of placeholder is an icon, render 4x size with reduced opacity.
> …
=> Style first-child icon within placeholder

desktop/cmp/treemap/TreeMap.js
=> Tree map dark theme

CHANGELOG.md, cmp/form/field/BaseFieldModel.js, data/impl/RecordFieldValidator.js, data/validation/Rule.js
=> Enhance state passed to constraints in validation API

cmp/grid/Grid.scss, cmp/grid/columns/Column.js, cmp/grid/impl/ColumnHeader.js
See matching toolbox PR
- icon defaults to enabled
- hover color added for desktop  …
=> Tree grid header expand/collapse all icon defaults to enabled

CHANGELOG.md, cmp/chart/Chart.scss, kit/blueprint/styles.scss
=> Chart navigator in dialog

CHANGELOG.md, cmp/grid/columns/Column.js, utils/react/ReactUtils.js
=> Inline grid editor supports jsx components

CHANGELOG.md, svc/FetchService.js
=> Abort Fetch after timeout

CHANGELOG.md, cmp/grid/Grid.js, cmp/grid/GridModel.js
=> GridModel.clicksToEdit implemented.

CHANGELOG.md, appcontainer/MessageSourceModel.js, appcontainer/ToastModel.js, appcontainer/ToastSourceModel.js, core/XH.js, desktop/appcontainer/ToastSource.js, svc/GridExportService.js
+ expose ToastModel
+ improve toasting and display of exceptions from GridExportService
+ misc cleanup …
=> Programmatic dismissal of Toast/Improve Export messaging

CHANGELOG.md, cmp/grid/GridModel.js, svc/GridAutosizeService.js
+ Improves autosizeAsync performance on large tree grids by excluding collapsed children
Resolves #2541  …
=> Add GridAutosizeOptions.includeCollapsedChildren config

CHANGELOG.md, admin/tabs/activity/tracking/ActivityTrackingModel.js, data/cube/Cube.js, data/cube/Query.js, data/cube/View.js
=> Restore Synchronous view computation

cmp/chart/Chart.js
Can be tested on the pieChart in this branch:
https://github.com/xh/toolbox/tree/pieChart
which has a "view in full screen" menu option.
Noticed on client app which has this menu option that full screen opens a small chart in corner of black screen. …
=> BugFix: restore highcharts fullscreen display ability.

CHANGELOG.md, admin/tabs/activity/clienterrors/ClientErrorsModel.js, core/ExceptionHandler.js, package.json
Closes #2462
Should be merged with matching PR in hoist-core: https://github.com/xh/hoist-core/pull/203 …
=> Include full URL with client error reports

mobile/cmp/navigator/impl/swipe/BackIndicator.js, mobile/cmp/navigator/impl/swipe/RefreshIndicator.js, mobile/cmp/navigator/impl/swipe/Swiper.js, mobile/cmp/navigator/impl/swipe/Swiper.scss
+ Render indicators into a Portal to ensure displayed above other components
+ Tweak CSS names to reflect component name as per BEM …
=> Swipe gesture tweaks

core/TaskObserver.js
=> Add `pendingTaskCount` getter to TaskObserver

core/persist/PersistenceProvider.js
See issue: https://github.com/xh/hoist-react/issues/2584 …
=> Add PersistOptions typedef.

CHANGELOG.md, cmp/badge/Badge.js, cmp/badge/Badge.scss
=> Badge component has compact prop

desktop/cmp/grouping/GroupingChooser.js, desktop/cmp/grouping/GroupingChooser.scss, mobile/cmp/grouping/GroupingChooser.js, mobile/cmp/grouping/GroupingChooser.scss
+ Use underline and cursor to show editability of level labels.
+ Always enable selects, even when all levels selected.
See issue https://github.com/xh/hoist-react/issues/2598
> …
=> Indicate editability in GroupingChooser.

CHANGELOG.md, cmp/websocket/WebSocketIndicator.js, desktop/cmp/filter/FilterChooser.js, desktop/cmp/grouping/GroupingChooser.js, icon/Icon.js
See issue: https://github.com/xh/hoist-react/issues/2600
See toolbox PR: https://github.com/xh/toolbox/pull/520 …
=> Icon factories take an intent config

CHANGELOG.md, cmp/form/Form.js
=> Fix form field label

CHANGELOG.md, desktop/cmp/treemap/SplitTreeMapModel.js, desktop/cmp/treemap/TreeMap.js, desktop/cmp/treemap/TreeMapModel.js
See Toolbox PR: https://github.com/xh/toolbox/pull/521 …
=> Tree map `theme` config

CHANGELOG.md, appcontainer/AppContainerModel.js, appcontainer/SizingModeModel.js, cmp/ag-grid/AgGridModel.js, cmp/grid/Grid.js, cmp/grid/GridAutosizeMode.js, cmp/grid/GridModel.js, core/XH.js, core/enums/SizingMode.js, core/index.js, desktop/cmp/appOption/AutoRefreshAppOption.js, desktop/cmp/appOption/SizingModeAppOption.js, desktop/cmp/appOption/ThemeAppOption.js, desktop/cmp/appOption/index.js, desktop/cmp/grid/impl/filter/values/ValuesTabModel.js, mobile/cmp/appOption/AutoRefreshAppOption.js, mobile/cmp/appOption/SizingModeAppOption.js, mobile/cmp/appOption/ThemeAppOption.js, mobile/cmp/appOption/index.js
+ Add observable XH.sizingMode
+ Persist this with built-in preference
+ Use as default sizing mode in GridModel
+ GridModel.sizingMode reacts to changes to the global sizing mode
+ GridModel autosizes upon changing the sizing mode
See issue: https://github.com/xh/hoist-react/issues/1889
See hoist-core PR: https://github.com/xh/hoist-core/pull/205
See toolbox PR: https://github.com/xh/toolbox/pull/518
button below to indicate it is …
=> Build in support for sizingMode

CHANGELOG.md, admin/tabs/activity/tracking/detail/ActivityDetailModel.js
=> Activity tracker displays name of user being impersonated

CHANGELOG.md, appcontainer/SizingModeModel.js
See hoist-core PR: https://github.com/xh/hoist-core/pull/206 …
=> Use JSON for xhSizingMode preference, keyed by platform

desktop/cmp/appOption/AutoRefreshAppOption.js, desktop/cmp/appOption/SizingModeAppOption.js, desktop/cmp/appOption/ThemeAppOption.js, mobile/cmp/appOption/AutoRefreshAppOption.js, mobile/cmp/appOption/SizingModeAppOption.js, mobile/cmp/appOption/ThemeAppOption.js
=> Additional config for preset AppOption controls

CHANGELOG.md, mobile/cmp/navigator/impl/swipe/Swiper.js
=> Disable swipe to refresh/go back on mobile charts to allow for dragging

cmp/filter/FilterChooserModel.js
The "pure" stringified value was temporarily flashing, due to the Select control not having access to a corresponding option with a label. …
=> Fix display of FilterChooser tags during transition between values

desktop/cmp/grid/impl/filter/values/ValuesTabModel.js
Fixes: https://github.com/xh/hoist-react/issues/2617 …
=> Ensure values in column filter Values Tab are unique

svc/GridExportService.js
=> Tweak to remove weird _sortOrder dependency

CHANGELOG.md, core/HoistAppModel.js, core/XH.js
=> Make restoreDefaultsAsync() overrideable

CHANGELOG.md, desktop/appcontainer/ChangelogDialog.js, desktop/appcontainer/ChangelogDialog.scss, svc/ChangelogService.js
=> Fix: In-app changelog prompt does not appear if category-based filtering results in an empty version

cmp/chart/Chart.scss
=> Ensure tooltips using the 'outside' flag render on top, Fixes: #2622 

cmp/ag-grid/AgGrid.js, core/HoistComponent.js, core/modelspec/uses.js, desktop/cmp/form/FormField.js
=> Model check

CHANGELOG.md, desktop/cmp/tab/Tabs.scss, styles/vars.scss
=> New CSS vars / standardization for desktop tabs

styles/XH.scss
=> Disable user select on tablets, Fixes #2655

admin/differ/Differ.js, admin/differ/DifferModel.js, admin/tabs/config/ConfigTab.js, admin/tabs/config/ConfigTabModel.js, admin/tabs/userData/JsonBlobModel.js, admin/tabs/userData/JsonBlobPanel.js, admin/tabs/userData/PreferenceModel.js, admin/tabs/userData/PreferencePanel.js
=> Add quick filter to admin Differ, and allow parent models to create/destroy DifferModel 

admin/differ/DifferModel.js, cmp/grid/GridModel.js, desktop/appcontainer/ExceptionDialog.js, desktop/cmp/button/RestoreDefaultsButton.js, desktop/cmp/rest/RestGridModel.js, desktop/cmp/rest/impl/RestFormModel.js, mobile/cmp/button/RestoreDefaultsButton.js
=> Tweak restore defaults alert

CHANGELOG.md, cmp/ag-grid/AgGrid.js, desktop/cmp/grid/impl/filter/ColumnHeaderFilter.scss, styles/vars.scss
=> Reduce default grid header heights

cmp/grid/Grid.js, cmp/grid/GridModel.js, cmp/grid/impl/ColumnHeader.js, desktop/cmp/button/ColAutosizeButton.js, desktop/cmp/contextmenu/StoreContextMenu.js, desktop/cmp/grid/impl/colchooser/ColChooserModel.js, mobile/cmp/button/ColAutosizeButton.js, mobile/cmp/grid/impl/ColChooserModel.js
+ autosizeAsync defaults showMask to false
+ Use showMask: true for user-driven autosizes …
=> Autosize masking

CHANGELOG.md, desktop/cmp/input/Select.js, mobile/cmp/input/Select.js
=> Promote react-select maxMenuHeight prop to Select input

CHANGELOG.md, cmp/grid/Grid.scss, styles/vars.scss
+ Wrap tree style colors to support up to 10 levels (as we do with tree highlights)
+ Changelog entry …
=> Tree style tweaks + changelog entry

admin/tabs/logging/viewer/LogDisplay.js, admin/tabs/logging/viewer/LogViewer.scss
=> Prevent Log Viewer from stretching small row counts. Fixes #2687

admin/tabs/logging/viewer/LogDisplay.js, admin/tabs/logging/viewer/LogViewer.scss
=> Fix log view scroll

CHANGELOG.md, cmp/grid/GridModel.js, cmp/grid/columns/Column.js, cmp/grid/impl/ColumnHeader.js
=> Refine default column sorting based field type

CHANGELOG.md, desktop/cmp/grid/editors/impl/InlineEditorModel.js
=> Delay inline editor focus

styles/XH.scss
Tested all input types, quick filter etc on phone and tablet …
=> Fix inputs for mobile and tablets

cmp/grid/GridModel.js, cmp/store/impl/StoreFilterFieldImplModel.js, desktop/cmp/grid/find/GridFindField.js, desktop/cmp/grid/find/GridFindField.scss, desktop/cmp/grid/find/impl/GridFindFieldImplModel.js, desktop/cmp/store/impl/StoreFilterField.js
Suggesting the following changes:
+ Store the value on a specifiable 'model', or the grid itself.  This is what StoreFilterField does, and it's important if you ever want to control/persist this value, but also because local state can easily be "lost" in toolbar controls.  (Toolbar will remount more than it should -- a separate issue).
+ Added keyboard handling for up/down arrow.
+ Stacked the buttons -- looking just to make the thing visually a bit tighter.
+ Hide the buttons when no search in place -- again, looking to make things visually tighter, especially when control is not in use.
+ SelectOnFocus : true, for this control. Don't feel strongly about this, but seemed like generally a worthwhile default.
+ Minor re-org to hide implemenation class …
=> Improvements to GridFindField

CHANGELOG.md, core/refresh/LoadSpec.js, core/refresh/LoadSupport.js
=> Make app meta data first-class object on LoadSpec

desktop/cmp/grid/impl/colchooser/ColChooserModel.js
=> Make ColChooser wider when we are showing all the buttons

desktop/cmp/grid/find/GridFindField.js, desktop/cmp/grid/find/impl/GridFindFieldImplModel.js
=> Show / hide GridFindField controls on focus

CHANGELOG.md, appcontainer/OptionsDialogModel.js
=> Track options

CHANGELOG.md, cmp/ag-grid/AgGrid.scss, kit/blueprint/styles.scss, kit/onsen/theme.scss, mobile/cmp/menu/impl/Menu.js, mobile/cmp/menu/impl/Menu.scss, styles/vars.scss
Tested on device with toolbox-dev. …
=> Highlight mobile menu items on tap + add menu CSS vars

CHANGELOG.md, admin/AppModel.js, admin/tabs/server/ServerTab.js, admin/tabs/server/ehcache/EhCachePanel.js, admin/tabs/server/environment/ServerEnvModel.js, admin/tabs/server/environment/ServerEnvPanel.js, admin/tabs/server/services/ServicePanel.js
+ Requires corresponding hoist-core update to enable, disables gracefully otherwise.
+ Add brief intro labels to other server-side tabs for clarity. …
=> New admin tab displays server env vars + system properties

cmp/form/field/BaseFieldModel.js, data/validation/constraints.js
=> Null displayName on FieldModel should default to generated displayName

desktop/appcontainer/IdlePanel.scss
Fixes https://github.com/xh/hoist-react/issues/2782 …
=> Fix idlePanel display.

admin/tabs/server/logViewer/LogDisplayModel.js
=> Don't scroll logs to top when turning off tail mode, Fixes #2776

CHANGELOG.md, desktop/appcontainer/AppContainer.js
Resolves #2781 
See matching toolbox PR: https://github.com/xh/toolbox/pull/540
> …
=> Build refresh app data hotkey into hoist

CHANGELOG.md, cmp/grid/Grid.js, desktop/cmp/contextmenu/StoreContextMenu.js, svc/GridExportService.js
=> Use Export formatting for Clipboard

CHANGELOG.md, core/XH.js, desktop/appcontainer/ExceptionDialog.js, mobile/appcontainer/ExceptionDialog.js, svc/FetchService.js
The current proposal here just makes a very specific patch for our handling of our own forms based auth in Hoist.
Did not see a clear path or need to come up with a more general API at this time.  However, this should not cause problems for Colin's use case at client.
> …
=> Auto reload app for non-SSO auth situations

mobile/cmp/header/AppBar.js
=> Adjust mobile home button navigation to work even if your home route isn't 'default'

appcontainer/ViewportSizeModel.js
=> ViewportSizeModel determines orientation from window.screen on phones / tablets

cmp/grid/Grid.js, cmp/grid/GridModel.js
Fixes https://github.com/xh/hoist-react/issues/2820 …
=> Persist column width when noting a column has been manually sized.

cmp/filter/impl/QueryEngine.js, desktop/cmp/filter/FilterChooser.scss
Fixes: https://github.com/xh/hoist-react/issues/2810
Fixes: https://github.com/xh/hoist-react/issues/2811 …
=> Filter chooser improvements

mobile/cmp/input/DateInput.js
Tested on device.
Fixes https://github.com/xh/hoist-react/issues/2814
> single …
=> Don't bring up device keyboard when opening mobile DateInput popup.

CHANGELOG.md, desktop/cmp/dash/DashContainerModel.js, kit/golden-layout/styles.scss
Fixes #2831 
Also took the opportunity to adjust the styling of the menu to be consistent with our other menus. …
=> Fix displaying of dash container overflow menu

CHANGELOG.md, desktop/cmp/treemap/TreeMap.js, desktop/cmp/treemap/TreeMapModel.js
See issue: https://github.com/xh/hoist-react/issues/2833 …
=> TreeMap uses lightest shading for zero heat.

CHANGELOG.md, data/Store.js
=> New property to make record reuse opt-in

CHANGELOG.md, admin/columns/Rest.js, admin/columns/Tracking.js, admin/tabs/activity/clienterrors/ClientErrorDetail.js, admin/tabs/activity/clienterrors/ClientErrorsModel.js, admin/tabs/activity/clienterrors/ClientErrorsPanel.js, admin/tabs/activity/tracking/detail/ActivityDetailModel.js, admin/tabs/activity/tracking/detail/ActivityDetailView.js, cmp/grid/columns/DatesTimes.js, format/FormatDate.js
=> Show seconds

desktop/cmp/grid/impl/filter/ColumnHeaderFilterModel.js
It was straightforward enough to simply not create the ValuesTabModel if enableValues is false.
See issue [#2843](https://github.com/xh/hoist-react/issues/2843)
Note that this implementation is likely to change with https://github.com/xh/hoist-react/issues/2841, since the value extraction code will likely be refactored to be shared by both tabs. But I still think its worth taking this improvement in the interim.
button below to …
=> Avoid extracting values from store when GridFilterFieldSpec.enableValues is false

CHANGELOG.md, cmp/filter/FilterChooserFieldSpec.js, utils/datetime/LocalDate.js
Not the final word on this but this bit of work could be done easily now without any API changes, or required changes to Hoist Core. …
=> Make LocalDate.get() accept hyphens.

CHANGELOG.md, cmp/grid/columns/Column.js, cmp/grid/columns/DatesTimes.js, cmp/grid/columns/ExcelFormat.js, cmp/grid/columns/index.js, svc/GridExportService.js
+ Only send per-cell ExportFormat for excel exports.
+ Rename ExportFormat > ExcelFormat 
+ Rename Column.exportFormat > Column.excelFormat
See issue: https://github.com/xh/hoist-react/issues/2797
See toolbox PR: https://github.com/xh/toolbox/pull/544 …
=> ExcelFormat

data/Store.js
=> New Experimental flag castIdToString

desktop/cmp/grid/impl/filter/custom/CustomRow.js, desktop/cmp/grid/impl/filter/custom/CustomTab.scss
Fixes [#2851](https://github.com/xh/hoist-react/issues/2851) …
=> Allow column filter's custom tab to scroll without covering remove buttons

cmp/grid/columns/Column.js
Avoid ugly errors from casual tooltip implementors …
=> Make tooltip more robust.

admin/tabs/general/alertBanner/AlertBannerModel.js, admin/tabs/general/alertBanner/AlertBannerPanel.js
Noticed this little bug when testing an (unrelated) problem with Hoist core that was keeping it from creating json blobs. 
Was causing this window to fail, with no clear indication as to what was happening.
Happy to discuss …
=> Display errors when trying to update banner

CHANGELOG.md, cmp/grid/GridModel.js
=> Add gridIsInEditingMode flag to GridModel (in addition to existing more-sensitive flag 'isEditing')

CHANGELOG.md, desktop/cmp/input/NumberInput.js, mobile/cmp/input/NumberInput.js
Fixes #2821 
Toolbox pr with examples: https://github.com/xh/toolbox/pull/551
> …
=> Add `scaleFactor` prop to NumberInput

admin/tabs/server/websocket/WebSocketPanel.js, svc/WebSocketService.js
=> Web socket check

CHANGELOG.md, cmp/grid/GridModel.js
=> Fix docstring for GridModel's emptyText

kit/onsen/styles.scss
Fixes https://github.com/xh/hoist-react/issues/2880 …
=> Fix red border for invalid mobile inputs.

CHANGELOG.md, cmp/ag-grid/AgGridModel.js, cmp/grid/Grid.js, cmp/grid/GridModel.js, data/Store.js, data/StoreRecord.js, desktop/cmp/contextmenu/StoreContextMenu.js, desktop/cmp/grid/find/impl/GridFindFieldImplModel.js, svc/GridExportService.js
Restoring our ability to have integer ids in store by adding StoreRecord.agId
+ Fixes to AgGridModel code and docs to reflect new string ids.
Please Merge also toolbox branch with the same name …
=> Alternative id handling

cmp/grid/GridModel.js
Please check the issue for important caveats and limitations:
https://github.com/xh/hoist-react/issues/2886
See Toolbox branch used for testing: https://github.com/xh/toolbox/tree/dotDelimitedColumnFields …
=> Allow defining dot-delimited field in column field specs

CHANGELOG.md, cmp/grid/GridModel.js
See issue: https://github.com/xh/hoist-react/issues/2892
See Toolbox PR for usage: https://github.com/xh/toolbox/pull/563 …
=> Allow GridModels to extend 'Restore Grid Defaults'.

CHANGELOG.md, appcontainer/MessageModel.js, core/XH.js, desktop/appcontainer/Message.js, mobile/appcontainer/Message.js
+ Spec "left" to place Cancel action button on left side of toolbar, separated from the Confirm button by a filler. …
=> Support cancelAlign message config

CHANGELOG.md, core/AppSpec.js, desktop/appcontainer/AppContainer.js, mobile/appcontainer/AppContainer.js
=> Allow AppSpecs to define a custom LockoutPanel component

CHANGELOG.md, appcontainer/ThemeModel.js, core/XH.js, desktop/cmp/appOption/ThemeAppOption.js, mobile/cmp/appOption/ThemeAppOption.js
=> Add support for "sync with system" as a theme option

CHANGELOG.md, desktop/cmp/input/Select.js, mobile/cmp/input/Select.js
See issue: https://github.com/xh/hoist-react/issues/2911 …
=> Fix Selects to not commit null when clearing filter text

CHANGELOG.md, cmp/form/field/SubformsFieldModel.js
=> Fix dirty detection for subforms

CHANGELOG.md, data/filter/FieldFilter.js
Resolves https://github.com/xh/hoist-react/issues/2925
https://github.com/xh/toolbox/tree/filterCommitted  (Filter Chooser)
https://github.com/xh/toolbox/tree/columnFiltersOnInlineEditingPanel  (Column Filters) …
=> FieldFilter ignores record if no committedData

CHANGELOG.md, mobile/appcontainer/FeedbackDialog.js, mobile/appcontainer/FeedbackDialog.scss, mobile/cmp/dialog/Dialog.js, mobile/cmp/dialog/Dialog.scss
=> Mobile dialogs scroll internally if taller than the screen

cmp/grid/impl/ColumnWidthCalculator.js
See issue: https://github.com/xh/hoist-react/issues/2941 …
=> Don't warn when autosizing a column with headerName: null

desktop/cmp/dash/canvas/impl/DashCanvasView.js
=> Fix dash canvas duplicate

cmp/grid/Grid.js
=> Add flag to suppress Clipboard API due to change in Chrome's handling of the API

desktop/cmp/dash/canvas/DashCanvasModel.js, desktop/cmp/dash/canvas/DashCanvasViewModel.js, desktop/cmp/dash/canvas/impl/DashCanvasView.js
=> Return ref to DOM element when new DashCanvasView is created

desktop/cmp/dash/canvas/DashCanvas.js, desktop/cmp/dash/canvas/DashCanvas.scss, desktop/cmp/dash/canvas/DashCanvasModel.js, desktop/cmp/dash/canvas/DashCanvasViewModel.js, desktop/cmp/dash/canvas/DashCanvasViewSpec.js, desktop/cmp/dash/canvas/impl/DashCanvasContextMenu.js, desktop/cmp/dash/canvas/impl/DashCanvasView.js, desktop/cmp/dash/canvas/impl/utils.js
=> DashCanvas bug fixes

core/TaskObserver.js
=> TaskObserver modified to accept ReactNode as message

CHANGELOG.md, cmp/grid/columns/Column.js
=> Ensure boolean values returned by grid renderers actually render

CHANGELOG.md, core/HoistComponent.js
=> In HoistCmp's callRender, props should be enhanced prior to being set on ctx, Fixes: #2913

admin/tabs/general/about/AboutPanel.js, cmp/filter/impl/QueryEngine.js, cmp/grid/helpers/GridCountLabel.js, cmp/websocket/WebSocketIndicator.js
=> Fixed a few fmt [Object object] cases

mobile/cmp/tab/impl/TabContainer.js
=> Update to tabContainer mobile emptyText

desktop/cmp/dash/canvas/DashCanvasModel.js
=> Fix MobX bug in DashCanvasModel.publishState()

desktop/cmp/grid/editors/DateEditor.js
Fixes: https://github.com/xh/hoist-react/issues/2980 …
=> Fix showing date picker in inline date editor

CHANGELOG.md, admin/App.js, admin/AppModel.js
=> Allow for customizable app menu items in admin console

CHANGELOG.md, core/HoistComponent.js, core/HoistModel.js, core/impl/ModelLookup.js
Cleanup/Tightening discovered during research on #2931 …
=> Require Model passed to a HoistComponent to be a HoistModel

CHANGELOG.md, admin/tabs/general/GeneralTab.js
=> Provide soft config to hide General > Users tab in Admin console

CHANGELOG.md, data/Store.js
=> Throw if summaryRecord ID is not unique

svc/FetchService.js, svc/LocalStorageService.js
=> Improve handling when Local Storage not available.

CHANGELOG.md, cmp/dataview/DataView.scss, cmp/dataview/DataViewModel.js, cmp/grid/Grid.js, cmp/grid/GridModel.js
See issue: https://github.com/xh/hoist-react/issues/2992 …
=> Remove groupRowElementRenderer

CHANGELOG.md, cmp/grid/GridModel.js, cmp/grid/columns/Column.js, cmp/grid/impl/Utils.js, format/FormatUtils.js
=> Column renderers should not be allowed to take down an app

cmp/ag-grid/AgGridModel.js
=> Fix bug where Grid would render incorrectly on sort order change

cmp/grid/Grid.js, cmp/grid/GridModel.js, cmp/grid/impl/ColumnWidthCalculator.js, format/FormatNumber.js, svc/GridAutosizeService.js
See issue for more information, discussion and caveats: https://github.com/xh/hoist-react/issues/2996
+ Ensure current recordset has been rendererd prior to starting autosize.
+ Limit total number of records sampled.
> collapse multiple intermediate commits into a single …
=> Improve autosizing with AG27

desktop/cmp/dash/canvas/DashCanvasModel.js
=> Update dashCanvasModel.addView() to include state

CHANGELOG.md, desktop/cmp/treemap/TreeMap.js, desktop/cmp/treemap/TreeMapModel.js
=> Provide StoreRecord as second argument to TreeMapModel's valueRenderer and heatRenderer

CHANGELOG.md, svc/ChangelogService.js
=> Support new `xhChangelogConfig.limitToRoles` soft-config

CHANGELOG.md, utils/js/LangUtils.js
=> Add support for Map and WeakMap collections in LangUtils.getOrCreate

CHANGELOG.md, mobile/cmp/input/TextInput.js, mobile/cmp/input/TextInput.scss
See https://github.com/xh/toolbox/pull/586
Resolves #3023  …
=> Allow enableClear button within mobile textInput

desktop/cmp/grid/editors/impl/InlineEditorModel.js
=> Flush any pending value when asked by editor framework for value.

CHANGELOG.md, desktop/cmp/grid/editors/SelectEditor.js
=> Fix focus issues with SelectEditor

CHANGELOG.md, desktop/cmp/dash/DashViewModel.js, desktop/cmp/dash/canvas/DashCanvas.js, desktop/cmp/dash/canvas/DashCanvasViewModel.js, desktop/cmp/dash/canvas/DashCanvasViewSpec.js, desktop/cmp/dash/canvas/impl/DashCanvasView.js, desktop/cmp/dash/container/impl/DashContainerContextMenu.js
=> Add DashCanvasViewModel support for extraMenuItems and headerItems

CHANGELOG.md, desktop/cmp/dash/canvas/DashCanvas.scss, desktop/cmp/dash/canvas/DashCanvasModel.js
=> Dash canvas bugs

CHANGELOG.md, cmp/filter/FilterChooserFieldSpec.js, cmp/filter/impl/Option.js, cmp/grid/columns/Core.js, cmp/grid/filter/GridFilterFieldSpec.js, cmp/grid/index.js, cmp/grid/renderers/TagsRenderer.js, cmp/grid/renderers/TagsRenderer.scss, data/Field.js, data/filter/BaseFilterFieldSpec.js, data/filter/FieldFilter.js, desktop/cmp/grid/impl/filter/ColumnHeaderFilterModel.js, desktop/cmp/grid/impl/filter/values/ValuesTabModel.js
=> Support for 'array' field type

CHANGELOG.md, cmp/grid/filter/GridFilterFieldSpec.js
=> Flatten filtered record values

CHANGELOG.md, desktop/cmp/panel/impl/PanelHeader.js, mobile/cmp/panel/impl/PanelHeader.js
=> Fix bug where Panel would throw when headerItems = null

CHANGELOG.md, cmp/grid/GridModel.js, cmp/grid/impl/ColumnWidthCalculator.js, svc/GridAutosizeService.js
Please merge also:
https://github.com/xh/toolbox/pull/588 …
=> Enhance autosize

CHANGELOG.md, cmp/filter/impl/QueryEngine.js
=> QueryEngine now searches within multi-word field names

CHANGELOG.md
=> Update CHANGELOG with PanelHeader change

CHANGELOG.md, utils/js/Decorators.js
=> Add `@abstract` decorator

CHANGELOG.md, appcontainer/MessageSourceModel.js, core/XH.js, desktop/cmp/dash/canvas/DashCanvasModel.js
=> Minor bug fixes in `DashCanvasModel`, `MessageSourceModel` and `XHClass`

CHANGELOG.md, kit/ag-grid/index.js
See Toolbox PR: https://github.com/xh/toolbox/pull/591 …
=> Update to ag-Grid 28.

desktop/cmp/dash/canvas/DashCanvasModel.js
+ A persisted state could ref. an obsolete widget - currently that will throw the model ctor. …
=> DashCanvas fails gracefully on unknown viewSpecId

cmp/ag-grid/AgGrid.scss
=> Disable native AgGrid hover

CHANGELOG.md, cmp/grid/GridModel.js
=> Add ensureRecordsVisibleAsync method to GridModel

cmp/ag-grid/AgGrid.scss
=> Removed style mismatch when context menu is open

cmp/ag-grid/AgGrid.scss
=> Cell border now does not show on right click when showCellFocus is false

CHANGELOG.md, desktop/cmp/button/AppMenuButton.js, desktop/cmp/contextmenu/ContextMenu.js, desktop/cmp/dash/canvas/DashCanvas.js, desktop/cmp/dash/canvas/impl/DashCanvasContextMenu.js, desktop/cmp/dash/canvas/impl/utils.js, desktop/cmp/dash/container/DashContainer.js, desktop/cmp/dash/container/impl/DashContainerContextMenu.js
=> Modify empty `DashCanvas` / `DashContainer` "Add View" button to only list available views

CHANGELOG.md, cmp/grid/Grid.js
=> Disable Grid ContextMenu when inline editing

CHANGELOG.md, cmp/grid/GridModel.js
=> Wait a tick *after* the grid is confirmed ready to allow processing of data updates

CHANGELOG.md, cmp/grid/Grid.js, core/HoistBase.js
=> Enhance addReaction/addAutorun to accept multiple reactions

CHANGELOG.md, desktop/appcontainer/Toast.scss, desktop/appcontainer/ToastSource.js, kit/blueprint/styles.scss
+ Consolidate desktop Toast styles to Toast.scss.
+ Apply `.xh-toast--{intent}` class rather than relying on bp-applied class. …
=> Fix text color on desktop warning toasts

CHANGELOG.md, desktop/cmp/input/CodeInput.js
=> Fix `ModalSupport` bugs in `CodeInput`

CHANGELOG.md, desktop/cmp/input/ButtonGroupInput.js, mobile/cmp/input/ButtonGroupInput.js
=> Added enableMulti option to ButtonGroupInput

admin/differ/DifferModel.js
=> Add warning to confirm dialog when syncing config to production

CHANGELOG.md, admin/tabs/activity/tracking/charts/ChartsModel.js, admin/tabs/activity/tracking/charts/ChartsPanel.js
=> Add toggle weekends checkbox to admin activity chart

CHANGELOG.md, desktop/cmp/grid/impl/filter/values/ValuesTab.js
=> AutoFocus filterText field in ColumnHeaderFilter

CHANGELOG.md, desktop/cmp/form/FormField.scss
=> Support line breaks in default `FormField` read-only renderer

CHANGELOG.md, appcontainer/AboutDialogModel.js, appcontainer/AppContainerModel.js, core/HoistAppModel.js, core/index.js, desktop/appcontainer/AboutDialog.js, desktop/appcontainer/VersionBar.js, desktop/cmp/button/AppMenuButton.js, desktop/cmp/contextmenu/ContextMenuItem.js, mobile/appcontainer/VersionBar.js, mobile/cmp/header/AppMenuButton.js
=> Enhance `AboutDialog` to display more dynamic custom properties.

cmp/ag-grid/AgGrid.scss
See issue https://github.com/xh/hoist-react/issues/2898 …
=> Alternative approach to #2898 which avoids using !important

CHANGELOG.md, core/HoistComponent.js
- [ X] Created Toolbox branch / PR, or determined not required. …
=> Clone props

CHANGELOG.md, admin/differ/Differ.scss, admin/differ/DifferDetail.js, admin/differ/DifferModel.js
=> Show lastUpdated / lastUpdatedBy in admin config/pref differ 

CHANGELOG.md, core/HoistModel.js, core/XH.js, core/modelspec/uses.js
- [X ] Caught up with `develop` branch as of last change. …
=> XH.getActiveModels()

desktop/cmp/dash/container/DashContainerModel.js, desktop/cmp/dash/container/impl/DashContainerUtils.js
=> Make DashContainerModel.onResize and convertStateToGL null safe, Fixes: #3126

CHANGELOG.md, desktop/cmp/button/DashCanvasAddViewButton.js, desktop/cmp/button/index.js, desktop/cmp/dash/canvas/DashCanvas.js, desktop/cmp/dash/canvas/impl/DashCanvasContextMenu.js
=> Expose dashCanvasAddViewButton as a public component

CHANGELOG.md, core/TaskObserver.js
=> Tweak to task observer logic

CHANGELOG.md, core/XH.js
=> Check and require that all service classes extend HoistService

CHANGELOG.md, data/filter/BaseFilterFieldSpec.js
=> Fixed boolean filterChooser fields suggesting true for 'false' 

CHANGELOG.md, svc/EnvironmentService.js
+ And `serverBuild` for good measure since we poll both anyway and both can factor into pre-existing upgrade prompt.
+ Fixes #3035 …
=> Add observable `XH.environmentService.serverVersion`

CHANGELOG.md, desktop/cmp/contextmenu/StoreContextMenu.js
=> Fixed store context menu rendering '[object Object]' on formatter-having fields

inspector/Inspector.scss, inspector/InspectorPanel.js, inspector/instances/InstancesModel.js, inspector/instances/InstancesPanel.js, inspector/stats/StatsModel.js, svc/InspectorService.js
=> Inspector improvement (syncRun)

core/HoistComponent.ts
Note that this will require a fix to our linting configuration …
=> HoistCmp TS signature cleanup

CHANGELOG.md, desktop/cmp/modalsupport/ModalSupport.js, desktop/cmp/modalsupport/ModalSupportModel.js
=> Fix ModalSupport lifecycle bug

cmp/form/FormModel.ts, data/validation/Rule.ts, desktop/cmp/dock/DockViewModel.ts
=> Modify Form and DockContainer model prop interfaces

CHANGELOG.md, desktop/appcontainer/Toast.scss
=> Fix toast styling bug

core/types/Types.ts, data/Store.ts, data/validation/Rule.ts, desktop/cmp/dash/DashViewModel.ts, desktop/cmp/dash/canvas/DashCanvasModel.ts, desktop/cmp/loadingindicator/LoadingIndicator.ts
=> Create Awaitable and Corner Types, modify Dash LoadingIndic, and Store

icon/Icon.ts
=> Add missing FontAwesome size options to Icon.ts

admin/tabs/activity/feedback/FeedbackPanel.ts, admin/tabs/monitor/MonitorEditorPanel.ts, admin/tabs/server/logLevel/LogLevelPanel.ts, admin/tabs/userData/UserPreferencePanel.ts, desktop/cmp/rest/RestGrid.ts, desktop/cmp/rest/data/RestStore.ts
=> Improve typescript signature for RestGrid

core/types/Interfaces.ts, utils/datetime/LocalDate.ts
=> Minor typescript tweaks

cmp/grid/filter/GridFilterModel.ts
=> BLANK_STR rename and make static

cmp/filter/FilterChooserModel.ts, cmp/form/FormModel.ts, cmp/grid/GridModel.ts, cmp/grid/Types.ts, cmp/grid/columns/Column.ts, cmp/grid/columns/ColumnGroup.ts, cmp/grid/filter/GridFilterModel.ts, cmp/grid/impl/MenuSupport.ts, cmp/grouping/GroupingChooserModel.ts, cmp/tab/TabContainerModel.ts, core/HoistBase.ts, data/RecordAction.ts, data/Store.ts, desktop/cmp/input/Select.ts, desktop/cmp/record/RecordActionBar.ts, desktop/cmp/rest/RestGridModel.ts, desktop/cmp/rest/data/RestStore.ts, mobile/cmp/input/Select.ts
=> typeTighten

core/HoistAppModel.ts, desktop/appcontainer/AppContainer.ts, desktop/appcontainer/VersionBar.ts, mobile/appcontainer/VersionBar.ts
=> Allow App more flexibility to hide/show its version bar.

core/XH.ts, desktop/appcontainer/AppContainer.ts, mobile/appcontainer/AppContainer.ts
=> Use AppLoadModel for initial masking

CHANGELOG.md, format/FormatNumber.ts
- [C] Created Toolbox branch / PR, or determined not required. …
=> Add allowBillions flag to fmtQuantity, Fixes #3210

CHANGELOG.md, cmp/grid/columns/Column.ts, cmp/spinner/Spinner.ts, desktop/cmp/grid/columns/Actions.ts, yarn.lock
=> TS type fixes for Spinner and ColumnSpec.actions

cmp/grid/GridModel.ts, cmp/grid/Types.ts, cmp/grid/filter/GridFilterModel.ts
=> Fix exported interface GridFilterModelConfig.

CHANGELOG.md, desktop/cmp/grid/editors/impl/InlineEditorModel.ts
=> Fix bug with single charachter editing.

cmp/ag-grid/AgGrid.ts, cmp/ag-grid/AgGridModel.ts
Delay check against doubly-mounted agGridModel, allowing time for unregister in the case of a swap. …
=> Allow Grid remount

CHANGELOG.md, desktop/cmp/dash/container/DashContainer.ts
=> Eliminate spurious and transient "empty" messages in dash container

CHANGELOG.md, cmp/grid/GridModel.ts
=> Grids will persist minimal metadata on hidden columns

CHANGELOG.md, desktop/cmp/panel/Panel.ts
=> Panel class name dropped bug

cmp/chart/ChartModel.ts
=> Add missing types to ChartModel

CHANGELOG.md, appcontainer/ErrorBoundary.ts, cmp/form/Form.ts, cmp/layout/Box.ts, cmp/layout/Frame.ts, cmp/layout/Placeholder.ts, cmp/layout/Tags.ts, cmp/layout/Viewport.ts, core/HoistComponent.ts, core/elem.ts, core/model/ModelLookup.ts, desktop/cmp/button/ButtonGroup.ts, desktop/cmp/input/ButtonGroupInput.ts, desktop/cmp/toolbar/Toolbar.ts, kit/blueprint/Dialog.ts, kit/blueprint/Wrappers.ts, kit/blueprint/index.ts, kit/onsen/index.ts, mobile/cmp/input/ButtonGroupInput.ts, mobile/cmp/input/Label.ts, mobile/cmp/navigator/impl/swipe/Swiper.ts, mobile/cmp/toolbar/Toolbar.ts
=> Remove containerElementFactory/standardElementFactory distinction

CHANGELOG.md, svc/GridExportService.ts
=> Add flag to enable tracking of grid exports

CHANGELOG.md, data/Field.ts, data/StoreRecord.ts, data/StoreSelectionModel.ts, data/cube/Query.ts, data/cube/View.ts, data/cube/row/AggregateRow.ts, data/cube/row/BaseRow.ts, data/cube/row/BucketRow.ts, data/cube/row/LeafRow.ts, data/cube/row/RowUpdate.ts, data/validation/Rule.ts
+ Related cleanups to mark immutable objects as immutable, and avoid extra deep copies when updating queries. …
=> + Improve cube caching via updateQuery.

core/types/Interfaces.ts, desktop/cmp/input/Select.ts, mobile/cmp/input/Select.ts
See issue: https://github.com/xh/hoist-react/issues/3274 …
=> Move SelectOption interface to core

core/model/HoistModel.ts
=> Update generic HoistModelClass interface to accept abstract HoistModel's

desktop/cmp/panel/PanelModel.ts
=> Only disable panel sizing if both `showSplitter` and `resizeWhileDragging` are `false`

CHANGELOG.md, data/Store.ts, data/cube/Cube.ts, data/cube/Query.ts, data/cube/View.ts, data/cube/row/AggregateRow.ts, data/cube/row/BaseRow.ts, data/cube/row/BucketRow.ts, data/cube/row/LeafRow.ts, data/cube/row/RowUpdate.ts, utils/impl/Equals.ts
+ Add typings + related fixes
+ Remove use of `hasOwn`
- [ X] Updated doc comments / prop-types, or determined not required.
- [ X] Reviewed and tested on Mobile, or determined not required. …
=> Enhancement to Cubes omitFn property

docs/upgrade-to-typescript.md
=> Ts upgrade doc

CHANGELOG.md, admin/columns/Tracking.ts, admin/tabs/activity/aggregators/RangeAggregator.ts, admin/tabs/activity/tracking/ActivityTrackingModel.ts
=> Clean-up Date Range handling in tracking

CHANGELOG.md, desktop/cmp/dash/DashViewModel.ts, desktop/cmp/dash/canvas/DashCanvasModel.ts, desktop/cmp/dash/canvas/DashCanvasViewModel.ts, desktop/cmp/dash/canvas/DashCanvasViewSpec.ts, desktop/cmp/dash/canvas/impl/DashCanvasView.ts
=> Dash canvas enhancements

CHANGELOG.md, data/cube/View.ts, data/cube/row/AggregateRow.ts
=> Preserve dim values

admin/differ/DifferModel.ts, cmp/ag-grid/AgGridModel.ts, cmp/chart/Chart.ts, cmp/chart/ChartModel.ts, cmp/filter/FilterChooserModel.ts, cmp/grid/GridModel.ts, cmp/grouping/GroupingChooserModel.ts, core/HoistBase.ts, core/HoistBaseDecorators.ts, core/persist/PersistenceProvider.ts, desktop/cmp/dash/container/DashContainerModel.ts, desktop/cmp/leftrightchooser/LeftRightChooser.ts, desktop/cmp/treemap/TreeMapModel.ts, svc/PrefService.ts
It actually failed on one usage (in TreeMapModel) where lodash did not, so there is some risk here.
(left deepClone).  Would be good to understand why.
Think this is still worth taking, but need to test it carefully -- being sure to run every usage. …
=> Replace CloneDeep with structuredClone

CHANGELOG.md, desktop/cmp/dash/canvas/DashCanvasModel.ts
=> Add width and height params to DashCanvasModel.addView

CHANGELOG.md, svc/FetchService.ts
=> Add `abort` method to `FetchService`

desktop/cmp/dash/canvas/DashCanvasViewModel.ts
=> Fix bug where DashCanvasView autoheight sometimes cuts off contents

CHANGELOG.md, admin/differ/DifferModel.ts, cmp/ag-grid/AgGridModel.ts, cmp/chart/Chart.ts, cmp/chart/ChartModel.ts, cmp/filter/FilterChooserModel.ts, cmp/grid/GridModel.ts, cmp/grouping/GroupingChooserModel.ts, core/HoistBase.ts, core/HoistBaseDecorators.ts, core/persist/PersistenceProvider.ts, desktop/cmp/dash/container/DashContainerModel.ts, desktop/cmp/leftrightchooser/LeftRightChooser.ts, desktop/cmp/treemap/TreeMapModel.ts, svc/PrefService.ts
=> V55 maintenance

cmp/ag-grid/AgGrid.ts, cmp/ag-grid/AgGridModel.ts, cmp/grid/Grid.ts, cmp/grid/GridAutosizeOptions.ts, cmp/grid/GridModel.ts, cmp/grid/Types.ts, cmp/grid/columns/Column.ts, cmp/grid/columns/ColumnGroup.ts, cmp/grid/impl/ColumnGroupHeader.ts, cmp/grid/impl/ColumnHeader.ts, cmp/grid/impl/ColumnWidthCalculator.ts, cmp/grid/impl/MenuSupport.ts, cmp/grid/impl/RowKeyNavSupport.ts, cmp/grid/impl/Utils.ts, desktop/cmp/grid/editors/DateEditor.ts, desktop/cmp/grid/editors/EditorProps.ts, desktop/cmp/grid/editors/impl/InlineEditorModel.ts, desktop/cmp/grid/find/impl/GridFindFieldImplModel.ts, kit/ag-grid/index.ts, package.json, svc/GridAutosizeService.ts, svc/GridExportService.ts, yarn.lock
I am limiting this to typescript related changes in order to faciliate merge/release before worrying about some of the warts we discovered with our use of `renderer` and `getValueFn`.
We can deal with that in a seperate PR or release.  Will create a ticket with findings related to that now.
Note there is one TODO, related to a change with behavior of sort state for pivot grids.  this still needs to be tested/addressed.
button below …
=> Use Community Types for agGrid

utils/js/LangUtils.ts
=> Added `ordinalize()` to LangUtils.ts

format/FormatNumber.ts
=> Added the `NumberFormatOptions.zeroDisplay` parameter

CHANGELOG.md, cmp/grid/filter/GridFilterFieldSpec.ts, desktop/cmp/grid/impl/filter/values/ValuesTabModel.ts
=> Backport v56 bug fix to filtering.

cmp/form/Form.ts
=> Fix FormProps interface

CHANGELOG.md, admin/tabs/monitor/MonitorColumns.ts, admin/tabs/server/memory/MemoryMonitorModel.ts, admin/tabs/server/memory/MemoryMonitorPanel.ts, utils/js/LangUtils.ts
+ This PR goes with the PR in hoist core by the same name.
+ Taking the minor HC version is a be a weak (but easy) requirement.  Memory monitor charting will appear slightly bust if data not there -- but it should all still be fully usable.  …
=> Memory Monitoring Admin enhancements

CHANGELOG.md, cmp/ag-grid/AgGrid.ts, cmp/grid/Grid.ts, kit/ag-grid/index.ts
+ Use scrolling optimization
+ Tweak to vanilla AgGridComponent row sizing to use appropriate group sizes …
=> Use scrolling optimization

cmp/form/FormModel.ts, data/RecordAction.ts, data/Store.ts, data/StoreRecord.ts, data/cube/Cube.ts, data/cube/CubeField.ts, data/cube/View.ts, data/validation/Rule.ts, desktop/cmp/dash/DashViewModel.ts, desktop/cmp/dash/container/DashContainerModel.ts, desktop/cmp/error/ErrorMessage.ts, desktop/cmp/input/CodeInput.ts, desktop/cmp/treemap/TreeMapModel.ts, mobile/cmp/error/ErrorMessage.ts, mobile/cmp/input/DateInput.ts, mobile/cmp/popover/Popover.ts
=> Replace Record<string, any> with the Hoist PlainObject type

cmp/filter/FilterChooserModel.ts
=> Fix typing for FilterChooserModel.fieldSpecDefaults to accept partial configs

CHANGELOG.md, desktop/cmp/dash/container/DashContainerModel.ts
=> Expose `borderWidth` property on DashContainerModel.

admin/tabs/server/memory/MemoryMonitorModel.ts
solves: #3335 and aligns y Axii
solution taken from https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/candlestick-and-volume/
which is a demo linked to from the Highcharts docs at:
https://api.highcharts.com/highstock/yAxis.top
... and btw, AI/LLM was of no use in solving this one.  I'll take full credit, thank you very much. :)
button below to indicate it is not ready yet for a final …
=> solves: #3335 and aligns y Axii

CHANGELOG.md, admin/tabs/server/memory/MemoryMonitorModel.ts, admin/tabs/server/websocket/WebSocketModel.ts, core/XH.ts, desktop/cmp/dash/canvas/DashCanvasModel.ts, mobile/appcontainer/ExceptionDialogDetails.ts
=> Added generic type to `XH.promise()`

CHANGELOG.md, desktop/appcontainer/Banner.scss, mobile/appcontainer/Banner.scss, styles/vars.scss
=> Banner height

admin/tabs/server/logViewer/LogDisplay.ts, utils/impl/TimeZone.ts
=> Server time fix

CHANGELOG.md, cmp/dataview/DataView.ts
=> Support `agOptions` prop on `DataView`

CHANGELOG.md, desktop/cmp/modalsupport/ModalSupport.ts
=> Fix layout issues w/popovers triggered from within `ModalSupport` dialogs

cmp/grid/GridModel.ts, utils/js/LangUtils.ts
=> Add column name output to column uniqueness validation

CHANGELOG.md, cmp/ag-grid/AgGrid.ts
=> Improve workaround for `suppressBrowserResizeObserver`

CHANGELOG.md, kit/onsen/index.ts
=> Fix forwarding refs to Onsen components

CHANGELOG.md, admin/tabs/general/alertBanner/AlertBannerModel.ts, admin/tabs/general/alertBanner/AlertBannerPanel.ts
* Relative timestamp in presets
* Fix Updated timestamp format …
=> Check hoist core version for admin banner presets

CHANGELOG.md, desktop/cmp/leftrightchooser/LeftRightChooserModel.ts, desktop/cmp/leftrightchooser/impl/ChooserToolbar.ts
=> Add observable `readonly` property to `LeftRightChooserModel`

CHANGELOG.md, svc/IdentityService.ts
+ Support for new 'HOIST_IMPERSONATOR' role
+ Allow customization of impersonation targets.
- [ X] Created Toolbox branch / PR, or determined not required. …
=> Impersonation Improvements

CHANGELOG.md, core/types/Interfaces.ts, svc/TrackService.ts
=> New option TrackOptions.logData

format/FormatNumber.ts
=> Make calcStyleFromColorSpec function null safe

CHANGELOG.md, cmp/tab/TabContainerModel.ts
=> Tab routing fix

CHANGELOG.md, cmp/grid/Grid.ts
=> Fix event source for detecting manual column resize

CHANGELOG.md, desktop/cmp/dash/DashModel.ts, desktop/cmp/dash/canvas/DashCanvas.ts, desktop/cmp/dash/canvas/DashCanvasModel.ts, desktop/cmp/dash/canvas/impl/DashCanvasContextMenu.ts, desktop/cmp/dash/container/DashContainer.ts
…loadSupport enabled views directly. …
=> New `DashModel.refreshContextModel`

desktop/cmp/dash/container/DashContainerModel.ts
=> Dash container load state async warning msg

CHANGELOG.md, format/FormatNumber.ts
=> Fixed fmtNumber returning '-0' when rounding small negative numbers

CHANGELOG.md, desktop/appcontainer/ToastSource.ts
=> Blueprint toaster triggering warning fix

CHANGELOG.md, cmp/ag-grid/AgGrid.scss, desktop/cmp/input/ButtonGroupInput.ts
=> Support null value for `ButtonGroupInput` option

CHANGELOG.md, desktop/cmp/panel/Panel.ts, desktop/cmp/panel/impl/PanelHeader.ts
=> Collapsed PanelHeader adjustments

CHANGELOG.md, desktop/cmp/input/Select.ts
=> Fix `select.selectOnFocus` regression from react-select upgrade

appcontainer/AppContainerModel.ts
+ Add `xhFlags` config to enable runtime toggle.
See hoist-core PR (does not need to be merged / released for this PR)
https://github.com/xh/hoist-core/pull/310 …
=> Workaround for Chromium / BigNumber bug

CHANGELOG.md, desktop/cmp/panel/Panel.ts, desktop/cmp/panel/impl/PanelHeader.ts, inspector/Inspector.scss, inspector/InspectorPanel.ts
=> Support new `Panel.headerClassName` prop

CHANGELOG.md, desktop/cmp/input/Checkbox.scss, desktop/cmp/input/Checkbox.ts, styles/vars.scss
=> Improve disabled checkbox colors, fixes #3434

data/cube/View.ts
=> Throw when attempting to connect a Store with `reuseRecords: true` to a Cube View.

CHANGELOG.md, appcontainer/ExceptionDialogModel.ts, cmp/error/ErrorBoundary.ts, core/XH.ts, core/exception/ExceptionHandler.ts, desktop/appcontainer/AppContainer.ts, desktop/cmp/error/ErrorMessage.ts, mobile/appcontainer/AppContainer.ts, mobile/cmp/error/ErrorMessage.ts, svc/GridExportService.ts
Enhanced ability to get details from ErrorMessage.  …
=> Enhance error message

CHANGELOG.md, desktop/cmp/dash/container/DashContainerModel.ts, desktop/cmp/dash/container/impl/DashContainerUtils.ts
=> Fix dash container model allow remove

CHANGELOG.md, desktop/appcontainer/Banner.ts, mobile/appcontainer/Banner.ts
=> Fix regression to alert banners. Resume allowing elements as messages.

admin/tabs/general/alertBanner/AlertBannerModel.ts, cmp/grid/GridModel.ts
=> Remove lodash import

mobile/cmp/menu/impl/Menu.scss
=> Fix max-height constraint on mobile menu

CHANGELOG.md, data/RecordAction.ts, inspector/instances/InstancesModel.ts
=> Add type for `ActionFnData.record`

CHANGELOG.md, desktop/cmp/dock/DockViewModel.ts
=> Add onClose hook to DockViewModel + DockViewConfig

CHANGELOG.md, cmp/grid/GridModel.ts, cmp/grid/columns/ColumnGroup.ts
=> Add `GridModel` APIs to lookup and show / hide entire column groups

CHANGELOG.md, cmp/ag-grid/AgGrid.scss, cmp/grid/Grid.scss, cmp/grid/GridModel.ts, cmp/grid/columns/ColumnGroup.ts
=> Col group borders

CHANGELOG.md, data/cube/Query.ts, data/cube/View.ts, data/cube/row/BaseRow.ts
=> New properties:`Query.omitFn`, `Query.bucketSpecFn` and `Query.lockFn`.

CHANGELOG.md, cmp/ag-grid/AgGrid.scss
=> Fix `Grid` cell border styling inconsistencies

cmp/grid/GridModel.ts
=> Fix bug where column group borders were not being properly defaulted

cmp/ag-grid/AgGridModel.ts, cmp/dataview/DataViewModel.ts, cmp/grid/GridContextMenu.ts, cmp/grid/Types.ts, cmp/grid/columns/Column.ts, cmp/grid/filter/GridFilterFieldSpec.ts, cmp/grid/impl/GridPersistenceModel.ts, cmp/zoneGrid/impl/ZoneGridPersistenceModel.ts, core/elem.ts, core/load/LoadSupport.ts, data/Store.ts, data/UrlStore.ts, desktop/cmp/rest/Actions.ts, svc/FetchService.ts, utils/js/LangUtils.ts, utils/react/LayoutPropUtils.ts
=> Misc Typescript Fixes

svc/AutoRefreshService.ts, utils/async/AsyncUtils.ts
=> Updated uses of `document.hidden`

svc/AutoRefreshService.ts, utils/async/AsyncUtils.ts
=> Auto refresh document hidden

data/filter/FieldFilter.ts
=> FieldFilter should use isEquals for = and != op comparisons

CHANGELOG.md, admin/differ/DifferModel.ts, appcontainer/AppStateModel.ts, appcontainer/PageStateModel.ts, appcontainer/SizingModeModel.ts, cmp/ag-grid/AgGrid.ts, cmp/ag-grid/AgGridModel.ts, cmp/chart/Chart.ts, cmp/filter/FilterChooserModel.ts, cmp/grid/Grid.ts, cmp/grid/GridModel.ts, cmp/grid/columns/Column.ts, cmp/grid/helpers/GridCountLabel.ts, cmp/grid/impl/ColumnWidthCalculator.ts, cmp/grid/impl/GridPersistenceModel.ts, cmp/grouping/GroupingChooserModel.ts, cmp/tab/TabContainerModel.ts, cmp/zoneGrid/impl/ZoneGridPersistenceModel.ts, core/HoistBase.ts, core/impl/InstallServices.ts, data/impl/RecordSet.ts, desktop/appcontainer/ToastSource.ts, desktop/cmp/treemap/TreeMap.ts, svc/AutoRefreshService.ts, svc/GridAutosizeService.ts, svc/TrackService.ts, svc/WebSocketService.ts, utils/async/Timer.ts, utils/js/LogUtils.ts
Took this one step further, by making delegating methods on HoistBase.  The syntax has its pros and cons, but I would argue that overall its better.
More similar to hoist core, leverages HoistBase, and allows us to not have to surround multiple args in `[]` for most cases.  
Happy to discuss
> **Pull request reviewers:** when merging this P/R, please consider using a …
=> Enhanced LogUtils 2

cmp/grid/renderers/MultiFieldRenderer.ts
=> MultifieldRenderer - supplied renderer is always allowed to transform value

CHANGELOG.md, desktop/cmp/dock/DockViewModel.ts, desktop/cmp/dock/impl/DockView.ts
=> Add additional layout support for DockViews

CHANGELOG.md, desktop/cmp/grid/editors/DateEditor.ts
Fixes https://github.com/xh/hoist-react/issues/3552 …
=> Fix DateEditor popper styling to work with latest AgGrid css classes

CHANGELOG.md, cmp/grid/columns/ColumnGroup.ts
=> Fixed bug where ColumnGroup doesn't support omit

admin/tabs/general/roles/RoleModel.ts
=> Fix possible NPE in RoleModel.groupByCategoryReaction

core/exception/Exception.ts, svc/FetchService.ts
=> Tweak to how exception with 'ping' handled

admin/tabs/general/roles/RoleModel.ts, admin/tabs/general/roles/Types.ts, admin/tabs/general/roles/details/members/RoleMembers.ts, admin/tabs/general/roles/details/members/RoleMembersModel.ts, admin/tabs/general/roles/editor/form/RoleForm.ts
=> Misc tweaks to DefaultRoleAdmin API

CHANGELOG.md, cmp/grid/columns/Column.ts, cmp/grid/columns/ColumnGroup.ts, cmp/grid/impl/Utils.ts
=> Managed tooltip

admin/tabs/general/roles/graph/RoleGraphModel.ts
=> Guard against stack overflow in Role Graph

admin/tabs/general/roles/editor/form/RoleForm.ts, admin/tabs/general/roles/editor/form/RoleFormModel.ts
=> Tweak to remove ugly "null"

CHANGELOG.md, admin/tabs/general/roles/RoleModel.ts
=> More user friendly roles grid in admin

CHANGELOG.md, admin/tabs/general/roles/RolePanel.ts, admin/tabs/general/roles/editor/form/RoleForm.scss, admin/tabs/general/roles/editor/form/RoleForm.ts
=> Add Roles Admin tbar edit button and adjust member grid toolbars

inspector/stats/StatsModel.ts, svc/InspectorService.ts, utils/js/BrowserUtils.ts
=> Improves memory reporting in Inspector and tracking

CHANGELOG.md, admin/differ/Differ.scss
- Addresses dialog scaling uncontrollably when dealing with JSON content.
> single …
=> Restyles diff detail dialog to fit content properly

CHANGELOG.md, mobile/cmp/header/AppMenuButton.ts
=> Add reload item to default mobile app menu

CHANGELOG.md, appcontainer/AppStateModel.ts, core/TaskObserver.ts
=> TaskObserver.clear

CHANGELOG.md, cmp/zoneGrid/ZoneGridModel.ts
=> ZoneGrid columns' rendererIsComplex flag always set to true. Fixes #3612

CHANGELOG.md, core/types/Interfaces.ts, desktop/cmp/button/AppMenuButton.ts, desktop/cmp/contextmenu/ContextMenu.ts, mobile/cmp/menu/impl/Menu.ts
=> Add `className` to `MenuItem`

appcontainer/AppContainerModel.ts, appcontainer/RouterModel.ts
=> Determine `defaultRoute` by inspecting the AppModel's route configuration

admin/tabs/general/roles/editor/form/RoleFormModel.ts
=> Improve Directory Group lookup error handling

CHANGELOG.md, cmp/zoneGrid/ZoneGridModel.ts
=> Filter omissions before setting available columns in zone grid

CHANGELOG.md, cmp/grid/GridModel.ts, cmp/zoneGrid/ZoneGridModel.ts
=> Zone grid column filter refactor

CHANGELOG.md, kit/blueprint/styles.scss
=> Remove internal BP menu padding override

.gitignore, tsconfig.json
=> Update tsconfig.json with `composite: true`

CHANGELOG.md, desktop/cmp/grouping/GroupingChooser.ts, kit/blueprint/styles.scss
=> Patch hotfixes to grouping chooser and BP padding override

CHANGELOG.md, cmp/grid/Grid.ts, cmp/grid/GridModel.ts, cmp/zoneGrid/ZoneGridModel.ts, data/Store.ts, svc/GridAutosizeService.ts, svc/GridExportService.ts
=> Pinned rows

utils/async/Timer.ts
=> Fix type signature for Timer.setInterval

CHANGELOG.md, appcontainer/AppContainerModel.ts
=> More cleanup of AppContainerModel:InitAsync

CHANGELOG.md, admin/tabs/monitor/MonitorColumns.ts, admin/tabs/monitor/MonitorEditorPanel.ts, admin/tabs/monitor/MonitorResultsModel.ts, admin/tabs/monitor/MonitorResultsPanel.ts, admin/tabs/monitor/MonitorTab.ts, admin/tabs/monitor/Tile.scss, admin/tabs/monitor/Tile.ts, admin/tabs/monitor/Types.ts, desktop/cmp/rest/RestGridModel.ts, desktop/cmp/rest/impl/RestFormModel.ts
=> Make status monitoring multi-instance aware + add default monitors

CHANGELOG.md, static/preflight.js
=> Apply preflight error check hotfix, update Changelog

cmp/grid/Grid.scss
=> Aligned the inline editing badge with an edited row

admin/tabs/cluster/ClusterTabModel.ts
=> Cluster tab refresh fix

security/BaseOAuthClient.ts, security/TokenInfo.ts, security/authzero/AuthZeroClient.ts, security/msal/MsalClient.ts
+ Add type for AccessToken configs …
=> Auth0 audience for Access Token only

core/types/Types.ts
=> Add NonEmptyArray convenience type

security/BaseOAuthClient.ts, security/authzero/AuthZeroClient.ts, security/msal/MsalClient.ts
- [ X] Caught up with `develop` branch as of last change. …
=> Cleanups and Prompt

CHANGELOG.md, security/BaseOAuthClient.ts, security/Token.ts, security/TokenInfo.ts, security/authzero/AuthZeroClient.ts, security/authzero/index.ts, security/msal/MsalClient.ts, security/msal/index.ts, svc/FetchService.ts
=> New OAuth API

security/BaseOAuthClient.ts, security/msal/MsalClient.ts
+ New 'initRefreshTokenExpirationOffsetSecs' for MsalClient.
+ Fallback to login on any uncaught exception during MsalClients initial attempt to acquire tokens
+ Quiet chatty msal logging …
=> Support refreshTokenExpirationOffsetSecs for MsalClient.

appcontainer/AppContainerModel.ts, security/BaseOAuthClient.ts, security/authzero/AuthZeroClient.ts, security/msal/MsalClient.ts, svc/LocalStorageService.ts
=> OAuthClients: Improved support for SSO/Improvements to Logging and docs

CHANGELOG.md, core/HoistComponent.ts, core/HoistProps.ts, core/elem.ts, desktop/cmp/input/ButtonGroupInput.ts, mobile/appcontainer/ToastSource.ts, utils/react/LayoutPropUtils.ts
=> Typescript: Improve `ref` typing in JSX

admin/tabs/userData/roles/RoleModel.ts
=> Roles Grid tweaks

CHANGELOG.md, appcontainer/AppContainerModel.ts
=> Mobile orientation zoom fix

desktop/cmp/treemap/SplitTreeMapModel.ts
- [ X Created Toolbox branch / PR, or determined not required. …
=> Export SplitTreeMapConfig interface

cmp/zoneGrid/ZoneGridModel.ts, cmp/zoneGrid/impl/ZoneGridRenderer.ts
=> ZoneGrid should accept 'false' as a value for it's delimiter property

desktop/cmp/filechooser/FileChooser.ts
FileChooser will accept a maxFiles prop
=> fix/ #3570 FileChooser should accept a maxFiles prop

CHANGELOG.md, core/XH.ts
=> * New option for `XH.reloadApp` to reload specific app path.

CHANGELOG.md, data/impl/StoreValidator.ts
=> Validate records added immediately to new store

CHANGELOG.md, cmp/layout/Viewport.scss, mobile/appcontainer/Toast.scss, mobile/cmp/dialog/Dialog.scss, mobile/cmp/menu/impl/Menu.scss, mobile/cmp/panel/DialogPanel.scss
=> Update styles using `svh|svw` units to `dvh|dvw`

CHANGELOG.md, appcontainer/AppContainerModel.ts, appcontainer/login/LoginPanelModel.ts, core/AppSpec.ts, core/HoistAppModel.ts, core/HoistAuthModel.ts, core/XH.ts, core/index.ts, desktop/cmp/button/AppMenuButton.ts, desktop/cmp/button/LogoutButton.ts, mobile/appcontainer/LockoutPanel.ts, mobile/cmp/button/LogoutButton.ts, mobile/cmp/header/AppMenuButton.ts, svc/IdentityService.ts
See also toolbox branch with the same name …
=> New Client-Side AuthModel

CHANGELOG.md, cmp/grid/columns/ColumnGroup.ts
Had a spare 10 minutes so banged this one out. Closes https://github.com/xh/hoist-react/issues/3648 …
=> Added `headerTooltip` prop to `ColumnGroup`

CHANGELOG.md, desktop/cmp/grid/editors/NumberEditor.ts, desktop/cmp/input/NumberInput.ts, mobile/cmp/input/NumberInput.ts
=> Fixed numberInput losing quick edits due to debounce

CHANGELOG.md, security/BaseOAuthClient.ts, security/msal/MsalClient.ts
+ Use blank URL for all silent requests (as per https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/errors.md#issues-caused-by-the-redirecturi-page)
+ Use blank URL for popup login (as before, just made explicit in call to `client.acquireTokenPopup`
+ Use redirect URL for redirect login (as before, just made explicit in call to `client.acquireTokenRedirect`
+ Remove unused `MsalClientConfig.tenantId`
+ Minor doc comment tweaks
**If your change is still a WIP**, please use the "Create …
=> Update `MsalClient` to explicitly pass baseApp vs. blank redirect URLs

CHANGELOG.md, cmp/markdown/Markdown.ts
=> Add `components` prop to Markdown component

CHANGELOG.md, appcontainer/RouterModel.ts, cmp/badge/Badge.ts, cmp/chart/Chart.ts, cmp/chart/ChartModel.ts, cmp/chart/impl/copyToClipboard.ts, cmp/dataview/DataView.ts, cmp/layout/Box.ts, desktop/cmp/input/Select.ts, desktop/cmp/rest/impl/RestFormModel.ts, desktop/cmp/treemap/TreeMap.ts, mobile/cmp/input/Select.ts, mobile/cmp/navigator/NavigatorModel.ts, utils/js/LangUtils.ts
=> Implement and use mergeDeep

cmp/grid/GridSorter.ts
=> GridSorter.parse() return null if called with null/undefined cfg

data/cube/row/LeafRow.ts
=> Add + set `LeafRow.cubeRecordId`

CHANGELOG.md, security/authzero/AuthZeroClient.ts, security/msal/MsalClient.ts
=> Support passing configs through to OAuth client library constructors

CHANGELOG.md, cmp/grid/GridModel.ts, desktop/cmp/leftrightchooser/LeftRightChooserModel.ts
=> Remove context menus from colChooser, allow "false" contextMenu param for GridModel.

CHANGELOG.md, admin/tabs/monitor/editor/MonitorEditorDialog.ts
=> fix(monitor-editor): swap locations of 'active' and 'primary' sliders

admin/tabs/userData/roles/recategorize/RecategorizeDialog.ts, admin/tabs/userData/roles/recategorize/RecategorizeDialogModel.ts
=> Mask dialog when saving role category

desktop/appcontainer/LockoutPanel.ts
=> Account for impersonation more thoroughly in LockoutPanel messaging

format/FormatNumber.ts
=> Improve `NumberFormatOptions.zeroPad` handling of unexpected precision

core/exception/ExceptionHandler.ts
=> Remove Hoist finger pointing

core/XH.ts
=> Add `XH.postJson()` convenience alias

CHANGELOG.md, promise/Promise.ts
=> Correct types of enhanced `Promise` methods

admin/tabs/cluster/BaseInstanceModel.ts, admin/tabs/cluster/services/DetailsModel.ts
=> Backward-compatible tweaks relating to HoistCore update to Service Admin

CHANGELOG.md, admin/tabs/general/alertBanner/AlertBannerModel.ts, admin/tabs/general/alertBanner/AlertBannerPanel.ts, svc/AlertBannerService.ts, svc/EnvironmentService.ts
=> Deliver Alert Banner data with environment polling

CHANGELOG.md, cmp/markdown/Markdown.ts
=> Accept remark and rehype plugin props to the markdown component

admin/tabs/activity/clienterrors/ClientErrorsModel.ts, admin/tabs/activity/clienterrors/ClientErrorsPanel.ts, admin/tabs/activity/tracking/ActivityTrackingModel.ts, admin/tabs/activity/tracking/ActivityTrackingPanel.ts
=> Added button selection to admin day range toolbars

data/cube/View.ts
=> Prevent wiring up a Store that `idEncodesTreePath` to a Cube with a `bucketSpecFn` or `omitFn`

desktop/cmp/input/CodeInput.ts
=> Correct code input commitOnChange documentation

CHANGELOG.md, cmp/viewmanager/ViewManagerModel.ts, cmp/viewmanager/ViewToBlobApi.ts, core/exception/ExceptionHandler.ts, desktop/cmp/viewmanager/ViewManager.ts, desktop/cmp/viewmanager/ViewManagerLocalModel.ts, desktop/cmp/viewmanager/dialog/ManageDialog.ts, desktop/cmp/viewmanager/dialog/ManageDialogModel.ts, desktop/cmp/viewmanager/dialog/ViewMultiPanel.ts, desktop/cmp/viewmanager/dialog/ViewPanel.ts, desktop/cmp/viewmanager/dialog/ViewPanelModel.ts
=> View manager enhancements

data/filter/CompoundFilter.ts, data/filter/FieldFilter.ts, data/filter/Filter.ts, data/filter/FunctionFilter.ts, data/filter/Types.ts, desktop/cmp/grid/impl/filter/GridFilterDialog.ts
See issue: https://github.com/xh/hoist-react/issues/3812 …
=> Move toJSON to base Filter class

CHANGELOG.md, desktop/cmp/button/RefreshButton.ts, desktop/cmp/rest/impl/RestGridToolbar.ts, desktop/cmp/viewmanager/dialog/ManageDialog.ts, mobile/cmp/button/RefreshButton.ts
=> RefreshButton takes target instead of model

svc/GridExportService.ts
As a bonus, removed some runtime checking that seems fully obsoleted by typescript. …
=> Support TrackOptions for Export

CHANGELOG.md, core/persist/PersistOptions.ts
=> Improve accuracy + JSDoc of `PersistOptions.type` enum

cmp/viewmanager/DataAccess.ts, cmp/viewmanager/ViewManagerModel.ts, desktop/cmp/viewmanager/ViewMenu.ts, desktop/cmp/viewmanager/dialog/SaveAsDialogModel.ts
=> Minor fixes to Views

admin/tabs/cluster/distobjects/DistributedObjectsModel.ts, cmp/viewmanager/ViewManagerModel.ts, desktop/cmp/viewmanager/dialog/ViewPanelModel.ts
=> Multi instance compare2

CHANGELOG.md, core/HoistBase.ts
Can be tested with this minor version release: 
72.0.0-SNAPSHOT.1736808794610
> …
=> Improve signature of `HoistBase.markPersist`

security/BaseOAuthClient.ts, security/authzero/AuthZeroClient.ts, security/msal/MsalClient.ts
=> Handle edge-case where OAuth redirect opens new tab instead

CHANGELOG.md, cmp/viewmanager/ViewManagerModel.ts
=> Fix `ViewManagerModel` unique name validation

CHANGELOG.md, cmp/grid/GridModel.ts
=> Respect default filter in GridModel.restoreDefaultsAsync

CHANGELOG.md, admin/tabs/userData/roles/RoleModel.ts
=> Don't auto-expand Role Manager tree grid on refresh

CHANGELOG.md, cmp/filter/FilterChooserModel.ts, cmp/grid/impl/InitPersist.ts, cmp/grouping/GroupingChooserModel.ts, cmp/zoneGrid/impl/InitPersist.ts, core/HoistBase.ts, core/HoistBaseDecorators.ts, core/persist/PersistenceProvider.ts
=> Improve PersistOptions merging

data/cube/row/BaseRow.ts
=> Fix BaseRow.getVisibleChildrenDatas to return null rather than [null]

CHANGELOG.md, admin/tabs/userData/roles/editor/form/RoleFormModel.ts, data/Store.ts, data/StoreRecord.ts
=> New isDirty aliases.

core/HoistProps.ts, utils/react/LayoutPropUtils.ts
=> Support `gap` as `LayoutProp`

admin/tabs/userData/roles/recategorize/RecategorizeDialogModel.ts
=> Close role category change dialog after save then refresh parent

CHANGELOG.md, core/exception/Exception.ts
=> Make FetchService Exception Parsing more flexible 

CHANGELOG.md, admin/tabs/activity/clienterrors/ClientErrorsModel.ts
=> Dedicated cols in Admin Client Errors for error names and messages

security/BaseOAuthClient.ts, security/Token.ts, security/Types.ts, security/authzero/AuthZeroClient.ts, security/msal/MsalClient.ts
Still a draft, as I have not run/tested this code.  Just trying to fast track reviewing the idea. …
=> Add FetchMode for AccessTokens

security/BaseOAuthClient.ts
=> Minor refactor to BaseOAuthClient.fetchAllTokensAsync

security/BaseOAuthClient.ts, security/Types.ts
=> Mark `AccessTokenSpec.fetchMode` as optional, with `eager` as default

CHANGELOG.md, appcontainer/AppStateModel.ts, package.json, security/BaseOAuthClient.ts, security/Types.ts, security/msal/MsalClient.ts, svc/FetchService.ts, svc/TrackService.ts, utils/js/BrowserUtils.ts, yarn.lock
=> MSAL v4.8 w/telemetry + include headers cb in `FetchService` track timing

CHANGELOG.md, security/Types.ts, security/msal/MsalClient.ts, svc/WebSocketService.ts
=> Add telemetry report to `WebSocketService`

svc/WebSocketService.ts
=> Throw if methods called on disabled WebSocketService

CHANGELOG.md, cmp/store/StoreCountLabel.ts
=> Make StoreCountLabelProps.store required

CHANGELOG.md, mobile/cmp/grid/impl/ColChooser.scss, mobile/cmp/grid/impl/ColChooser.ts
See issue https://github.com/xh/hoist-react/issues/3960 for more details
> single …
=> Fix mobile column chooser usability issues

CHANGELOG.md, desktop/cmp/input/DateInput.ts, desktop/cmp/input/NumberInput.ts, desktop/cmp/input/TextInput.ts, mobile/cmp/input/DateInput.ts, mobile/cmp/input/NumberInput.ts, mobile/cmp/input/SearchInput.ts, mobile/cmp/input/TextInput.ts
=> Correct textAlign type

CHANGELOG.md, admin/AppModel.ts, core/XH.ts, desktop/appcontainer/VersionBar.ts, desktop/cmp/button/AppMenuButton.ts, desktop/cmp/button/LaunchAdminButton.ts
Important -- Also adding the reusing of some windows, here and in toolbox!
Please merge toolbox branch with same name at the same time. …
=> XH.OpenInTab

CHANGELOG.md, core/HoistBase.ts, mobx/overrides.ts
=> Add new check for makeObservable on HoistBase

core/HoistAppModel.ts, desktop/appcontainer/VersionBar.scss, desktop/appcontainer/VersionBar.ts, mobile/appcontainer/VersionBar.ts, svc/ClientHealthService.ts
=> Tweaks to show IDs in About Box, version bar

promise/Promise.ts
=> Don't track auto-aborted fetch calls (and other routine exceptions)

CHANGELOG.md, desktop/cmp/button/AppMenuButton.ts, desktop/cmp/viewmanager/ViewManager.ts, desktop/cmp/viewmanager/ViewMenu.ts, utils/impl/MenuItems.ts, utils/impl/index.ts
+ Moved `parseMenuItems` to reusable util …
=> Added `extraMenuItems` to `ViewManager`

CHANGELOG.md, desktop/cmp/dash/canvas/DashCanvasModel.ts, desktop/cmp/dash/canvas/impl/DashCanvasView.ts
+ hide Add context menu item in views in if allowAdd=false …
=> #4028 - ensure allowAdd=false is not enforced if loadingState

CHANGELOG.md, desktop/cmp/dash/canvas/DashCanvas.scss
Paired with toolbox pr: https://github.com/xh/toolbox/pull/769 …
=> Adjust `DashCanvas` style to `position: relative`

security/BaseOAuthClient.ts
=> Don't rely on clientAppCode for `BaseOAuthClient.baseUrl`

CHANGELOG.md, cmp/grouping/GroupingChooserModel.ts, desktop/cmp/grouping/GroupingChooser.ts, mobile/cmp/grouping/GroupingChooser.ts
- Can be set to false to respect the order in which dimensions are provided to the model. …
=> Added new `GroupingChooserModel.sortDimensions` config

CHANGELOG.md, admin/tabs/clients/activity/ClientDetailPanel.ts, admin/tabs/general/alertBanner/AlertBannerPanel.ts, cmp/relativetimestamp/RelativeTimestamp.ts
Great suggestion.  
Please merge also the toolbox branch with same name.
> single …
=> Streamline RelativeTimetstamp Component

cmp/grid/GridModel.ts, cmp/grid/impl/MenuSupport.ts, desktop/cmp/button/grid/ExpandToLevelButton.ts, mobile/cmp/button/grid/ExpandToLevelButton.ts
=> DRY for level label handling + restore default level

desktop/cmp/panel/impl/dragger/DraggerModel.ts
=> Fix panel resizing on Firefox

cmp/grid/Grid.ts, cmp/grid/GridModel.ts
Take 2 on this.  Realize we are using the agAPI in a somewhat crazed way here, but I tried to comment appropriately.
Happy to discuss.
Please note the first change to doWithPreservedState is just removing some unused cruft.
Thanks for catching the error Anselm.
> collapse …
=> Expand state fix

CHANGELOG.md, cmp/relativetimestamp/RelativeTimestamp.ts, core/load/LoadSpec.ts, desktop/cmp/filechooser/FileChooserModel.ts, desktop/cmp/grouping/GroupingChooser.ts, svc/FetchService.ts, svc/IdentityService.ts, utils/js/LangUtils.ts, utils/js/LogUtils.ts
+ Remove some outstanding deprecations …
=> Enhancements to `apiDeprecated`.

CHANGELOG.md, desktop/cmp/grid/impl/filter/headerfilter/HeaderFilter.ts, desktop/cmp/grid/impl/filter/headerfilter/HeaderFilterModel.ts, desktop/cmp/grid/impl/filter/headerfilter/values/ValuesTabModel.ts
=> Commit grid column filter changes on `enter` + cancel on `esc`

CHANGELOG.md, cmp/viewmanager/ViewManagerModel.ts, core/HoistAppModel.ts, core/XH.ts, svc/PrefService.ts
See Hoist Core as well.
Note added Track statement. …
=> Clear view state
